### ISSUE TITLE
如何在Field内添加图片元素呢。

### ISSUE THREAD

**Issue by zhuqiuyang** [ElemeFE/mint-ui#100]
想做出验证码图片显示在输入框的右边，请问想嵌入field元素中如何实现呢。

**Comment by QingWei-Li** [comment]
暂时没提供，我后面加个 slot

**Comment by zhuqiuyang** [comment]
@QingWei-Li 好的，3q啦~

**Comment by QingWei-Li** [comment]
fixed https://github.com/ElemeFE/mint-ui/commit/8507c7adfc5da747406ee354596474a7686dc424
