### ISSUE TITLE
picker组件 如何设置初始选中值？

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/mint-ui#101]
picker组件 如何设置初始选中值？比如一渲染出来的时候就是选中第6排

**Comment by Leopoldthecoder** [comment]
ok，我加一下这个功能

**Comment by Leopoldthecoder** [comment]
请升级到 0.1.13 版，现在可以在 `slots` 数组的对象中添加 `defaultIndex` 键，表示的是初始选中值在 `values

**Comment by Leopoldthecoder** [comment]
请升级到 0.1.13 版，现在可以在 `slots` 数组的对象中添加 `defaultIndex` 键，表示的是初始选中值在 `values` 数组中的序号，默认为 0

**Comment by acmeid** [comment]
谢谢！

**Comment by yezongyang** [comment]
从源码里看defaultIndex初始化时并没有用到， 只有一个watch，也就是只在变化时使用

**Comment by CaTmmao** [comment]
为毛我设置了还是没用啊

**Comment by xwLyc** [comment]
> 为毛我设置了还是没用啊

我之前设置也没效果，后来发现需要 在数据声明 的时候就要加上 defaultIndex 属性，后面方法才有效。
