### ISSUE TITLE
[Bug Report] Datetime-picker not popup when click the button

### ISSUE THREAD

**Issue by miyalee** [ElemeFE/mint-ui#1018]
### Mint UI version
2.2.8

### OS/Browsers version
mac/chrome

### Vue version
2.3.3

### Reproduction Link
[https://jsfiddle.net/miyalee/pj71jkyw/418/](https://jsfiddle.net/miyalee/pj71jkyw/418/)

### Steps to reproduce
just run it and click the button

### What is Expected?
the picker will show like
https://mint-ui.github.io/docs/#/zh-cn2/datetime-picker

### What is actually happening?
nothing happened

comment: 
it is work on version 2.2.7, but has console a error,  
I have note this`<!-- <script src="https://unpkg.com/mint-ui@2.2.7/lib/index.js"></script> -->`, you can try it

I use datetime-picker on my company project，please fix it as soon as possible, thank you

**Comment by Leopoldthecoder** [comment]
Fixed in 2.2.9

**Comment by miyalee** [comment]
@Leopoldthecoder 好快！谢谢
