### ISSUE TITLE
[Bug Report] Picker defaultIndex 初始化没有作用

### ISSUE THREAD

**Issue by yezongyang** [ElemeFE/mint-ui#1035]
### Mint UI version
2.2.9

### OS/Browsers version
mac/chrome59

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/191224x2/5/](https://jsfiddle.net/191224x2/5/)

### Steps to reproduce
1.把官网数据拷贝一份
2.查看picker显示默认是否被选中

### What is Expected?
默认应该选中defaultInex=0的选项

### What is actually happening?
实际默认没有选中，查看源代码发现defaultIndex watch了，所以只有在改变的时候有作用

**Comment by Hsensor** [comment]
picker-sllot.vue
watch defaultIndex , set immediate: true

**Comment by yezongyang** [comment]
@Hsensor  什么意思

**Comment by xiaotaoyan-z** [comment]
同问，defaultIndex在初始化时设置没用，想知道怎么处理的

**Comment by yezongyang** [comment]
手动设置defaultIndex 是有用的，但是必须满足之前的defaultIndex 和你设置的不同 @xiaotaoyan-z

**Comment by Hsensor** [comment]
`defaultIndex: {
        handler(val) {
          console.log('-------1', this.defaultIndex);
          if ((this.mutatingValues[val] !== undefined) && (this.mutatingValues.length >= val + 1)) {
            this.currentValue = this.mutatingValues[val];
          }
        },
        immediate: true
      }`

**Comment by xiaotaoyan-z** [comment]
@yezongyang 小白问下怎么手动设置defaultIndex
