### ISSUE TITLE
[Feature Request] Picker当前可以用对象数组的形式，但是不能被选中

### ISSUE THREAD

**Issue by yezongyang** [ElemeFE/mint-ui#1036]
### Existing Component
是

### Component Name
Picker

### Description
如果Picke里传递对象数组， 但是查找用的是indexOf方法, 对比用的是'==='符号，针对对象是不能查找和比较相等的。

**Comment by openks** [comment]
@yezongyang 这个是已经存在功能可能说明文档写的不是很清楚 看下这个是否符合你的要求
 https://github.com/openks/learn-vue/issues/22

**Comment by yezongyang** [comment]
@openks 用对象数组的情况， 如果用picker.setValues 不会选中设置的值，从源码来看， 查找用的indexOf，相等比较用的是===

**Comment by openks** [comment]
额，这个应该是我没理解你的意思
