### ISSUE TITLE
[Bug Report] mt-cell to使用router无法传递参数

### ISSUE THREAD

**Issue by openks** [ElemeFE/mint-ui#1039]
### Mint UI version
2.2.9

### OS/Browsers version
mac os 10.12.5 /版本 62.0.3175.4（正式版本）dev （64 位）

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/zyxcn/ym1nek3q/2/](https://jsfiddle.net/zyxcn/ym1nek3q/2/)

### Steps to reproduce
点击mt-cell 跳转到foo页，但是无法显示传递过来的参数 demo里是id

### What is Expected?
demo里能显示正常id

### What is actually happening?
demo里不能显示正常id

**Comment by openks** [comment]
解决方案  
使用自定义方法想带啥参数就带啥参数 
`to`只适用于页面跳转
```js
<mt-cell
 v-for="(item,index) in list"  
 is-link 
 :title="item.text" 
 :key="index"  
 @click.native="goGoGo(item)">
     <img slot="icon" :src="item.icon" width="24" height="24">
</mt-cell>
```

**Comment by DusuWen** [comment]
下边js改成
`path: '/foo/:id',
	name: 'foo',
  component: Foo}`

**Comment by openks** [comment]
``` vue
  <mt-cell title="路由跳转" label="跳转到 /#/toast222" is-link :to="{name: 'foo',params:{'id':1112}}"></mt-cell>
```
这种方式也可以 
```js
  computed: {
    href() {
      if (this.to && !this.added && this.$router) {
        const resolved = this.$router.match(this.to);
        if (!resolved.matched.length) return this.to;

        this.$nextTick(() => {
          this.added = true;
          this.$el.addEventListener('click', this.handleClick);
        });
        return resolved.path;
      }
      return this.to;
    }
  },
```
只要在`resolved.path`里就ok    
感觉没有自己写事件来的方便
