### ISSUE TITLE
搜索组件的放大镜icon显示位置偏上

### ISSUE THREAD

**Issue by Lxxyx** [ElemeFE/mint-ui#104]
```
<template>
  <mt-search
    :value.sync="results"
    cancel-text="取消"
    placeholder="搜索">
  </mt-search>
</template>
```
实际效果： 手机和电脑都这样。
![pic](http://7xpbyo.com1.z0.glb.clouddn.com/search.png)

**Comment by QingWei-Li** [comment]
哪个版本的 mint ? 什么浏览器或手机型号

**Comment by Lxxyx** [comment]
@QingWei-Li 
版本：0.1.14
浏览器：chrome canary 53
手机：一加1，氢OS 5.1。手机浏览器chrome dev 53
