### ISSUE TITLE
0.1.14中，部分js组件的css未加载。

### ISSUE THREAD

**Issue by Lxxyx** [ElemeFE/mint-ui#105]
浏览器：chrome 53
测试： 0.1.14中。使用toast, MessageBox等组件均出现样式破损，检查后发现css类名中并没有相应的属性，应该是css未加载。
测试2： 使用0.1.3，则恢复正常。

使用的安装方法: （测试仅切换版本，未做其它改动。）
```javascript
import Vue from 'vue';
import MintUI from 'mint-ui';
import 'mint-ui/lib/style.css';

Vue.use(MintUI);
```

**Comment by QingWei-Li** [comment]
已发新版 0.1.15

**Comment by Lxxyx** [comment]
@QingWei-Li 速度很快，点个赞~
