### ISSUE TITLE
[Bug Report] picker设置了defaultIndex不起作用？显示错位 中间栏也是未选中状态

### ISSUE THREAD

**Issue by cwc845982120** [ElemeFE/mint-ui#1059]
### Mint UI version
2.2.8

### OS/Browsers version
macOS chrome

### Vue version
2.3.3

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN?repo=mint](https://elementui.github.io/issue-generator/#/zh-CN?repo=mint)

### Steps to reproduce
点击优惠折扣

### What is Expected?
picker默认选择正确（原重现网址输入无效，点击优惠折扣）

### What is actually happening?
picker默认没有选择而且好像错位了 没有selected选项（原重现网址输入无效，点击优惠折扣）

**Comment by cwc845982120** [comment]
我设置了defaultIndex默认为8
![7d968759-0e66-4d96-8b24-67be9df7b8da](https://user-images.githubusercontent.com/17759619/29460476-b54f2fa4-845a-11e7-8fc0-17869957f892.png)
<img width="688" alt="wx20170818-210322 2x" src="https://user-images.githubusercontent.com/17759619/29460478-b6baf06c-845a-11e7-964a-97b2ccad9b52.png">
<img width="720" alt="wx20170818-210340 2x" src="https://user-images.githubusercontent.com/17759619/29460480-b84613da-845a-11e7-8a5f-e9892600b2b3.png">
<img width="237" alt="wx20170818-210405 2x" src="https://user-images.githubusercontent.com/17759619/29460482-b9a6fe56-845a-11e7-853c-37fe2a1e2247.png">

**Comment by lzcmaro** [comment]
这个组件有BUG，刚提了PR，https://github.com/ElemeFE/mint-ui/pull/1071

**Comment by cwc845982120** [comment]
然后 我用了popup组件 是否会出现事件击穿现象 就是我滑动popup 下面的body也会跟着滑动。

**Comment by anightrabbit** [comment]
最新的版本的"mint-ui": "^2.2.9",并没有修复这个问题。

**Comment by superfff** [comment]
最新版本的 "^2.2.9" 还是存在这个问题.
如果slot使用 [{value,key}...] 这样形式的使用defaultIndex不生效.
以及使用picker 设定好的方法setValues也不生效...

**Comment by yezongyang** [comment]
@superfff  设置选中对象值的时候，数据不要使用新建的对象，需要从slot数组里取值，然后用这个对象值。
源码里判断相等是用===来判断的， 所以setValues里的需要传递指向同样地址的引用对象

**Comment by superfff** [comment]
@yezongyang 
后面我直接调用实例的setValues就解决了.感谢你.
不过建议下一版的indicator组件.
这个类.mint-indicator-wrapper  加上z-index.
在ios不会, 在安卓上面有时候如果内容里面有div用了absolute,z-index起来,就会被遮住尴尬 - -

**Comment by HP-jackZhang** [comment]
具体是怎么解决的呢？@superfff
