### ISSUE TITLE
[Bug Report]Loadmore 组件中的:bottom-method="loadBottom"方法每次页面初始化的时候都会执行一次

### ISSUE THREAD

**Issue by Recklesslmz** [ElemeFE/mint-ui#1069]
> 饿了么小伙伴你们好，我目前遇到的问题是使用loadmore组件的时候，`:bottom-method`的方法会在数据没有占到底层的时候会触发，举个例子，比我我有二十条数据，分页为每页10条，那么`:bottom-method`这个方法就不会在初始化的时候触发，但是假使我只有一两条数据，这个`:bottom-method`方法就会自己执行一次。请问这个问题该如何解决呢~

**Comment by JsonLeex** [comment]
![image](https://user-images.githubusercontent.com/25883665/29960266-8fc8305e-8f2d-11e7-88c3-fa694e6b3e29.png)
设置autoFill为false
