### ISSUE TITLE
如何使用 vue-cli 生成的项目中使用

### ISSUE THREAD

**Issue by exoticknight** [ElemeFE/mint-ui#107]
急
用的模板是 webpack-simple，babel 按照文档配置了，希望单独引入 picker
暂时出现的问题是，style 似乎没有效果

**Comment by Leopoldthecoder** [comment]
单独引入 picker 以外的组件有效果吗？

**Comment by QingWei-Li** [comment]
@exoticknight 
如果只需要 picker 可以单独安装 `mint-picker`，我测试了下用 webpack-simple 后安装 style-loader 并配置 
css loader 是可以正常运行的，所以你说的没有效果只是什么

**Comment by exoticknight** [comment]
@Leopoldthecoder 似乎是，查看了一下似乎的确是没有引入 css，不知我是哪里搞错了

**Comment by exoticknight** [comment]
@QingWei-Li 港真，那个我也试过了……出现了另外的问题，现在紧急改成用 vux 了，项目过后我再看看究竟什么问题吧……

**Comment by exoticknight** [comment]
@QingWei-Li 
项目过了，再来讨论……
我重开了一个新项目，你看看我步骤有没有问题：

1. vue-cli 创建一个 webpack-simple 项目
1. npm i mint-ui -S
1. npm i babel-plugin-component -D
1. webpack.config.js 加上
```javascript
{
        test: /\.css$/,
        loader: 'css-loader',
      }
```
1. .babelrc
```json
{
  "plugins": ["other-plugin", ["component", [
    { "libraryName": "mint-ui", "style": true }
  ]]]
}
```
1. App.vue
```javascript
import Vue from 'vue';
import MintUI from 'mint-ui';
Vue.use(MintUI);
...
```

最后发现还是没有 css 的引入

**Comment by QingWei-Li** [comment]
@exoticknight 
.... css 还需要用 style-loader 不然不会内联到 DOM 上 

```javascript
{
  test: /\.css$/,
  loader: 'style!css'
}
```

**Comment by exoticknight** [comment]
@QingWei-Li 
原来如此！可以了！:tada:
