### ISSUE TITLE
vue组件中的style声明

### ISSUE THREAD

**Issue by chenEdgar** [ElemeFE/mint-ui#108]
vue组件中的style声明 lang = "css",  为什么却有能使用变量和混合等呢，感觉像是scss语法。package.json 中没有看到scss相关的插件依赖， 查了cooking的配置，也没有将scss集成进去。

请问mini-ui中的style 设置为lang = “css”， 为什么能使用变量等呢？

**Comment by QingWei-Li** [comment]
一个 postcss 插件 https://github.com/ElemeFE/postcss-salad，
配置在 cooking 的 extends: ['saladcss']

**Comment by chenEdgar** [comment]
谢谢
