### ISSUE TITLE
[Feature Request] 请及时更新文档！！！！！

### ISSUE THREAD

**Issue by joenil** [ElemeFE/mint-ui#1082]
### Existing Component
是

### Component Name
DateTimePicker

### Description
我可以接受没有中文文档，但既然出了就请保持和英文文档一起同步，关于这个DateTimePicker的中文文档上面还写着通过传入visible的props，但最新的代码已经去掉了，而是通过暴露出的open和close方法来控制，找了半天才发现问题。我很感谢饿了么能够提供这么精美的UI库，来帮助开发者节省时间，但从文档上我已经感觉到团队慢慢的开始违背初衷，真的不够用心。

**Comment by joenil** [comment]
犯傻了，看到1.x的文档去了，应该看中文2.0，建议优化一下文档的展示，把不太重要的隐藏起来，具体参考vue官网，把版本放进一个下拉菜单里。

**Comment by Kuohao-wu** [comment]
最新的dateTimePicker添加了cancel事件，文档也没有更新，来github看了才知道
