### ISSUE TITLE
[Bug Report] defaultIndex not work in picker component

### ISSUE THREAD

**Issue by love-yoyo** [ElemeFE/mint-ui#1088]
### Mint UI version
2.2.9

### OS/Browsers version
chrome

### Vue version
2.4.2

### Reproduction Link
[https://github.com/ElemeFE/mint-ui/blob/c696c4e90247697726d6b08b183254f116440537/packages/picker/src/picker.vue#L103](https://github.com/ElemeFE/mint-ui/blob/c696c4e90247697726d6b08b183254f116440537/packages/picker/src/picker.vue#L103)

### Steps to reproduce
you may fix like below:    
   
   values[slot.valueIndex] = (slot.values || [])[slot.defaultIndex || 0];     
==>   
   this.values[slot.valueIndex] = (slot.values || [])[slot.defaultIndex || 0];

### What is Expected?
can set default select item in component picker

### What is actually happening?
cannot set default select item where use defaultIndex in property slots

**Comment by javascripet** [comment]
我也遇到了, 不能设定默认值还导致报错

**Comment by web-yuzm** [comment]
2.2.7之前好像不会出现默认值不出现的问题，这两天重新安装了2.2.9，默认的没有掉了

**Comment by zhylmzr** [comment]
我遇到了同样的问题, 不设置defaultIndex是不会默认选中任何项的, 设置了也没有效果
