### ISSUE TITLE
[Bug Report] dater-picker中使用了picker组件，但是并没有将picker的部分属性暴露出来，类似itemHeight

### ISSUE THREAD

**Issue by LanceXuGood** [ElemeFE/mint-ui#1098]
### Mint UI version
2.2.9

### OS/Browsers version
w10/all

### Vue version
2.0.3

### Reproduction Link
[https://mint-ui.github.io/docs/#/zh-cn2/datetime-picker](https://mint-ui.github.io/docs/#/zh-cn2/datetime-picker)

### Steps to reproduce
项目中date-picker组件内的行高在iphone6p下太小。

### What is Expected?
希望能够将picker的样式属性暴露给date-picker

### What is actually happening?
希望能够将picker的样式属性暴露给date-picker

**Comment by LanceXuGood** [comment]
可以在组件注册的时候，去修改default的值。

**Comment by xspurs** [comment]
请问如何在组件注册的时候修改default值？求指教，多谢
