### ISSUE TITLE
tabbar和tabcontainer不能关联

### ISSUE THREAD

**Issue by chenEdgar** [ElemeFE/mint-ui#110]
需求:类似tabbar例子，切换tab， tabbar同步切换

使用：结合tabbar和tabcontainer，按照官网给出的结构写的。
点击tab后，tabcontainer没有切换，还是处于display:none。
通过vuetool 观察到 active一直是undefined。

组件是以对象的形式注册的

截图：
vue组件：
![image](https://cloud.githubusercontent.com/assets/12596622/16478898/61be581e-3ecf-11e6-82ef-17fc29dd7405.png)

vue树
![image](https://cloud.githubusercontent.com/assets/12596622/16478874/413f6704-3ecf-11e6-9ad5-dd0c200dcdff.png)

**Comment by QingWei-Li** [comment]
`tab-container` 里的 selected 要和 `tabbar` 的 selected 一致才行。
```html
<tab-container :active.sync="selected">
<tabbar :selected.sync="selected">
```
参考 example 里的代码

**Comment by chenEdgar** [comment]
已解决。谢谢

**Comment by chenEdgar** [comment]
第一次用中文做为id。。
