### ISSUE TITLE
[Feature Request] 因为打包之后的vendor.js天大，所以我想在vue中引入elementUI的cdn资源，但是还想继续使用vue-cli的开发模式，应该怎么做？

### ISSUE THREAD

**Issue by zhuqitao** [ElemeFE/mint-ui#1109]
### Existing Component
否

### Component Name
no

### Description
因为打包之后的vendor.js天大，所以我想在vue中引入mint的cdn资源，但是还想继续使用vue-cli的开发模式，应该怎么做？

**Comment by LaoHu97** [comment]
webpack.base.conf.js配置  
externals: {
    'vue': 'Vue',
    'element-ui':'ELEMENT',
    'vue-router': 'VueRouter',
    'axios': 'axios'
  },

**Comment by xygahs0801** [comment]
mark

**Comment by xsfxtsxxr** [comment]
直接CDN引入element-ui的index.js,不需要再external里面排除，也不要在main.js里面import了
