### ISSUE TITLE
官网demo页能开放源码么

### ISSUE THREAD

**Issue by wulucxy** [ElemeFE/mint-ui#111]
你好，请问[官网](http://mint-ui.github.io/docs/#!/zh-cn/popup)能开放源码么，很好奇是怎么实现的

**Comment by QingWei-Li** [comment]
https://github.com/mint-ui/docs

**Comment by decadego** [comment]
https://github.com/ElemeFE/mint-ui/tree/master/example

我估计问的是这个吧

**Comment by zhonggedan** [comment]
@decadego 这个是个啥?
