### ISSUE TITLE
popup弹框内部滚动条不显示

### ISSUE THREAD

**Issue by wolfscience** [ElemeFE/mint-ui#1113]
在popup中加入一个可滚动的div元素，class为.scroll-content，css如下，在移动端div内部滚动条不显示。请问是什么原因造成的？有什么好的解决方案么？

`	
.scroll-content{
		height:7rem;	
		overflow-y:scroll;
}
	
.scroll-content::-webkit-scrollbar {
	-webkit-appearance: none;
}
.scroll-content::-webkit-scrollbar:vertical {
	width: 1rem;
}
.scroll-content::-webkit-scrollbar:horizontal {
	height: 1rem;
}
.scroll-content::-webkit-scrollbar-thumb {
  background-color: rgba(0, 0, 0, .5);
  border-radius: 10em;
  border: 2em solid #ffffff;
}
.scroll-content::-webkit-scrollbar-track {
  border-radius: 10em;
  background-color: #ffffff;
}`

**Comment by HP-jackZhang** [comment]
这个问题解决了吗？我用popup 配合 loadmore 也会有类似的问题
