### ISSUE TITLE
[Feature Request] apicloud中页面加在的js内容较大导致应用卡死

### ISSUE THREAD

**Issue by hainuo** [ElemeFE/mint-ui#1118]
### Existing Component
是

### Component Name
Infinite scroll 和Loadmore

### Description
在apicloud中  使用下面的方式引入 mintui

<link rel="stylesheet" href="https://unpkg.com/mint-ui/lib/style.css">

<script src="https://unpkg.com/mint-ui/lib/index.js"></script>

页面无法被打开，界面卡死，CPU发烫严重

希望能够 提供单独打包的方法 自行打包使用 确实不懂的怎么单独打包这两个组件

**Comment by cloudIC** [comment]
似乎和mint-ui关系不大，卡主界面并不是js包过大导致的，单独打包可以采用 webpack 的方式。
