### ISSUE TITLE
Make dev 报错

### ISSUE THREAD

**Issue by zhaozhe0831** [ElemeFE/mint-ui#112]
ERROR in ./src/index.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/zhaozhe/Work/vue/mint-ui/packages/indicator/lib/style.css in /Users/zhaozhe/Work/vue/mint-ui/src
     @ ./src/index.js 25:0-43
貌似是项目里没找到 css，但是项目里也确实是没有 css。

**Comment by QingWei-Li** [comment]
样式文件引用成编译后的了，已经改好了，同步下最新代码

**Comment by zhaozhe0831** [comment]
更新很快！
