### ISSUE TITLE
[Bug Report] 查看示例打不开

### ISSUE THREAD

**Issue by vanstline** [ElemeFE/mint-ui#1126]
### Mint UI version
2.2.9

### OS/Browsers version
Win10 / chrome版本 60.0.3112.101

### Vue version
2.4.4

### Reproduction Link
[http://elemefe.github.io/mint-ui](http://elemefe.github.io/mint-ui)

### Steps to reproduce
进入http://mint-ui.github.io/#!/zh-cn 点击查看示例

### What is Expected?
1

### What is actually happening?
1

**Comment by ccw-kevin** [comment]
请问现在哪里可以查看实例额

**Comment by cloudIC** [comment]
macos 上查看正常，确认下是否 win10 上是否还存在

**Comment by qifenshu** [comment]
@cloudIC 这个问题已经很严肃，网页无法打开不是操作系统的问题。

**Comment by Leopoldthecoder** [comment]
已确认网站本身可以打开。

目前敏感时期，部分地区可能会被墙。请自备梯子再次尝试。
