### ISSUE TITLE
field 组件怎么配合vue-validator呢

### ISSUE THREAD

**Issue by chenEdgar** [ElemeFE/mint-ui#113]
项目中使用了vue-validator作为表单验证的插件
由于form下包含了多个子组件， 这样的话整个表单有三级构成，如图：
注：第三级为引入mint-ui组件
![vue](https://cloud.githubusercontent.com/assets/12596622/16551235/5f3deb7e-41e8-11e6-9dfa-7e99e12aff3f.jpg)

请问min-ui怎么引入validate作为验证器呢

**Comment by QingWei-Li** [comment]
目前看来没办法，看起来 vue-validator 只能作用在原生表单组件上。有什么好的建议或者其他开源项目可以参考的吗？

**Comment by chenEdgar** [comment]
还不知道怎么弄

**Comment by speedornothing** [comment]
有种变通的作法，利用 hidden 表单域，双向绑定，把 validator 规则应用到 hidden 表单域上

**Comment by QingWei-Li** [comment]
1.x 的话可以使用 @speedornothing 提到的方法
2.0 的时候自定义组件也将支持 v-model 这就可以适用 vue-validator 了，我们已经有计划要支持 Vue2.0 了，只是还没排上日程

**Comment by NoraGithub** [comment]
@QingWei-Li 请问实现了吗？：D
