### ISSUE TITLE
[Bug Report] message-box显示状态时，切换浏览器的返回按钮，不会消失

### ISSUE THREAD

**Issue by jasmineY** [ElemeFE/mint-ui#1135]
### Mint UI version
2.2.9

### OS/Browsers version
all

### Vue version
2.4.4

### Reproduction Link
[http://elemefe.github.io/mint-ui/#/](http://elemefe.github.io/mint-ui/#/)

### Steps to reproduce
1.进入上述链接，进入message-box，点击提示框
2.在界面上不进行任何操作
3.点击浏览器的返回按钮或者手机端的返回按钮
4.模态框不会消失

### What is Expected?
使用浏览器 前进 和 后退 按钮促使路由发生变化的时候，message-box能够隐藏

### What is actually happening?
message-box显示状态时，切换浏览器的返回按钮，不会消失

**Comment by cloudIC** [comment]
这是一个通用问题 本质是 pop 之类的弹框是新建的 vue 实例放入在 vue-router 外层。而 vue-router 之类路由库并不会通知到该组件，导致组件没被销毁。 

但是弹框在移动端应该要阻塞用户操作，只有等蒙版去掉后才可后续操作。

如果非要解决该问题，可以在调用该组件的的索引上挂载router回调：
```vue
<script>
beforeRouteLeave (to, from, next) {
  MessageBox.close()
  next()
}
</script>
```

**Comment by jasmineY** [comment]
好的，谢谢你的解答！



maolin.yang@foxmail.com
 
发件人： 云淇淋
发送时间： 2017-10-13 18:48
收件人： ElemeFE/mint-ui
抄送： maomao; Author
主题： Re: [ElemeFE/mint-ui] [Bug Report] message-box显示状态时，切换浏览器的返回按钮，不会消失 (#1135)
这是一个通用问题 本质是 pop 之类的弹框是新建的 vue 实例放入在 vue-router 外层。而 vue-router 之类路由库并不会通知到该组件，导致组件没被销毁。
但是弹框在移动端应该要阻塞用户操作，只有等蒙版去掉后才可后续操作。
如果非要解决该问题，可以在调用该组件的的索引上挂载router回调：
<script>
beforeRouteLeave (to, from, next) {
  MessageBox.close()
  next()
}
</script>
