### ISSUE TITLE
Navbar 不支持回调吗、

### ISSUE THREAD

**Issue by ithack** [ElemeFE/mint-ui#1136]
<navbar v-model="tabIndex" @click="tabClick">
            <tab-item id="1">aa</tab-item>
            <tab-item id="2">bb</tab-item>
        </navbar>
查看api 这个组件不支持回调，也不支持事件绑定吗？

**Comment by xgqfrms** [comment]
# shit api & shit demos

> just using `@click.native`, like vanilla js

https://github.com/ElemeFE/mint-ui/blob/master/example/pages/navbar.vue
