### ISSUE TITLE
[Feature Request] 能否去掉mt-button的type和size属性的校验

### ISSUE THREAD

**Issue by LastHeaven** [ElemeFE/mint-ui#1137]
### Existing Component
是

### Component Name
mt-button

### Description
这个按钮的type只能填'default','danger','primary'，type也就对样式有影响，但是按钮可能会有更多的样式，如success，warning等等，这些都是自定义样式。size属性同理

**Comment by cloudIC** [comment]
去掉验证 但是你写success并不会有效果。还是需要调用者自己修改样式。如果有特殊的按钮形状，可以自己写个按钮组件。
