### ISSUE TITLE
messageBox状态没有同步

### ISSUE THREAD

**Issue by laoxubuer** [ElemeFE/mint-ui#114]
我的页面里有A,B按钮触发两个messageBox，当第一次点击A弹出msgbox的时候，提示内容一切正常，接着点击B，发现msgbox的内容还是A的内容，接着点击A，发现A的内容变成了B的内容。

我是这样引入的，CSS单独拷贝到了自己的CSS文件中,
`import MessageBox from 'mint-ui/lib/msgbox';`

**Comment by laoxubuer** [comment]
好像是和我把@click写在了包裹了checkbox的label上面有关

**Comment by laoxubuer** [comment]
但我发现，prompt点击确定后，点击确定后，action的值是undefined，而点击取消后catch的是cancle

**Comment by Leopoldthecoder** [comment]
Hi，prompt 点击确定后 action 值为 undefined 的问题下个版本会修复。关于状态没有同步的问题，麻烦提供一下代码。

**Comment by Leopoldthecoder** [comment]
prompt 点击确定后 action 值为 undefined 的问题已修复，请升级 0.1.20。出现问题的原因是 [Promise 的 resolve 只能接收一个参数](http://stackoverflow.com/questions/22773920/can-promises-have-multiple-arguments-to-onfulfilled)，所以现在改为把 value 和 action 包成一个对象传给 resolve，可以这样调用：
```javascript
MessageBox.prompt(...).then(({ value, action }) => {
  ...
})
```
或者：
```javascript
MessageBox.prompt(...).then(param => {
  ... // 通过 param.value 和 param.action 访问参数
})
```
若只需要 value，则可以：
```javascript
MessageBox.prompt(...).then(({ value }) => {
  ...
})
```

**Comment by laoxubuer** [comment]
状态没有同步的原因应该就是和我把@click写在了包裹了checkbox的label上面有关，现在改成watch对应的model上的属性值来触发方法就没有问题了

**Comment by laoxubuer** [comment]
更新至最新版，发现依旧是undefined，会不会是没有build

**Comment by Leopoldthecoder** [comment]
是的😂，麻烦升到 0.1.21，抱歉。

**Comment by laoxubuer** [comment]
@Leopoldthecoder 好的，没事儿😂
