### ISSUE TITLE
[Bug Report] 点击空白区域关闭messagebox时，关闭事件无效应

### ISSUE THREAD

**Issue by tyf221578** [ElemeFE/mint-ui#1145]
### Mint UI version
2.2.9

### OS/Browsers version
Mac ／ Chrome

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/GavinPlus/caps4vck/2/](https://jsfiddle.net/GavinPlus/caps4vck/2/)

### Steps to reproduce
1. 点击“按钮”弹出messagebox
2. 在空白区域点击关闭messagebox
3. messagebox可以关闭，但是关闭事件无响应

### What is Expected?
点击空白区域关闭时，catch能够捕获到关闭事件

### What is actually happening?
catch没有捕获到关闭事件

**Comment by cloudIC** [comment]
这个是设计问题 目前点击 modal 不触发点击事件。可以设置下 closeOnClickModal 来让用户点击 modal 不关闭。
