### ISSUE TITLE
[Bug Report] Swipe 组件在手机QQ内置浏览器中过渡效果显示异常

### ISSUE THREAD

**Issue by u3u** [ElemeFE/mint-ui#1148]
### Mint UI version
2.2.9

### OS/Browsers version
iOS11

### Vue version
2.5.2

### Reproduction Link
[http://elemefe.github.io/mint-ui/#/swipe](http://elemefe.github.io/mint-ui/#/swipe)

### Steps to reproduce
在最新版手机QQ内置浏览器打开下面链接：
http://elemefe.github.io/mint-ui/#/swipe
http://bangumi.bilibili.com/moe/2017/jp/mobile

视频：
http://kissovo.oss-cn-beijing.aliyuncs.com/%E6%89%8B%E6%9C%BAQQ%E8%A7%86%E9%A2%91_20171019202819.mp4

### What is Expected?
过渡动画与其他浏览器显示一致

### What is actually happening?
过渡动画显示异常

**Comment by cloudIC** [comment]
同样 ios11 QQ内置浏览器 并未发现该问题。看来定位还要更加精细点 QQ版本之类的 等待多个反馈

**Comment by u3u** [comment]
**详细信息：**
OS: iOS 11.0.3
QQ: v7.2.0.439
UA: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_3 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A432 QQ/7.2.0.439 V1_IPH_SQ_7.2.0_1_APP_A Pixel/750 Core/UIWebView NetType/WIFI QBWebViewType/1

**Comment by u3u** [comment]
微信和 Safari 都是正常的

**Comment by u3u** [comment]
妈卖批，是QQ自身的BUG。。
我刚才测试了 [Vux](https://vux.li/demos/v2/#/) 的组件，只要是带滑动过渡效果的都显示不正常
然后我回想了一下以前用的时候好像没这问题，然后我将QQ强制退出再打开后都正常了

不好意思，打扰了😅
