### ISSUE TITLE
[Bug Report] Form Components里面的field 里面 password里面单词打错了，打成v-modal了 

### ISSUE THREAD

**Issue by zzw0313** [ElemeFE/mint-ui#1151]
### Mint UI version
2.2.9

### OS/Browsers version
window10/chrome 61

### Vue version
2.5.2

### Reproduction Link
[http://mint-ui.github.io/docs/#/en2/field](http://mint-ui.github.io/docs/#/en2/field)

### Steps to reproduce
Form Components里面的field 里面 password里面单词打错了，打成v-modal了 

### What is Expected?
修改一下呗

### What is actually happening?
·

**Comment by cloudIC** [comment]
往这里提：[mint-ui-docs](https://github.com/mint-ui/docs)。这里是文档
