### ISSUE TITLE
[Feature Request] Toast组件能不能增加回调方法？

### ISSUE THREAD

**Issue by delayhsiao** [ElemeFE/mint-ui#1153]
### Existing Component
是

### Component Name
Toast

### Description
提醒完了还有其他操作，如果使用同步做法，Toast还没出来呢就做下一步了，是不是来个回调方法

**Comment by dongzhl** [comment]
Toast({ message: "操作成功", duration: 1000 });
          setTimeout(() =>something, 1500);

**Comment by delayhsiao** [comment]
@dongzhi 道理我都懂，但是就不能来个回调方法简单操作么

**Comment by yoyo837** [comment]
利用duration: 参数加 setTimeout做，Toast组件的定义本身就是这个效果
