### ISSUE TITLE
打包后样式都变大了

### ISSUE THREAD

**Issue by xiezehao** [ElemeFE/mint-ui#1160]
原本设计是这样的

![_20171107205803](https://user-images.githubusercontent.com/9320056/32495002-c6207390-c3fe-11e7-838e-2f6a42cf1ee6.png)

可到了打包后（cnpm run build）
![_20171107205757](https://user-images.githubusercontent.com/9320056/32495013-cdf17b82-c3fe-11e7-9dc9-399caa1e2519.png)
怎么办？

**Comment by cloudIC** [comment]
确认下打包配置是否有误

**Comment by xiezehao** [comment]
@cloudIC 
![default](https://user-images.githubusercontent.com/9320056/32496049-e2d0f178-c402-11e7-864c-ffd4d9b6c40d.PNG)

**Comment by xiezehao** [comment]
@cloudIC 就修改了assetsPublicPath
