### ISSUE TITLE
[Bug Report] master分支的Pick-slot默认不能选中第一项

### ISSUE THREAD

**Issue by topul** [ElemeFE/mint-ui#1169]
### Mint UI version
2.2.10

### OS/Browsers version
windows 10/chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue](https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue)

### Steps to reproduce
:class="{ 'picker-selected': itemValue === currentValue }"
其中currentValue = this.value，而在master分支中，value恒是undefined，所以默认选中永远不能生效

### What is Expected?
能够默认选中第一个或指定的选项

### What is actually happening?
无法选中第一个或指定的选项

**Comment by nailuoGG** [comment]
#1132

**Comment by cloudIC** [comment]
#1132 fixed.
