### ISSUE TITLE
css-loader不能正确加载css文件

### ISSUE THREAD

**Issue by BboyAwey** [ElemeFE/mint-ui#117]
`import mintUi from 'mint-ui'`
如上，我安装了babel-plugin-component，根据文档设置好了配置：
```
"plugins": ["transform-runtime", ["component", [
    { "libraryName": "mint-ui", "style": true }
  ]]],
```
然后加载button文件时提示
`You may need an appropriate loader to handle this file type.`
当我将button中的style.css内容全部删除后，编译正常通过不再报错，该文件中写入任意正常css代码都会报错
将该文件移动到其它文件夹，在入口文件手动引入：
`import './style.css'`
不报错
我查了一下午，没查出任何问题~~请问这是咋回事啊

**Comment by QingWei-Li** [comment]
麻烦把完整的错误日志，以及你的 webpack 配置发上来看下

**Comment by BboyAwey** [comment]
已经解决，多谢

**Comment by cactusG90** [comment]
怎么解决的？我也碰到了这个问题
