### ISSUE TITLE
[Bug Report] picker组件设置属性defaultIndex首次赋值后再次赋值无效

### ISSUE THREAD

**Issue by Chaaang** [ElemeFE/mint-ui#1173]
### Mint UI version
2.2.10

### OS/Browsers version
Mac Hight Sierra/ Chrome(already updated)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/729/](https://jsfiddle.net/pj71jkyw/729/)

### Steps to reproduce
https://jsfiddle.net/pj71jkyw/729/

### What is Expected?
the defaultIndex should change the value shown in the picker.

### What is actually happening?
the defaultIndex doesn't changed anything.

**Comment by cloudIC** [comment]
#1132 fixed
