### ISSUE TITLE
[Bug Report] import single component ，error happen when build（单独引入一个组件文件时，编译报错）

### ISSUE THREAD

**Issue by woden0415** [ElemeFE/mint-ui#1184]
### Mint UI version
2.2.11

### OS/Browsers version
window 10 / chrome  62.0.3202.94

### Vue version
2.4.4

### Reproduction Link
[https://github.com/woden0415/justForTest](https://github.com/woden0415/justForTest)

### Steps to reproduce
```
git clone https://github.com/woden0415/justForTest
cd justForTest
npm install
```
operate `npm run dev` , run normally （开发环境时，运行正常）    

operate `npm run build`, error happen （编译时报错）

### What is Expected?
like use the import way  `import { MessageBox } from 'mint-ui'`    
generate a dist folder     
像官网推荐的引入方式一样，`import { MessageBox } from 'mint-ui'`    
生成dist文件夹

### What is actually happening?
error happen in console（控制台报错）  

```
ERROR in build.js from UglifyJs
Unexpected token: operator (>) [./node_modules/mint-ui/packages/message-box/src/message-box.js:53,0][build.js:11856,32]
```

**Comment by woden0415** [comment]
![image](https://user-images.githubusercontent.com/20438542/33278734-747c274e-d3d7-11e7-8ec5-9d983332ddd0.png)
this is Screenshots

**Comment by cloudIC** [comment]
这是 webpack 自带的 uglifyjs-webpack-plugin 的 bug。（webpack 小于 v3.0.0,用的是v0.4.6版本) 你 babel-loader 配置忽略了 node_modules 文件。在压缩箭头函数的时候报错了。
3个方案：
1. 你应该用 mint-ui 下 lib 文件夹下的组件，而不是源码。
2. 如果非要用源码，需要把源码通过 webpack 预编译。
3. 不用自带的压缩插件，自己单独引入最新版本。
