### ISSUE TITLE
msgbox-title 没有居中

### ISSUE THREAD

**Issue by starsea** [ElemeFE/mint-ui#119]
没有此项 css 
text-align:center

**Comment by Leopoldthecoder** [comment]
看了一下，`text-align: center;` 写在了 `.msgbox-title` 的父元素上，可以保证 `.msgbox-title` 内容的居中。

**Comment by starsea** [comment]
这是不行的 
text-align:center  写在.msgbox-header 里 ，并不能保证子元素.msgbox-title 居中。

**Comment by Leopoldthecoder** [comment]
是，`text-align` 不影响块级元素，所以子元素 `.msgbox-title` 本身的居中是由 `padding` 来做的，而`.msgbox-title` 内部的文本会受到 `text-align` 的影响而居中。

**Comment by Leopoldthecoder** [comment]
是，`text-align` 不影响块级元素，所以子元素 `.msgbox-title` 本身的居中是由 `padding` 来做的，而 `.msgbox-title` 内部的文本会受到 `text-align` 的影响而居中。按道理 `text-align` 的确是应该写在 `.msgbox-title` 上，下个版本会改；但是目前写在 `.msgbox-header` 上也是可以满足需求的。
