### ISSUE TITLE
[Bug Report] 响应式不知道他适合不适合，因为需要面向手机电脑平板多设备

### ISSUE THREAD

**Issue by onesez** [ElemeFE/mint-ui#1194]
### Mint UI version
2.2.12

### OS/Browsers version
手机电脑平板多设备

### Vue version
2.5.9

### Reproduction Link
[https://elementui.github.io/issue-generator/#/zh-CN?repo=mint](https://elementui.github.io/issue-generator/#/zh-CN?repo=mint)

### Steps to reproduce
没有

### What is Expected?
没有

### What is actually happening?
响应式不知道他适合不适合，因为需要面向手机电脑平板多设备

**Comment by cloudIC** [comment]
主要是面向移动端的库。PC 端组件也可以用，不过不会很友好。
