### ISSUE TITLE
[Bug Report] cell-swipe 同时设置了 is-link 和滑动后弹出删除，同时触发了删除事件和跳转事件

### ISSUE THREAD

**Issue by hsiunien** [ElemeFE/mint-ui#1197]
### Mint UI version
2.2.12

### OS/Browsers version
微信最新版

### Vue version
2.5.9

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/65/](https://jsfiddle.net/mmx38qxw/65/)

### Steps to reproduce
在手机端，左划出删除，点击删除

### What is Expected?
期望点击删除按钮，不会触发界面的跳转

### What is actually happening?
同时触发了handler 和界面跳转

**Comment by cloudIC** [comment]
will be fixed in next release
