### ISSUE TITLE
loadmore 上拉刷新的问题

### ISSUE THREAD

**Issue by qiansimin88** [ElemeFE/mint-ui#120]
因为采用上拉刷新的页面大部分都是可以点击的列表 

在上拉刷新的时候   上拉手指都会停在屏幕上 一段时间  这样就很容易触发到页面上的click事件 

这样就会很尴尬 。。。

希望能不能加个  droping的双向布尔属性 告诉我这边是在上拉了  我就想办法解绑列表的click属性呢

**Comment by QingWei-Li** [comment]
我试了下在 [DEMO](http://elemefe.github.io/mint-ui/#!/pull-up) 里的上拉刷新貌似没有误触 click 的情况，能否提供的 demo?

**Comment by Leopoldthecoder** [comment]
Hi，你的项目是否使用了 fastclick？如果是用了，删掉它看看

**Comment by twoer** [comment]
后来解决了嘛？

**Comment by areyouse7en** [comment]
fastclick提供一个needsclick的样式，加了这个就可以恢复原生点击，但是在使用loadmore组件的时候，这个needclick需要加在span.mint-cell-mask上，不能加在外层a标签上。
几经测试，终于解决了这个蛋疼的问题。
```javascript
this.$nextTick(() => {
	var masks = document.getElementsByClassName('mint-cell-mask')
	for (var i = 0; i < masks.length; i++) {
		masks[i].classList.add('needsclick')
	}
})
```

**Comment by areyouse7en** [comment]
或者是在loadmore组件外层，比方叫.scroll-wrapper，添加touchstart事件，动态添加needsclick样式
```javascript
document.getElementsByClassName('scroll-wrapper')[0].addEventListener('touchstart', function(event) {
	event.target.classList.add('needsclick');
})
```
