### ISSUE TITLE
文档的无限滚动demo写错了吧

### ISSUE THREAD

**Issue by dkunlun** [ElemeFE/mint-ui#121]
Vue.directive(InfiniteScroll.name, InfiniteScroll);

**Comment by QingWei-Li** [comment]
没错啊，你可以当成插件用 `Vue.use(InfiniteScroll)` 或者当作指令自己指定名字 `Vue.directive('infinite-scroll', InfiniteScroll)`

**Comment by dkunlun** [comment]
好像要这么写才生效Vue.directive(InfiniteScroll.name, InfiniteScroll.infiniteScroll);

**Comment by QingWei-Li** [comment]
@dkunlun 

统一用 `Vue.use(InfiniteScroll)` 吧

**Comment by dkunlun** [comment]
ok 主要是昨天按那个文档写 搞了半天搞不好 这样容易误导新人

**Comment by QingWei-Li** [comment]
@dkunlun 嗯 我在改

**Comment by QingWei-Li** [comment]
http://mint-ui.github.io/docs/#!/en/infinite-scroll

**Comment by dkunlun** [comment]
ok
