### ISSUE TITLE
[Bug Report] require应为required

### ISSUE THREAD

**Issue by calledT** [ElemeFE/mint-ui#1211]
### Mint UI version
2.2.13

### OS/Browsers version
无

### Vue version
2.5.11

### Reproduction Link
[https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue#L163](https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue#L163)

### Steps to reproduce
https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue#L163

### What is Expected?
required: false

### What is actually happening?
require: false

**Comment by cloudIC** [comment]
done
