### ISSUE TITLE
关于picker组件中的slots是动态生成是，页面无法正常显示

### ISSUE THREAD

**Issue by guigui730** [ElemeFE/mint-ui#1227]
我在data()里写了slots: [
          {
            flex: 1,
            values: [],
            className: 'slot1',
            textAlign: 'center'
          }
        ]
然后我点击按钮获取它对应的值传递给slots.values后
this.slots.values = slots
  console.log(this.slots.values) //["5万", "10万", "20万", "30万", "50万", "100万", "200万", "不投保"]
，虽然传值成功了，但是页面没有显示出来。

**Comment by polliaC** [comment]
请问您解决这个问题了么
