### ISSUE TITLE
解决使用rem布局页面时loadmore无法上拉

### ISSUE THREAD

**Issue by sculiaojin** [ElemeFE/mint-ui#1247]
原因是源码中   checkBottomReached方法校验出错(rem布局可能会产出小数的高度)。可修改为
this.$el.getBoundingClientRect().bottom和this.scrollEventTarget.getBoundingClientRect().bottom转化为整数，亲测有效
checkBottomReached: function checkBottomReached() {
      if (this.scrollEventTarget === window) {
        return document.body.scrollTop + document.documentElement.clientHeight >= document.body.scrollHeight;
      } else {
        return parseInt(this.$el.getBoundingClientRect().bottom) <= parseInt(this.scrollEventTarget.getBoundingClientRect().bottom) + 1;
      }
    },

**Comment by mumofa** [comment]
感谢提示，不过我手机parseInt后 还是差一点   所以我在最后+1那里 改大了值 就可以了
