### ISSUE TITLE
[Feature Request] 能否为Datetime picker的取消添加一个回调

### ISSUE THREAD

**Issue by kiyosunsun** [ElemeFE/mint-ui#1268]
### Existing Component
是

### Component Name
Datetime picker

### Description
目前只有点击确定有回调函数，我需要在点击取消后进行某些操作，能否为取消按钮添加增加一个回调？

**Comment by thyhates** [comment]
这个是有的，只是文档里面没。` @cancel="handleUserCancel" `

**Comment by kiyosunsun** [comment]
@thyhates 有用=-=话说文档没写你怎么发现有这个的

**Comment by thyhates** [comment]
@LongYue9608 看的源码。。。

**Comment by firesh** [comment]
mint-ui文档有很大的滞后。
element做的比较好，代码和文档在一个仓库里，基本上都是同时更新。

**Comment by yujiaaoyujia** [comment]
@cancel只能设置取消按钮的回调，请问一下有人知道 点击遮罩后的关闭 怎么回调吗

**Comment by lijinke666** [comment]
@yujiaaoyujia 
```
  @visible-change="handleDateVisibleChange"
```
