### ISSUE TITLE
tab-container 在微信浏览器滑动时闪烁的问题

### ISSUE THREAD

**Issue by dragon8github** [ElemeFE/mint-ui#1316]
http://elemefe.github.io/mint-ui/#/tab-container

该插件在微信浏览器中滑动时，会出现闪烁，具体情况请开发者自行体验吧- -#

我就懒得检查源码了。对手势不太熟悉-.-

**Comment by mrTwelve12** [comment]
我也遇到同样的问题，有人知道解决方法吗

**Comment by langki** [comment]
同样的问题  滑动的初始一段距离不跟手  会闪烁一个

**Comment by lawmillion** [comment]
为什么就给关了，也不看下问题，这个同样遇到了
