### ISSUE TITLE
未支持触摸事件

### ISSUE THREAD

**Issue by BboyAwey** [ElemeFE/mint-ui#132]
经测试，button组件未支持触摸事件，由此在移动端带来的副作用有：
1.会同时激发click和touchstart事件
2.Button中使用disabled禁用按钮，无法禁用touch事件
另外，由此引出的另一个问题是当经由touch事件调起的popup事件会出现后立即消失，猜测原因是先触发了touch事件，后又触发了默认的click事件，需要手动在处理函数中preventDefault才能正常工作

针对移动端的ui组件没有针对触摸事件进行优化，可谓一大遗憾
强烈建议对移动端触摸事件的支持和优化

**Comment by BboyAwey** [comment]
sorry，补充下，经测试button是已经禁用了click事件的，但是当配合v-touch使用的时候会出现各种bug，请问是否只能和click等原生事件配合使用，而不能使用v-touch?

**Comment by QingWei-Li** [comment]
...没看懂 为什么会同时出发 click 和 touchstart。disabled 能不能阻止 touch 事件我不清楚，但是用 touch 替代 click 是不可取的，该用 click 的地方还是应该用 click 如果你要清除 300 ms 的延迟建议使用第三方库。touchstart 相当于 mousedown 也就是手指触碰到屏幕就会触发，所以 button 啥的最好还是老实用 click，再用 fastclick 之类的第三方库消除延迟

**Comment by BboyAwey** [comment]
我用的是v-touch来做的点击，当尝试绑定`v-touch:tap`事件到button组件上时，首先是按钮的active效果没有了，然后是需要在处理函数中手动`evt.preventDefault()`，才能正常弹出popup组件，否则popup组件会闪一下就消失了，具体原因我不是很明确

**Comment by QingWei-Li** [comment]
@BboyAwey 可以给一个 demo 么

**Comment by Leopoldthecoder** [comment]
> 首先是按钮的active效果没有了

从[这里](https://github.com/ElemeFE/mint-ui/issues/133)给出的例子来看，不调用 `evt.preventDefault()` 时可以正常触发 button 的 active 效果；而调用 `evt.preventDefault()` 的话，本身就不会触发原生 button 元素的 active，所以这里应该是符合预期的。

> popup组件会闪一下就消失了

已经在上述 issue 中解决。
