### ISSUE TITLE
多个popup组件间的modal相互影响

### ISSUE THREAD

**Issue by BboyAwey** [ElemeFE/mint-ui#133]
当前页面存在一个popup position="bottom" 组件，然后我使用另一个popup弹出sale-schedule-detail：
`<x-popup :visible.sync="detailShow" position="right" class="detail-layer">
    <sale-schedule-detail v-on:detail-page-dismiss="toggleDetailPage" :detail-id="currentDetailId"></sale-schedule-detail>
  </x-popup>`
sale-schedule-detail中引用的operation-list
`<operation-list
        size="large"
        type="primary"
        operation-name="审批"
        :operation-list="operationList"
        v-on:operate="operate">
      </operation-list>`
operation-list中又引用了另一个popup position="bottom"
```
<x-popup :visible.sync="operationListVisible" position="bottom" class="auth-operation-list">
      <x-button
        class="button-list"
        v-for="operation in operationList"
        :type="operation.type"
        size="large"
        @click="operate($event, operation.name)">
        {{ operation.text }}
      </x-button>
</x-popup>
```
这时，当我从sale-schedule-detail，popup right弹出operation-list，然后点击按钮弹出另一个popup bottom时，再点击popup bottom的modal层，popup消失但modal层仍旧留在页面上，无法继续操作

猜测可能是由于popup组件未能针对同一个页面引用多个popup的情况进行考虑或者未考虑全面

**Comment by Leopoldthecoder** [comment]
@BboyAwey 如果方便的话，请提供与业务逻辑无关且能重现问题的最小量代码。我大概理解你的问题是：打开一个 popup => 点击这个 popup 弹出另一个 popup => 关闭第二个 popup => modal 仍然存在，是这样吗？我这里试了一下，没有重现。

**Comment by BboyAwey** [comment]
好的，我抽空将提的两个issue给出demo，不过得稍晚些时候

**Comment by Leopoldthecoder** [comment]
好的，多谢

**Comment by BboyAwey** [comment]
我把demo放到github上了：https://github.com/BboyAwey/mint-ui-bug-demo
你拉下来，npm install 完再npm run dev，然后打开app.html即可看到效果

**Comment by Leopoldthecoder** [comment]
> 无preventDefault无法正常唤起popup

当不 preventDefault 事件时，流程为：手指点击 button => 触发 touchstart 事件 => 唤起相应 popup => modal 层出现（此时与手指接触的是 modal） => 手指离开屏幕 => 触发 modal 上的 click 事件 => popup 被关闭。现在我做了处理，modal 刚出现的 300ms 内不会监听 click 事件。升级 mint-ui@0.2.5 即可解决这个问题。

> 嵌套的popup会出现modal层干扰

应避免 popup 中嵌套 popup，因为这样会导致 popup 和相应的 modal 不在同一个 stacking context 上，从而造成 z-index 属性混乱。需要将
```html
  <mt-popup position="right" class="right-popup" :visible.sync="popupVisibility">
    <h3>嵌套popup的 modal 干扰BUG</h3>
    <p>嵌套的popup会出现modal层干扰</p>
    <mt-button size="large" @touchstart="tapHandler3($event)">嵌套的第三个popup</mt-button>
    <mt-popup position="bottom" :visible.sync="popupVisibility2">
        <p>嵌套的第三个popup</p>
        <p>嵌套的第三个popup</p>
        <p>嵌套的第三个popup</p>
    </mt-popup>
    <h3>返回</h3>
    <mt-button size="large" @touchstart="tapHandler2($event)">返回</mt-button>
  </mt-popup>
```
改为
```html
  <mt-popup position="right" class="right-popup" :visible.sync="popupVisibility">
    <h3>嵌套popup的 modal 干扰BUG</h3>
    <p>嵌套的popup会出现modal层干扰</p>
    <mt-button size="large" @touchstart="tapHandler3($event)">嵌套的第三个popup</mt-button>
    <h3>返回</h3>
    <mt-button size="large" @touchstart="tapHandler2($event)">返回</mt-button>
  </mt-popup>
  <mt-popup position="bottom" :visible.sync="popupVisibility2">
    <p>嵌套的第三个popup</p>
    <p>嵌套的第三个popup</p>
    <p>嵌套的第三个popup</p>
  </mt-popup>
```

**Comment by BboyAwey** [comment]
好的 辛苦啦~
