### ISSUE TITLE
lazyload 失效

### ISSUE THREAD

**Issue by simonmysun** [ElemeFE/mint-ui#134]
## 环境
* Google Chrome 52.0.2743.82 (Official Build) (64-bit) on 4.6.4-1-ARCH, Yoga 3 Pro
* Google Chrome 52.0.2743.91 (Official Build) (32-bit) on Android 5.1.1, Nexus 6

## 页面
http://elemefe.github.io/mint-ui/

## 复现方式
1. 载入 lazyload 示例
1. 向下滚动等待部分图片加载
1. 之后返回(window.history.back())
1. 重新进入 lazyload 示例

## 正确结果
图片正常 lazyload

## 实际结果
第一次进入 lazyload 示例时未出现在屏幕上但由滚动触发加载的图片无法在第二次进入 lazyload 示例时正常加载

## 原因猜测
所依赖的组件 lazyload 未完全释放和初始化: 
https://github.com/ElemeFE/mint-ui/blob/master/packages/lazyload/src/lazyload.js#L1
https://github.com/hilongjw/vue-lazyload/blob/master/src/vue-lazyload.es5.js#L19

**Comment by Leopoldthecoder** [comment]
@simonmysun fixed in 0.2.4
