### ISSUE TITLE
Field 加入readonly还是能编辑

### ISSUE THREAD

**Issue by HBLong** [ElemeFE/mint-ui#135]
<mt-field label="帐号" :readonly="true" placeholder="请输入账号"></mt-field>
<mt-field label="帐号" readonly="true" placeholder="请输入账号"></mt-field>

**Comment by QingWei-Li** [comment]
确保升级到最新版本，如果还是不行麻烦提供下代码

**Comment by Binaryify** [comment]
我也是一样,已经是最新版本了

**Comment by QingWei-Li** [comment]
@Binaryify 
请问具体是在哪个浏览器里，我们测试过的几款设备访问微信和自带浏览器都没问题。麻烦提供下详细信息。

**Comment by Binaryify** [comment]
chrome pc端
 52.0.2743.116 m
<mt-field label="搜索" placeholder="请输入关键词" readonly=true></mt-field>
mint-ui "version": "0.1.25"

**Comment by Binaryify** [comment]
```
<mt-field label="搜索" placeholder="请输入关键词" readonly=true></mt-field>
```
这样还是可以编辑

**Comment by QingWei-Li** [comment]
@Binaryify 这个在 0.2.0 版本已经更新，麻烦升级到最新版本

**Comment by Binaryify** [comment]
好的,谢谢
