### ISSUE TITLE
按文档快速上手启动项目时报错：no PostCss config found in E:/...

### ISSUE THREAD

**Issue by Kuichen** [ElemeFE/mint-ui#1356]
Hi，我初次尝试mint，按照文档一步步配置好环境，输入npm run dev启动项目时报如下错误，通过npm按照postcss后还是一样的错误。开发环境是Windows7，npm 3.10.10, node v6.10.1
请问是什么原因呢？ 

 WAIT  Compiling...                                                     11:42:04

 10% building modules 0/1 modules 1 active ...de_modules\mint-ui\lib\cell\style.
 10% building modules 0/2 modules 2 active ..._modules\mint-ui\lib\button\style.
 10% building modules 0/3 modules 3 active ...de_modules\mint-ui\lib\font\style.
 11% building modules 1/3 modules 2 active ...de_modules\mint-ui\lib\font\style.
 12% building modules 2/3 modules 1 active ...de_modules\mint-ui\lib\font\style.
94% asset optimization

 ERROR  Failed to compile with 3 errors                                 11:42:05

 error  in ../node_modules/mint-ui/lib/button/style.css

Module build failed: Error: No PostCSS Config found in: E:\mint\node_modules\min
t-ui\lib\button
    at Error (native)
    at E:\mint\cheng\node_modules\postcss-load-config\index.js:51:26

 @ ../node_modules/mint-ui/lib/button/style.css 4:14-168 13:3-17:5 14:22-176
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-serve
r ./src/main.js

 error  in ../node_modules/mint-ui/lib/cell/style.css

Module build failed: Error: No PostCSS Config found in: E:\mint\node_modules\min
t-ui\lib\cell
    at Error (native)

**Comment by huanghui8030** [comment]
遇到同样的问题，不知道是否解决了。
