### ISSUE TITLE
field不能获取到值

### ISSUE THREAD

**Issue by songlipeng2003** [ElemeFE/mint-ui#136]
`<mt-field label="邮箱" placeholder="请输入邮箱" type="email" :value="username"></mt-field>`

import { Header, Field, Button, MessageBox } from 'mint-ui'

import Account from '../resources/Account'

export default {
  components: {
    'mt-header': Header,
    'mt-field': Field,
    'mt-button': Button
  },
  data () {
    return {
      username: '',
      password: ''
    }
  },
  methods: {
    login: function (event) {
      Account.login({
        username: this.username,
        password: this.password
      }).then((response) => {
        let data = response.data
        if (data.code === 0) {

```
    } else {
      MessageBox.alert(data.msg)
    }
  })
}
```

  }
}

获取到的username的值一直为空

**Comment by QingWei-Li** [comment]
:value.sync

**Comment by songlipeng2003** [comment]
谢谢。

**Comment by purely-smile** [comment]
2.0.2 版本，field组件使用:value.sync也获取不到input的数值
`<mt-field :value.sync="nick" label="用户名" placeholder="请输入用户名/手机号"></mt-field>`

**Comment by QingWei-Li** [comment]
@purely-smile 麻烦你好好看看文档 2.0 哪来的 sync

**Comment by purely-smile** [comment]
一开始使用的不带sync。没有作用，然后看到这个issues。也是获取不到。
`<mt-field :value="nick" label="用户名" placeholder="请输入用户名/手机号"></mt-field>`

**Comment by purely-smile** [comment]
@QingWei-Li 知道原因了，文档写错了。使用v-model绑定才行。不能用value

**Comment by Giina** [comment]
建议修改一下文档

**Comment by Jmingzi** [comment]
建议修改下文档，使用v-model

**Comment by galenyuan** [comment]
已改正

**Comment by kinglo** [comment]
mt-field  type为password时 v-model也取不到值
