### ISSUE TITLE
在ios内，上下拉滚动效果不是很好

### ISSUE THREAD

**Issue by huangxinpeng** [ElemeFE/mint-ui#1366]
最近项目比较急，基本上完成了90%  测试验收时说在ios下滚动不是很理想，在phoneX上是出现 卡顿情况 ，怎么解决在线等急

**Comment by huangxinpeng** [comment]
最近项目比较急，基本上完成了90% 测试验收时说在ios下滚动不是很理想，在phoneX上是出现 卡顿情况 ，怎么解决在线等急

**Comment by Jam1zhu** [comment]
解决了吗
