### ISSUE TITLE
checklist 可点击区域不正确

### ISSUE THREAD

**Issue by yyjazsf** [ElemeFE/mint-ui#137]
### Mint UI version
0.2.1
### Device model

Wechat webview
### Reproduction Link

http://elemefe.github.io/mint-ui/#!/checklist

### What is Expected?
只有radio和文字可点，或者整条垂直方向较大范围可点

### What is actually happening?
以第一组为例，可点击区域很奇葩。右边空白区域中间不能点，偏上放能点
其他组也有类似问题

**Comment by QingWei-Li** [comment]
请问是手机型号是什么，我的 iOS 在微信里表现是正常的。可点击区域我设置的是整条 Cell

**Comment by yyjazsf** [comment]
我错了，之前就在chrome 模拟的不行，以为手机里面也不行- -
