### ISSUE TITLE
[Bug Report] Datetime picker插件 日期选择最后一天，小时不可以选择。

### ISSUE THREAD

**Issue by ahakeem** [ElemeFE/mint-ui#1395]
### Mint UI version
2.2.13

### OS/Browsers version
window/chrome

### Vue version
2.5.17-beta.0

### Reproduction Link
[http://mint-ui.github.io/docs/#/zh-cn/datetime-picker](http://mint-ui.github.io/docs/#/zh-cn/datetime-picker)

### Steps to reproduce
官网示例：
第一个Datetime picker例子。
1、自定义类型有年月日小时。
2、选择终止日期的最后一天，小时不可以选择。都是 0时0分。

### What is Expected?
最后一天的小时，可以选择。

### What is actually happening?
最后一天的小时，不可以选择。

**Comment by JerryYuanJ** [comment]
这个endDate应该是最后一天的开始，不包含最后一天。设计如此，不是bug。

**Comment by ahakeem** [comment]
这应该不是bug,我后来改成 最大值设置23:23 就没用问题了。
