### ISSUE TITLE
[Feature Request]MessageBox组件显示多行文本

### ISSUE THREAD

**Issue by gzlock** [ElemeFE/mint-ui#1397]
### Existing Component
是

### Component Name
Alert

### Description
尝试过

```html
“文本<br>文本”

“文本\n文本”

“文本\r\n文本”

“文本\n\r文本”
```
 都没有换行效果

Toast不支持多行文本可以理解，毕竟Toast会自动隐藏

但是希望Alert可以支持多行文本，谢谢。

**Comment by NemoPhoenix** [comment]
可以显示多行啊<br>和\n\r这些都可以，连P和div都可以
