### ISSUE TITLE
[Bug Report] TabContainer组件swipeable开启滑动怪异问题

### ISSUE THREAD

**Issue by alwaysRemember** [ElemeFE/mint-ui#1410]
### Mint UI version
2.2.9

### OS/Browsers version
android/ios都会出现

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/?message=未上线望见谅](https://jsfiddle.net/mmx38qxw/?message=未上线望见谅)

### Steps to reproduce
当在使用TabContainer的时候把swipeable开启，滑动会很怪异，哪怕是上下滑动都有一定的几率触发切换。当在一个列表页数据多，一个列表页数据少的时候尤其明显，会造成切换的同时上下滑动。。

### What is Expected?
swipeable开启的时候希望限制下用户操作，当Y轴滑动距离大于X轴的时候，不进行切换。

### What is actually happening?
swipeable开启的时候滑动怪异，哪怕上下滑动只要距离过了一半都会切换，会造成切换的同时上下滑动页面。用户体验有点差。。

**Comment by zhangluhu** [comment]
遇到同样的问题，官方是否能给个解决办法，我修改组件，一点反应也没有。求解

**Comment by zhangluhu** [comment]
> ### Mint UI version
> 2.2.9
> 
> ### OS/Browsers version
> android/ios都会出现
> 
> ### Vue version
> 2.5.17-beta.0
> 
> ### Reproduction Link
> [https://jsfiddle.net/mmx38qxw/?message=未上线望见谅](https://jsfiddle.net/mmx38qxw/?message=%E6%9C%AA%E4%B8%8A%E7%BA%BF%E6%9C%9B%E8%A7%81%E8%B0%85)
> 
> ### Steps to reproduce
> 当在使用TabContainer的时候把swipeable开启，滑动会很怪异，哪怕是上下滑动都有一定的几率触发切换。当在一个列表页数据多，一个列表页数据少的时候尤其明显，会造成切换的同时上下滑动。。
> 
> ### What is Expected?
> swipeable开启的时候希望限制下用户操作，当Y轴滑动距离大于X轴的时候，不进行切换。
> 
> ### What is actually happening?
> swipeable开启的时候滑动怪异，哪怕上下滑动只要距离过了一半都会切换，会造成切换的同时上下滑动页面。用户体验有点差。。

亲  你有解决方法了么？

**Comment by alwaysRemember** [comment]
@zhangluhu 没有。。这个官方也没给出解决方法，这个UI也好久没维护了，放弃吧。改用其他的ui

**Comment by ghost** [comment]
@alwaysRemember 放弃。。。

**Comment by shipMatserJack** [comment]
大家放弃吧。。。
