### ISSUE TITLE
[Bug Report] 官网挂了吧，都上不去

### ISSUE THREAD

**Issue by 672064406zerui** [ElemeFE/mint-ui#1435]
### Mint UI version
2.2.13

### OS/Browsers version
浏览器

### Vue version
2.5.17

### Reproduction Link
[http://mint-ui.github.io/](http://mint-ui.github.io/)

### Steps to reproduce
2112

### What is Expected?
好使

### What is actually happening?
不好使

**Comment by DevilTears** [comment]
可以打开的哇

**Comment by 672064406zerui** [comment]
http://mint-ui.github.io/#!/en   这个 能开？？

**Comment by ouhuiju** [comment]
你好，打不开
