### ISSUE TITLE
loadmore无法下拉。

### ISSUE THREAD

**Issue by galenjiang** [ElemeFE/mint-ui#146]
安卓微信blink下  Loadmore 多页刷新操作时，在某一个尺寸下，无法触发上拉刷新。

现在的解决方式，暂时在loadmore外层底部增加1px的block元素就可以进行拉动刷新。

**Comment by galenjiang** [comment]
### 重现
在示例demo中，列表行高由50px改成49.1px，上拉就失效了。

**Comment by QingWei-Li** [comment]
Fixed https://github.com/ElemeFE/mint-ui/pull/148
