### ISSUE TITLE
[Bug Report] 多个MessageBox，后面异步调用的弹框不执行

### ISSUE THREAD

**Issue by Mr-xue** [ElemeFE/mint-ui#1460]
### Mint UI version
2.2.13

### OS/Browsers version
Win7 / chrome 67

### Vue version
2.5.17

### Reproduction Link
[http://jsfiddle.net/eywraw8t/331444/](http://jsfiddle.net/eywraw8t/331444/)

### Steps to reproduce
点击实例地址里面的 点击按钮就可以复现。

### What is Expected?
希望多个弹窗都能依序弹出，而不是只有第一个弹出，后面的都被阻挡了

### What is actually happening?
实际场景中是在项目的根路由里面有一个判断条件触发一个弹窗，然后进入某个子路由中在一个接口的回调中也有一个条件出发一个弹窗。
当两个弹窗的条件都达成时，只有第一个弹窗显示了，第二个被阻挡了，第一个弹窗关掉，第二个也没有显示出来

**Comment by lei-mu** [comment]
我也遇到了，赶紧解决一下啊

**Comment by BigA666** [comment]
遇到+1，怎么解决

**Comment by BigA666** [comment]
而且这样操作点击其他地方会弹出上次连续要弹出的东西

**Comment by BigA666** [comment]
先代MessageBox.close(false);码强制关闭再进行弹出, 并没有完全解决，也没有达到想要的效果，但只能这样了
