### ISSUE TITLE
建议: 引入全局样式的建议

### ISSUE THREAD

**Issue by galenjiang** [ElemeFE/mint-ui#147]
在用构建工具时，假如不用webpack，只用sass进行编译，引入全局  ```import 'mint-ui/lib/button/style.css';```样式时，会编译成css的import外链格式，build后无法引用module里面的静态文件。建议style.css改成scss格式，或者额外开发一个scss文件来提供构建。

**Comment by furybean** [comment]
webpack 支持指定某个文件使用哪个 loader，应该可以这么做 import 'css!mint-ui/lib/button/style.css'

**Comment by galenjiang** [comment]
我指的是有一些项目不用webpack来构建，假如需要引用的话，只能单独拿出这个文件来更改了。
