### ISSUE TITLE
如何像vux一样直接源码引用，便于修改。

### ISSUE THREAD

**Issue by flybbjcs70** [ElemeFE/mint-ui#150]
rt

**Comment by QingWei-Li** [comment]
NPM 上发布的版本有提供源代码的，在 src 目录下。CSS 的话需要用 https://github.com/ElemeFE/postcss-salad 处理，然后 babel 要 es2015 就可以了。

**Comment by flybbjcs70** [comment]
为什么没有packages文件夹

**Comment by QingWei-Li** [comment]
.... 哦对 下一版改
