### ISSUE TITLE
获取模块错误

### ISSUE THREAD

**Issue by zhanfenghai** [ElemeFE/mint-ui#151]
### What is actually happening?
错误日志

ERROR in ./~/mint-ui/lib/toast/style.css
Module parse failed: E:\V2EX-mobile\node_modules\mint-ui\lib\toast\style.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by QingWei-Li** [comment]
你的 webpack 没有配置 css loader

**Comment by zhanfenghai** [comment]
Thank you,it's resolved 


---------------------- 
Tel:15270015944
QQ:410998447
E-mail :zhanfenghai1014@163.com
----------------------
在2016年08月24日 21:48，cinwell.li 写道:

Closed #151.
