### ISSUE TITLE
[Bug Report] tabbar组件切换报错 Uncaught TypeError: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by wxhon** [ElemeFE/mint-ui#1518]
### Mint UI version
2.2.13

### OS/Browsers version
Google Chrome版本 70.0.3538.110（正式版本） （64 位）

### Vue version
2.5.2

### Reproduction Link
[https://elemefe.github.io/mint-ui/#/tabbar](https://elemefe.github.io/mint-ui/#/tabbar)

### Steps to reproduce
项目开发环境：mint-ui v2.2.13
使用vue 官方模板 webpack standard
使用mint-ui组件tabbar，按照实例给出的使用方式
![image](https://user-images.githubusercontent.com/20228309/49559188-e9c89b80-f948-11e8-8df1-322355d60f51.png)

官网例子就报错了。Uncaught TypeError: Cannot read property 'match' of null

### What is Expected?
报错解决一下

### What is actually happening?
还未解决

**Comment by sollrei** [comment]
感觉好像是a标签（比如直接写<a>test</a>）没写href的点击都有这种报错?
