### ISSUE TITLE
用Tabbar做底边栏，在iOS上滚动的时候，fixed的tabbar闪现，怎么处理？

### ISSUE THREAD

**Issue by dingyiming** [ElemeFE/mint-ui#153]
### Mint UI version

*  "mint-ui": "^0.2.6",

### Device model

iOS 9 微信

### What is Expected?

* 希望在iOS上用上惯性 滑动和弹性效果，并且底部和顶部，都能固定住不动，中间容器滚动。

### What is actually happening?

*  http://mint-ui.github.io/docs/#!/zh-cn/tabbar

*  在body加上  overflow: scroll;-webkit-overflow-scrolling: touch;后整体滚动效果出来了，但是用的tabbar fixed在底部滚动的时候会出现闪现的情况，请问我该怎么处理？

* 谢谢

**Comment by QingWei-Li** [comment]
在 iOS 上用 fixed 定位会用问题吧？
或许你可以弄成三段式的，中间的容器滚动，上下用 position: absolute

**Comment by QingWei-Li** [comment]
我的做法：
- Demo 里面我是分成三部分，顶部和底部 absolute 定位，中间高度 100% 可滚动，然后 body 设置 `-webkit-overflow-scrolling: touch`

- 可以不用 `-webkit-overflow-scrolling: touch` 直接顶部底部 fixed，body 高度 100%

**Comment by theseawolves** [comment]
我也遇到类似问题了。  @QingWei-Li Demo具体是那个呢。按照例子，不加 -webkit-overflow-scrolling: touch，IOS卡顿，不流畅。加上后，IOS固定不了。

**Comment by suncn** [comment]
我很想知道怎么解决 谢谢啦
