### ISSUE TITLE
index-list  为什么不支持异步数据

### ISSUE THREAD

**Issue by angusjiang** [ElemeFE/mint-ui#155]
index-list  为什么不支持异步数据，异步获取的数据index-list无法使用，报错
 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

**Comment by Leopoldthecoder** [comment]
#154 我先关掉了，看起来是一个问题。待会处理。

**Comment by Leopoldthecoder** [comment]
fixed in #156
