### ISSUE TITLE
messagebox重复触发上次的弹框内容

### ISSUE THREAD

**Issue by johnshere** [ElemeFE/mint-ui#1555]
问题重复的纪律非常的大，我再次使用messagebox的时候，有时弹出的是上一次弹框的内容和形式。比如我先上次使用prompt，现在使用alert，但是展示的确实上次的内容和prompt形式。
只有当下次弹框时，才会弹出我刚刚想弹出的内容

**Comment by chenjinhao** [comment]
@johnshere 请问你解决了这个问题吗？实在不行只能换UI框架了。

**Comment by freecodemakerxu** [comment]
messagebox 这个有点不受控制，跳来跳去，在部分机型上面(比如苹果6s上面)。

**Comment by johnshere** [comment]
> @johnshere 请问你解决了这个问题吗？实在不行只能换UI框架了。

还没有解决
