### ISSUE TITLE
cell 组件在ios7.1.2 safari 样式错乱

### ISSUE THREAD

**Issue by liiujinfu** [ElemeFE/mint-ui#161]
### Reproduction Link
cell 组件在ios7.1.2 safari 样式错乱

### What is Expected?
希望和ios9 样式一致
### What is actually happening?

**Comment by QingWei-Li** [comment]
没设备 截个图

**Comment by liiujinfu** [comment]
![test](https://cloud.githubusercontent.com/assets/19798768/18244075/c3d95396-7390-11e6-8102-711a2affe0ed.png)

**Comment by QingWei-Li** [comment]
没找到原因，查了下 caniuse, flexbox 是支持的...

**Comment by galenyuan** [comment]
@QingWei-Li 直接把父级的display:flex点掉可以直接在Chrome上重现的，应该是因为label不支持-webkit-box-flex，换个标签就可以了，好坑啊
