### ISSUE TITLE
loadmore组件初始化

### ISSUE THREAD

**Issue by ittce** [ElemeFE/mint-ui#164]
初始化时 fillauto方法调用callback时，如果数据不能填充完毕页面，会继续调用 ，可使用props， bottom-all-load判断

**Comment by Leopoldthecoder** [comment]
有道理，我改一下。

**Comment by Leopoldthecoder** [comment]
我看了一下，在 `onBottomLoaded` 中已经对 `bottomAllLoaded` 进行了判断，如果都加载完毕就不会再次调用 `fillContainer`
