### ISSUE TITLE
<mt-field>好像不能通过attr来设置原生属性

### ISSUE THREAD

**Issue by tzhgkm** [ElemeFE/mint-ui#167]
<mt-field>好像不能通过attr来设置原生属性：我想限制input和textarea的输入字数，但是加上 attr="{ maxlength: 10 }"并没有效果。

**Comment by QingWei-Li** [comment]
确定加的是 `:attr="{ maxlength: 10 }"`？有冒号么

**Comment by tzhgkm** [comment]
<mt-field label="用户名" placeholder="请输入用户名" :attr="{ maxlength: 10 }"></mt-field>
加冒号和不加冒号，我都有试过，确实没有效果诶。您那边是可以的？

**Comment by QingWei-Li** [comment]
http://mint-ui.github.io/docs/#!/en/field

第一个输入用户名的 field 设置的就是  maxLength = 10 https://github.com/ElemeFE/mint-ui/blob/master/example/pages/field.vue#L5

**Comment by tzhgkm** [comment]
恩，谢啦。我再查查看为啥我这边会没有效果

**Comment by tzhgkm** [comment]
是我用的版本太旧了，是0.1.3的(三四个月前的版本吧)。<mt-field>还没有attr的属性

**Comment by vitalitygithub** [comment]
set native attributes. e.g. :attr="{ maxlength: 10 }"    冒号也是表达式的一部分  :attr="{ maxlength: 10 }"   希望文档能改进这段话，至少在后面注明

**Comment by dmlzj** [comment]
type="number"是没有maxlength属性的
