### ISSUE TITLE
我们的开发环境是 fis 的，所以无法移植啊，能不能根据非 webpack 环境做一下适配

### ISSUE THREAD

**Issue by luanwulin** [ElemeFE/mint-ui#169]
开发环境是 fis。用 seajs 异步加载模块，无法加载 node_modules 里面的组件，能不能适配呢？

**Comment by QingWei-Li** [comment]
推荐直接引入所有组件的文件，不然不搭配 webpack 太麻烦，readme 提供了 cdn
