### ISSUE TITLE
Index List样式错乱

### ISSUE THREAD

**Issue by w404** [ElemeFE/mint-ui#171]
[
![qq 20160910180609](https://cloud.githubusercontent.com/assets/17056943/18409725/80a3d656-7781-11e6-9f84-b1c2e65a1542.png)
](url)[
![qq 20160910180835](https://cloud.githubusercontent.com/assets/17056943/18409728/a8f64544-7781-11e6-9aa0-87ad0ad5322c.png)
](url)

**Comment by Leopoldthecoder** [comment]
fixed in #172
