### ISSUE TITLE
css problem for swiper

### ISSUE THREAD

**Issue by bsxz0604** [ElemeFE/mint-ui#177]
### Mint UI version
the lastest version
### Device model
webpage
### What is Expected?
使用swiper组件时，用ajax请求头数据后，无法获取图片高度，必须给一个固定值

### What is actually happening?

**Comment by Leopoldthecoder** [comment]
Swipe 组件本身不会去获取图片的高度，如果要根据图片的高度调整 Swipe 的高度的话，需要自己处理，比如获取图片高度后给 Swipe 加一条 `v-on:style="{ height: imgHeight }" `
