### ISSUE TITLE
可以提交下 lib 里面压缩的代码的原始版本么。希望研究下源码

### ISSUE THREAD

**Issue by luanwulin** [ElemeFE/mint-ui#178]
rt，可以看看原始代码么?

**Comment by QingWei-Li** [comment]
目前的版本是提供源代码的，在 `packages/` 里

https://unpkg.com/mint-ui@0.2.8/packages/

**Comment by luanwulin** [comment]
比如说我准备看看 toast 的代码，在 toast/lib/index.js 是压缩版本的。

**Comment by luanwulin** [comment]
带队

**Comment by luanwulin** [comment]
比如说我想看看 toast 的代码。toast/lib/index.js 里面的是压缩版本的。

**Comment by QingWei-Li** [comment]
哦 这个是因为当初直接把组件都单独拆分成独立的项目，所以你应该找 node_modules 里的 vue-toast-mobile
后面会将它们都移进来，统一管理
