### ISSUE TITLE
请教个组件特色问题

### ISSUE THREAD

**Issue by luxueyan** [ElemeFE/mint-ui#179]
我注意到组件中的样式使用了一些 第一次见的 @component @component-namespace 等牛逼的使用方法，这个是使用了什么预处理loader吗？ 求教！谢谢

**Comment by Leopoldthecoder** [comment]
参考 https://github.com/kezzbracey/postcss-bem

**Comment by QingWei-Li** [comment]
然后是整合到 https://github.com/ElemeFE/postcss-salad

**Comment by luxueyan** [comment]
学习了，谢谢二位！

**Comment by swxy** [comment]
像webstorm、vscode怎么支持这种语法检测？
