### ISSUE TITLE
有没有交流QQ群什么的?好多看了文档都不会用啊?里面的example也跑不起来

### ISSUE THREAD

**Issue by issmile** [ElemeFE/mint-ui#181]
### Mint UI version
如题,有没有交流QQ群什么的?好多看了文档都不会用啊?里面的example也跑不起来
### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/20268011/18505397/9d23aeb2-7a99-11e6-9ee2-2ee99e24a17a.png)
```
E:\vue\mint-ui>npm run dev

> mint-ui@0.2.8 dev E:\vue\mint-ui
> npm run build-entry && cooking watch -c scripts/cooking.demo.js


> mint-ui@0.2.8 build-entry E:\vue\mint-ui
> node bin/build-entry

[build entry] DONE: E:\vue\mint-ui\src\index.js

[cooking] - 插件加载成功: vue
[cooking] - 插件加载成功: lint
[cooking] - 插件加载成功: saladcss

[cooking] - server 启动中...
[cooking] - Listening at http://192.168.70.1:8789
webpack: wait until bundle finished: /
Child scripts/cooking.demo.js:

    ERROR in ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue
-loader/lib/selector.js?type=script&index=0!./packages/picker/src/picker-slot.vue
    Module not found: Error: Cannot resolve module 'raf.js' in E:\vue\mint-ui\packages\picker\src

     @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loade
r/lib/selector.js?type=script&index=0!./packages/picker/src/picker-slot.vue 25:0-17
    Child html-webpack-plugin for "index.html":

webpack: bundle is now VALID.
```

**Comment by QingWei-Li** [comment]
要先执行下面这个，安装依赖。我已经加到 scripts 里了
```shell
npm install && ./node_modules/.bin/lerna bootstrap
```

你所说的文档不会用是指哪些

**Comment by manwuyu** [comment]
我本地 也是跑不起来

**Comment by QingWei-Li** [comment]
`raf.js` 依赖没有安装，理论上执行 `npm run dev` 会帮你安装每个组件里面的依赖，如果不行的话就执行下下面这个
```shell
npm install && ./node_modules/.bin/lerna bootstrap
```

**Comment by manwuyu** [comment]
执行npm install && ./node_modules/.bin/lerna bootstrap
显示
![image](https://cloud.githubusercontent.com/assets/6800546/18824274/38c9c66e-83f3-11e6-8136-ce0085102968.png)

**Comment by QingWei-Li** [comment]
那你看看 node_modules 里的 bin 目录是存在哪里的，windows 上我不清楚，反正调用 lerna bootstrap  就对了

**Comment by manwuyu** [comment]
这样样的 npm install 是安装什么什么， npm instal && ./ 后面的语法 和 前面是并列的，也就是 ./ 也是 执行了 这个语言，并没有这个方式 所以报错  ，请问 这句话的原意是什么  是打开某个文件夹  执行 npm install么

**Comment by QingWei-Li** [comment]
哦那你试试，目的只是调用当前目录下 node_modules 里的 lerna 命令行工具
```shell
npm install && node_modules/.bin/lerna bootstrap
```

**Comment by manwuyu** [comment]
你好  执行了lerna bootstrap，但是有乱码报错
![image](https://cloud.githubusercontent.com/assets/6800546/18824457/d9bd95b8-83f4-11e6-9909-edcbd37fcda7.png)

**Comment by QingWei-Li** [comment]
你不能到这个路径下执行 😂，只能在项目根目录下执行这个，如果还是不行那么你全局安装一个 lerna 也可以
```shell
npm i lerna -g
lerna bootstrap
```

**Comment by manwuyu** [comment]
亲 一样的 乱码报错 噢

**Comment by QingWei-Li** [comment]
那你人工到 `packages/picker/` 目录下执行 `npm install` 安装组件依赖吧 😂

windows 已经测试过是没问题的 😂😂

**Comment by manwuyu** [comment]
一样的 乱码报错，如上图，因为我的是w10，其中dev dist clean 无法执行 ，deploy是可以执行的，
然后 再下面是 linux 执行npm run dev的报错图
![image](https://cloud.githubusercontent.com/assets/6800546/18824861/cf940998-83f7-11e6-8233-42498600c7b8.png)

**Comment by QingWei-Li** [comment]
linux 上的问题，感觉是 npm 版本太老。全局安装 lerna 应该是可行的。如果还是不行，到 `packages/picker/` 里执行 `npm install`，但是不晓得还有哪些组件有单独的依赖

**Comment by manwuyu** [comment]
linux  都能执行 没有报错  但是 lib 文件夹下 没有文件。。。。

**Comment by QingWei-Li** [comment]
执行 `dist` 才是打包项目。如果执行后没文件那么有可能是没写入权限？
```shell
npm run dist
```

**Comment by manwuyu** [comment]
@QingWei-Li 
还是缺少一个文件 
![image](https://cloud.githubusercontent.com/assets/6800546/18825885/11b81166-83fd-11e6-8e02-93eed50fad50.png)

**Comment by QingWei-Li** [comment]
哦 那这就是我的锅了。。稍等

**Comment by QingWei-Li** [comment]
@maranran done, 拉下最新代码

**Comment by manwuyu** [comment]
@QingWei-Li 
linux 成功！ 实在太不容易了~~~

**Comment by manwuyu** [comment]
生成了min-ui-common.js 是干嘛的 有啥用
能弱弱的说一句 自己生成的代码  一堆报错吗。。。。
![image](https://cloud.githubusercontent.com/assets/6800546/18826377/b1edbe04-83ff-11e6-9879-eaed962c9536.png)

**Comment by QingWei-Li** [comment]
还是去 Gitter 里聊吧，issue 这么玩不好 https://gitter.im/ElemeFE/mint-ui
