### ISSUE TITLE
datetime-picker 如何使用才能实时刷新数据？

### ISSUE THREAD

**Issue by manwuyu** [ElemeFE/mint-ui#186]
^0.2.7
 Device model    all 
点击其他地方修改了 开始时间 和 结束时间
时间控件的数据没有发生改变，
change的时候 时间控件才会发生变化

诡异，成功了一次，现在 没反应

**Comment by manwuyu** [comment]
非常感谢！已经解决问题

**Comment by manwuyu** [comment]
@Leopoldthecoder
 你好，我发现还是存在问题
流程是：第一次的change后的时间是一个不止一天的区间的话，展示的效果是乱的，
如果区间 只有一天 就是好的 
如图：
![image](https://cloud.githubusercontent.com/assets/6800546/18859638/75500534-84a8-11e6-8bc9-069aeb41df20.png)

**Comment by Leopoldthecoder** [comment]
@manwuyu 麻烦升级到 0.2.10 再试试
