### ISSUE TITLE
Field模块里那个增加数字的不是很人性化

### ISSUE THREAD

**Issue by paraofheaven** [ElemeFE/mint-ui#197]
点增加后，数字变为1，但原位置被清空的符号替换了，点快了会不明所以，建议把清空的符号放到前面来

**Comment by QingWei-Li** [comment]
似乎移动端的 Safari 还是 Chrome 都不会显示那个加减按钮的吧？至少我在 iOS 上是这样。放前面感觉太奇怪了。

**Comment by paraofheaven** [comment]
ios上试了一下，的确没有，改天在安卓上试一下，可以关了
