### ISSUE TITLE
vue-popup没有  visible

### ISSUE THREAD

**Issue by kobsucTam** [ElemeFE/mint-ui#198]
前些天npm上安装[vue-popup](https://www.npmjs.com/package/vue-popup)，发现对于ActionSheet等需要用到的组件没啥用，纠结了一下午，最终看vue-popup混淆后的代码，发现visible被 value代替了，但是npm上文档也没变，不知道现在修改没，我相信[vue-popup](https://www.npmjs.com/package/vue-popup)也是你们团队维护的，npm上也没git仓库，所以来这提问，请问这是什么情况？

**Comment by Leopoldthecoder** [comment]
vue-popup 目前有两个版本，分别支持 Vue 1.x 和 Vue 2.0。如果你使用的是 Vue 1.x，请安装 0.1.x 版本的 vue-popup。
