### ISSUE TITLE
这个可以直接在页面直接include使用吗

### ISSUE THREAD

**Issue by liwei1991** [ElemeFE/mint-ui#199]
这个可以直接在页面include lib/index.js 和lib/style.css
通过 Vue.use(MintUI); 使用吗？

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/mint-ui/issues/184

**Comment by liwei1991** [comment]
谢谢，再问一下js组件如何用include使用，比如toast组件 新手勿怪。再次感谢

**Comment by QingWei-Li** [comment]
通过 script 标签引入的会自动注册到 Vue 里。同时全局暴露了 ELEMENT 对象，通过 window.ELEMENT 可以访问到所有组件；其次 messagebox、toast 和 indicator 我们称作服务，已经注册到实例里。直接通过 `vm.$messagebox`, `vm.$toast` 和 `vm.$indicator` 就可以获取。

**Comment by qida** [comment]
@liwei1991  https://github.com/ElemeFE/mint-ui/tree/master/example/ 可以看一下例子，不知道能不能解决你的疑惑。

**Comment by liwei1991** [comment]
好的 我知道了，还有个疑问就是这个js组件和button之类的会用了 还有个就是scroll 和swiper又是该怎么用呢，感谢

**Comment by QingWei-Li** [comment]
看文档，还有别在 issue 里问了。去 [Gitter](https://gitter.im/ElemeFE/element?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
