### ISSUE TITLE
运行cnpm run dev 报错

### ISSUE THREAD

**Issue by huobaiyu** [ElemeFE/mint-ui#211]
$ cnpm run dev

> mint-ui@0.2.9 dev D:\Develop\vueprj\mint-ui
> npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js

npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN cooking@1.1.1 requires a peer of css-loader@^0.24.0 but none was installed.
npm WARN cooking@1.1.1 requires a peer of postcss-loader@^0.11.1 but none was installed.
npm WARN vue-loader@8.5.3 requires a peer of babel-runtime@^6.0.0 but none was installed.
Lerna v2.0.0-beta.18
Independent Versioning Mode
Linking all dependencies
Successfully bootstrapped 23 packages.

> mint-ui@0.2.9 build-entry D:\Develop\vueprj\mint-ui
> node bin/build-entry

[build entry] DONE: D:\Develop\vueprj\mint-ui\src\index.js

D:\Develop\vueprj\mint-ui\node_modules\.npminstall\path-is-inside\1.0.2\path-is-inside\lib\path-is-inside.js:24
    if (thePath[thePath.length - 1] === path.sep) {
                       ^

TypeError: Cannot read property 'length' of undefined
    at stripTrailingSep (D:\Develop\vueprj\mint-ui\node_modules\.npminstall\path-is-inside\1.0.2\path-is-inside\lib\path-is-inside.js:24:24)
    at module.exports (D:\Develop\vueprj\mint-ui\node_modules\.npminstall\path-is-inside\1.0.2\path-is-inside\lib\path-is-inside.js:8:23)
    at module.exports (D:\Develop\vueprj\mint-ui\node_modules\.npminstall\is-global-exec\0.1.0\is-global-exec\index.js:7:10)
    at Object.<anonymous> (D:\Develop\vueprj\mint-ui\node_modules\.npminstall\cooking\1.1.1\cooking\bin\cooking:15:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_global\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\Administrator\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "dev"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! mint-ui@0.2.9 dev: `npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mint-ui@0.2.9 dev script 'npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mint-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mint-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mint-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Develop\vueprj\mint-ui\npm-debug.log

**Comment by QingWei-Li** [comment]
别用 cnpm 装，路径都被改了。嫌慢的话用 `--registry=https://registry.npm.taobao.org` 或者仓库里建一个 `.npmrc` 文件配置 registry

**Comment by huobaiyu** [comment]
用npm run dev 报一样的错。

**Comment by QingWei-Li** [comment]
Fixed in https://github.com/QingWei-Li/is-global-exec/commit/608be855abf2cf97a0124117b22bf21d50a79698

单独升级下 is-global-exec 这个模块

**Comment by huobaiyu** [comment]
更新后问题一样：
| +-- is-global-exec@0.1.1
| | +-- global-bin-path@0.0.2
| | `-- path-is-inside@1.0.2

$ npm run dev

> mint-ui@0.2.9 dev D:\Develop\vueprj\mint-ui
> npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN cooking@1.1.1 requires a peer of css-loader@^0.24.0 but none was installed.
npm WARN cooking@1.1.1 requires a peer of postcss-loader@^0.11.1 but none was installed.
Lerna v2.0.0-beta.18
Independent Versioning Mode
Linking all dependencies
Successfully bootstrapped 23 packages.

> mint-ui@0.2.9 build-entry D:\Develop\vueprj\mint-ui
> node bin/build-entry

[build entry] DONE: D:\Develop\vueprj\mint-ui\src\index.js


D:\Develop\vueprj\mint-ui\node_modules\path-is-inside\lib\path-is-inside.js:24
    if (thePath[thePath.length - 1] === path.sep) {
                       ^

TypeError: Cannot read property 'length' of undefined
    at stripTrailingSep (D:\Develop\vueprj\mint-ui\node_modules\path-is-inside\lib\path-is-inside.js:24:24)
    at module.exports (D:\Develop\vueprj\mint-ui\node_modules\path-is-inside\lib\path-is-inside.js:8:23)
    at module.exports (D:\Develop\vueprj\mint-ui\node_modules\is-global-exec\index.js:7:10)
    at Object.<anonymous> (D:\Develop\vueprj\mint-ui\node_modules\cooking\bin\cooking:15:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! mint-ui@0.2.9 dev: `npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mint-ui@0.2.9 dev script 'npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mint-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mint-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mint-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Develop\vueprj\mint-ui\npm-debug.log

**Comment by huobaiyu** [comment]
升级后仍然出错
| +-- is-global-exec@0.1.1
| | +-- global-bin-path@0.0.2
| | `-- path-is-inside@1.0.2

$ npm run dev

> mint-ui@0.2.9 dev D:\Develop\vueprj\mint-ui
> npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN cooking@1.1.1 requires a peer of css-loader@^0.24.0 but none was installed.
npm WARN cooking@1.1.1 requires a peer of postcss-loader@^0.11.1 but none was installed.
Lerna v2.0.0-beta.18
Independent Versioning Mode
Linking all dependencies
Successfully bootstrapped 23 packages.

> mint-ui@0.2.9 build-entry D:\Develop\vueprj\mint-ui
> node bin/build-entry

[build entry] DONE: D:\Develop\vueprj\mint-ui\src\index.js


D:\Develop\vueprj\mint-ui\node_modules\path-is-inside\lib\path-is-inside.js:24
    if (thePath[thePath.length - 1] === path.sep) {
                       ^

TypeError: Cannot read property 'length' of undefined
    at stripTrailingSep (D:\Develop\vueprj\mint-ui\node_modules\path-is-inside\lib\path-is-inside.js:24:24)
    at module.exports (D:\Develop\vueprj\mint-ui\node_modules\path-is-inside\lib\path-is-inside.js:8:23)
    at module.exports (D:\Develop\vueprj\mint-ui\node_modules\is-global-exec\index.js:7:10)
    at Object.<anonymous> (D:\Develop\vueprj\mint-ui\node_modules\cooking\bin\cooking:15:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! mint-ui@0.2.9 dev: `npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mint-ui@0.2.9 dev script 'npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mint-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mint-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mint-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [D:\Develop\vueprj\mint-ui\npm-debug.log]

**Comment by QingWei-Li** [comment]
那你把 node_modules 清掉重新安装下吧。这个判断我已经加上了，按理说没问题的。

**Comment by huobaiyu** [comment]
已经把node_modules 删除；然后运行npm install; 再运行npm run dev。错误是一样的。

**Comment by QingWei-Li** [comment]
好了升级 `is-global-exec` 到 0.1.3

**Comment by huobaiyu** [comment]
旧的问题解决了，报了一个新错：
> mint-ui@0.2.9 build-entry D:\Develop\vueprj\mint-ui
> node bin/build-entry

[build entry] DONE: D:\Develop\vueprj\mint-ui\src\index.js

[cooking] - cooking is local module. You should use cooking-cli

            npm i cooking-cli -g


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! mint-ui@0.2.9 dev: `npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mint-ui@0.2.9 dev script 'npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mint-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && lerna bootstrap && npm run build-entry && cooking watch -c scripts/cooking.demo.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mint-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mint-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Develop\vueprj\mint-ui\npm-debug.log

我已经执行过npm i cooking-cli -g，还是报错。

**Comment by QingWei-Li** [comment]
问题太过诡异而且一直在 windows 上也没复现。目前临时措施是到 `node_modules\cooking\bin\cooking` 文件里把 `if (isGlobal()){...}` 那段判断删掉

**Comment by huobaiyu** [comment]
这个方法有效，已经可以了。
