### ISSUE TITLE
css 样式 

### ISSUE THREAD

**Issue by CarmineZhang** [ElemeFE/mint-ui#214]
我按照你们的说明
import Vue from 'vue'
import MintUI from 'mint-ui'
import VueResource from 'vue-resource'
import VueTouch from 'vue-touch'
import store from './vuex/store'
import Login from './components/login.vue'
import 'mint-ui/lib/style.css';
Vue.use(MintUI);

为什么生成的页面中却没有样式呢

**Comment by QingWei-Li** [comment]
贴一下你的 webpack 配置

**Comment by CarmineZhang** [comment]
.babelrc 
`{
  "presets": ["es2015","stage-2"],
  "plugins": ["transform-runtime",["component", [
    { "libraryName": "mint-ui", "style": true }
  ]]],
}`

**Comment by CarmineZhang** [comment]
webpack:
`  module: {
        loaders: [{
            test: /\.vue$/,
            loader: 'vue'
        }, {
            test: /\.js$/,
            loader: 'babel!eslint',
            // make sure to exclude 3rd party code in node_modules
            exclude: /node_modules/
        }, {
            test: /\.css$/,
            loader: 'css'
        }]
    },
    // vue-loader config:
    // lint all JavaScript inside *.vue files with ESLint
    // make sure to adjust your .eslintrc
    vue: {
        loaders: {
            js: 'babel!eslint'
        }
    }`

**Comment by QingWei-Li** [comment]
没有 style-loader 

自行谷歌 webpack 用法

**Comment by CarmineZhang** [comment]
明白了，我搞定了，Thank you
