### ISSUE TITLE
fastclick和loadmore组合的时候，下拉的时候很容易触发点击事件

### ISSUE THREAD

**Issue by winner3811** [ElemeFE/mint-ui#215]
fastclick插件和mint-ui的loadmore组合的时候，下拉的时候很容易触发点击事件

**Comment by Leopoldthecoder** [comment]
fastclick 是会引起类似问题。曾经内置 fastclick 支持的 [amaze UI](http://amazeui.org/) 也在 2.4 版本中将其移除：https://github.com/amazeui/amazeui/issues/567 。所以，可能需要自己寻求替代的处理方式。

**Comment by stringworld** [comment]
动态的给wrapper添加needsclick
this.$refs.wrapper.addEventListener('touchstart', function (event) {
                event.target.classList.add('needsclick');
            });

**Comment by HP-jackZhang** [comment]
fastclick  和 loadmore 配合使用时，有没有好的解决办法呢？

**Comment by siulunchien** [comment]
@stringworld 我在 mt-loadmore 这个组件上动态加 needsclick 是可以的，但是如果直接在 mt-loadmore 上面写死样式的话却不行，请问知道为什么吗？
