### ISSUE TITLE
popup 参数closeOnClickModal = “false”

### ISSUE THREAD

**Issue by angusjiang** [ElemeFE/mint-ui#223]
当我不想通过点击 modal 层来关闭 popup时，发现点击弹层依然关闭了popup

**Comment by Leopoldthecoder** [comment]
请确保这条属性是：`:close-on-click-modal="false"`，即属性名使用 kebab-case，并且前面要加冒号。

**Comment by angusjiang** [comment]
谢谢，是我的属性写错了

**Comment by yagmdream** [comment]
这个属性能在例子中加上吗? demo中别的属性示例都有。表示这个东西找了很久
