### ISSUE TITLE
对Picker组件的visibleItemCount接口建议增加一个奇偶性判断

### ISSUE THREAD

**Issue by seeyou404** [ElemeFE/mint-ui#231]
这个接口默认值是5，当设置为偶数的时候，默认的样式会错乱，改成如下样式会修复`.picker-slot-divider div{
    transform: translateY(18px);
  }
  .picker-center-highlight{
    margin-top:0;
  }`
但上面的样式不适用于visibleItemCount为奇数值的情况。建议增加一个奇偶性判断。

**Comment by Leopoldthecoder** [comment]
一般来说，`.picker-center-highlight` 应该垂直居中于整个 picker，如果 `visibleItemCount` 是偶数的话，`.picker-center-highlight` 是无法居中的（你的方法会使其偏下）。因此 `visibleItemCount` 应该是个奇数。

如果有业务场景要求 `visibleItemCount` 必须是偶数，建议用户自己覆盖 CSS。

**Comment by souldjl** [comment]
大佬们，这个在苹果手机 ，只能显示一个 item 是为什么啊
