### ISSUE TITLE
Bug with popup component

### ISSUE THREAD

**Issue by Yuyz0112** [ElemeFE/mint-ui#236]
### What is actually happening?

When a popup component was active, it will add the CSS arttribute 'overflow: hidden' on <body>. And it will not be removed when the component is inactive.

This will cause some bug like when I set 'height: 100%' on <html> and <body>, the document cannot scroll although there is some content overflow.

I just add 'overflow-y: auto' on body to override, but I think here need a better solution :)

**Comment by Leopoldthecoder** [comment]
I'm thinking about exposing this feature as an API so that you can turn it off.


In most cases, the 'overflow: hidden' removes when the popup deactivates. But if the disappearing animation gets interrupted (e.g. you jump to another page), things can go wrong. 

Anyway, this is on my to-do list.

**Comment by Leopoldthecoder** [comment]
fixed in #240 and #241
