### ISSUE TITLE
建议: 增加loadmore的pulldown下拉距离

### ISSUE THREAD

**Issue by spacemeowx2** [ElemeFE/mint-ui#238]
### Mint UI version
0.2.10

### Reproduction Link
官方Demo: http://elemefe.github.io/mint-ui/#!/pull-down

### Description
mint-ui的pulldown在下拉时, loadmore-top下降高度和手指高度是一致的, 这样让人感觉滑动速度过快. 比较符合人直觉的做法应该是手指滑动约2-3倍距离时top才被完全显示

### Code
目前我的修改是将下列代码:
> [packages/loadmore/src/loadmore.vue](https://github.com/ElemeFE/mint-ui/blob/8da004739c97491e63231e1035fda511bba473a4/packages/loadmore/src/loadmore.vue#L289)  

```javascript
...
handleTouchMove(event) {
  if (this.startY < this.$el.getBoundingClientRect().top && this.startY > this.$el.getBoundingClientRect().bottom) {
    return;
  }
  this.currentY = event.touches[0].clientY;
  let distance = this.currentY - this.startY;
  this.direction = distance > 0 ? 'down' : 'up';
...
```
改为  
```javascript
...
handleTouchMove(event) {
  if (this.startY < this.$el.getBoundingClientRect().top && this.startY > this.$el.getBoundingClientRect().bottom) {
    return;
  }
  this.currentY = event.touches[0].clientY;
  let distance = this.currentY - this.startY;
  distance /= 2
  this.direction = distance > 0 ? 'down' : 'up';
...
```

如果可以的话应该可以加一个props让开发者选择需要的倍数.

**Comment by Leopoldthecoder** [comment]
added in #239
