### ISSUE TITLE
[feature request] support for mt-cell + picker?

### ISSUE THREAD

**Issue by ritksm** [ElemeFE/mint-ui#243]
case:

1. init: load default value from picker data
2. action: mt-cell.click->show picker->pick value->update cell model value

Any chance of supporting this feature? 😄 

Maybe implement via adding a property(passing a pre-defined picker id) to `<mt-cell>`?

`<mt-cell :value-picker="#picker1"></mt-cell>`

**Comment by ritksm** [comment]
or mt-cell+html select?

**Comment by QingWei-Li** [comment]
@Leopoldthecoder 你看下？

**Comment by Leopoldthecoder** [comment]
If I'm getting it right, features like this should be handled by the user. You can do it by encapsulating a custom component with `mt-cell`, `mt-picker` and `mt-popup`.
