### ISSUE TITLE
mt-cell和mt-field混合使用的时候border混乱

### ISSUE THREAD

**Issue by ritksm** [ElemeFE/mint-ui#246]
在同一个form中可能会同时混合使用mt-cell（为了is-link）和mt-field

但是这样会导致边框混乱：border重合&border的对齐错乱

示例代码：
```
    <div>
      <mt-field label="银行卡号" placeholder="仅支持银联卡"></mt-field>
      <mt-cell title="所属银行" is-link></mt-cell>
      <mt-cell title="开户城市" is-link></mt-cell>
      <mt-field label="开户支行" placeholder="仅支持银联卡"></mt-field>
    </div>
```

如图：

![image](https://cloud.githubusercontent.com/assets/111809/19143120/5780b8d6-8bd4-11e6-8d6b-cbba38866ff7.png)

建议两种方案解决：
1、两个控件的border定义统一到一个class上。。比如 mt-form-item 之类的
2、mt-field支持类似is-link的功能，能够接受点击

**Comment by Leopoldthecoder** [comment]
fixed in #249

**Comment by hebian** [comment]
可以把mt-field的border去掉，自己重新写样式吗？ 
.mint-field, .mint-cell-left, .mint-cell-wrapper, .mint-cell-title, .mint-cell-text, mint-cell-value, .mint-field-core{
  border: 0 !important;
}这样为什么移动端不起作用
