### ISSUE TITLE
mt-button is not response click event on vue 2.0

### ISSUE THREAD

**Issue by pysjp** [ElemeFE/mint-ui#254]
### Mint UI version
    "mint-ui": "^2.0.0-rc.2",
### Device model
    chrome on pc

### What is Expected?
    <mt-button v-on:click="great">Greet</mt-button>
    <button v-on:click="great">Greet</button>
      great: function(event) {
        alert(event.target.tagName);
      }
### What is actually happening?
    mt-button is not response click event on vue 2.0

**Comment by QingWei-Li** [comment]
http://vuejs.org/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on

```javascript
<mt-button v-on:click.native="great">Greet</mt-button>
```

**Comment by pysjp** [comment]
yes it works,thanks a lot
