### ISSUE TITLE
picker组件的slots的 备选项values是否支对象数组

### ISSUE THREAD

**Issue by russellmars** [ElemeFE/mint-ui#258]
请问picker组件的slots的 备选项values是否支对象数组？这个对象的结构类似于

```javascript
{
  code: xxx,
  name: xxx
}
```
并将对象的name用于显示，能否做到？

**Comment by Leopoldthecoder** [comment]
不支持。如果需要显示值和实际值不同，可以在 `change` 事件中把显示值映射到实际值。
