### ISSUE TITLE
Field 组件如何绑定事件?

### ISSUE THREAD

**Issue by rubyless** [ElemeFE/mint-ui#259]
Field 组件如何绑定事件或者如何监听input的事件?

主要是用来自定义验证.  有没有好的解决方案?

**Comment by QingWei-Li** [comment]
请在 issue 里列清楚版本，用的 Vue 1 还是 2

如果是 2 的话有 .native 修饰符可以绑定原生事件，如果是 1 的话，最简单的方式是监听数据变化进行校验

**Comment by rubyless** [comment]
@QingWei-Li Vue2, 请问如何绑定blur 事件?

**Comment by QingWei-Li** [comment]
http://vuejs.org/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on

```html
<mt-field @blur.native="xxx"  />
```

**Comment by rubyless** [comment]
``` html
<mt-field @blur.native="xxx"  />
```
```javascript
export default {
  methods: {
    xxx() { console.log('xxx') }
  }
}
```
这样绑的话 blur 应该绑到 外层的div上面了吧... 还是我理解的不对..

**Comment by QingWei-Li** [comment]
哦我的错

可以自己封装一个指令，可以参考 https://github.com/QingWei-Li/vuerify/blob/master/packages/v-vuerify-next/index.js

或者如果你只是做数据校验的话，可是试试 https://github.com/QingWei-Li/vuerify/

**Comment by rubyless** [comment]
多谢!
