### ISSUE TITLE
单独调用 Swipe/SwipeItem 组件时会报错

### ISSUE THREAD

**Issue by hpyer** [ElemeFE/mint-ui#260]
![image](https://cloud.githubusercontent.com/assets/1290392/19219280/c4542406-8e41-11e6-82da-e7c3276a3fda.png)

``` js
import Vue from 'vue'
import { Swipe, SwipeItem } from 'mint-ui'

Vue.component(Swipe.name, Swipe)
Vue.component(SwipeItem.name, SwipeItem)
```

因为 SwipeItem 目录下没有 style.css 文件，所以导入包的时候就报错了。建一个空的 style.css 文件可解决，但是重新安装组件的话，又会报相同错误了~

另外，还有个情况，如果 style 标签定义了 scoped，就没办法重写 .mint-swipe-indicator （没有 data-v-x x 的元素）的样式。。把 scoped 去掉就可以。。不知道这个是 vue 的问题，还是 mint-ui 的

**Comment by QingWei-Li** [comment]
scoped 的限制就是这样的

不加 scoped 或者覆盖默认 mint 样式的话单独放到一个 css 文件里，方便管理

**Comment by hpyer** [comment]
明白，谢谢~
