### ISSUE TITLE
Module parse failed: D:\wamp\www\coffee\node_modules\mint-ui\lib\font\style.css Unexpected character '@' (2:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by reversesoul** [ElemeFE/mint-ui#264]
Module parse failed: D:\wamp\www\coffee\node_modules\mint-ui\lib\font\style.css Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.

我用的是laravel5.3 ，我在gulp的时候报了这个错。是缺少了什么包吗？用的是vue1.0.26，安装方法是 npm install mint-ui -S     。比较着急，谢谢！

**Comment by QingWei-Li** [comment]
自己参考 https://github.com/ElementUI/element-in-laravel-starter
