### ISSUE TITLE
我是一个新手，在用mint-ui的时候遇到了一些问题，为了避免issue冗余，我就都在这里写了，也给其它新手一些参考。

### ISSUE THREAD

**Issue by reversesoul** [ElemeFE/mint-ui#265]
### Mint UI version
^2.0.0-rc.2
### Device model

chrome

<mt-checklist
      title="复选框列表"
      v-model="value"
      :options="['选项A', '选项B', '选项C']">
  </mt-checklist>

不知道这个value在哪里设置

**Comment by Leopoldthecoder** [comment]
这里仅用来提交 Mint UI 相关的问题。上述问题请阅读 Vue 的文档。

**Comment by reversesoul** [comment]
不是，你理解错我的意思了。我下面data(){
`data(){
      return {
              value:"选项 A" 
     };
}`

这样还是报错的。

**Comment by Leopoldthecoder** [comment]
看一下文档吧，`value` 需要是一个数组。
