### ISSUE TITLE
vue/vue-template-compiler

### ISSUE THREAD

**Issue by baqianxin** [ElemeFE/mint-ui#267]
### vue  

`Vue packages version mismatch:

- vue@1.0.10
- vue-template-compiler@2.0.1

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.`

vue1.0.10  与 vue-template-compiler@2.0.1冲突，但是升级vue2.0.1之后，虽然不冲突，但是解析模板，语法错误，一直运行部成功，能帮忙瞧瞧吗

**Comment by QingWei-Li** [comment]
请检查 mint-ui 的版本是否是 next 的

**Comment by baqianxin** [comment]
我是直接download的项目，看package里面的version是0.2.10，我改成了2.0.0-rc.2,也没有运行起来，

**Comment by QingWei-Li** [comment]
那就贴一下错误信息

（如果是 `with in strict mode` 的错误，去看 Gitter 里的聊天记录）

**Comment by baqianxin** [comment]
我就想知道master版本的代码download下来，能跑起来吗
![image](https://cloud.githubusercontent.com/assets/6780391/19234237/d801cb62-8f1c-11e6-97c4-1761dd12a964.png)
![image](https://cloud.githubusercontent.com/assets/6780391/19234250/f108bcf6-8f1c-11e6-8e4a-281fa70d2215.png)
![image](https://cloud.githubusercontent.com/assets/6780391/19234261/fdd3fafe-8f1c-11e6-8ec6-2da317a798d2.png)

**Comment by baqianxin** [comment]
master里面无法npm install mint-ui@next 提示因为重复安装在自身了
那怎么才可以更新成next的呢

**Comment by QingWei-Li** [comment]
麻烦去看看 git 的使用教程

clone 下来默认是 master 分支，直接 npm run dev 就可以启动，如果要切到 next 请 git checkout next

**Comment by baqianxin** [comment]
嗯，明白了。
现在 我在家运行Ok了，主要解决的问题有两个
![image](https://cloud.githubusercontent.com/assets/6780391/19241535/a9289576-8f41-11e6-8aaf-84589b0fb73f.png)

一个是babel-plugin-transform-runtime@^6.8.0
一个是npm install babel-preset-stage-2
其他的都是小问题：npm install --only=dev  npm install
![image](https://cloud.githubusercontent.com/assets/6780391/19241592/da3fd0d4-8f41-11e6-9dc4-0d638072a40c.png)
再次感谢各位
:+1: :smile:
