### ISSUE TITLE
Mint UI 组件使用的时候绑定事件无效，是我用法有问题吗

### ISSUE THREAD

**Issue by reversesoul** [ElemeFE/mint-ui#271]
### Mint UI version
"dependencies": {
    "mint-ui": "^2.0.0-rc.2",
    "vue": "^2.0.1"
  },

------------------------------------------------------------------------------------------------------------------
```
<template>
<div id="app">
  <mt-button size="large" type="primary" v-on:click="primary">提交</mt-button>
  <h1 v-on:click="primary">hello vue!</h1>
</div>
</template>
```

渲染出来之后点击h1 是有反应的，点击button就没有反应了。

**Comment by reversesoul** [comment]
`<template>
<div id="app">
  <mt-button size="large" type="primary" v-on:click="primary">提交</mt-button>
  <h1 v-on:click="primary">hello vue!</h1>
</div>
</template>

<script>
  export default {
    name:'example',
    props:{

    },
    methods:{
        primary:function(){
            alert(2);
        }
    }
  }
</script>`

**Comment by reversesoul** [comment]
代码发不出来，奇怪

**Comment by QingWei-Li** [comment]
duplicated in https://github.com/ElemeFE/mint-ui/issues/254

**Comment by reversesoul** [comment]
It's so kind of you!

**Comment by wustzhaohui** [comment]
在组件上绑定原生事件需要在事件添加修饰符`.native`
