### ISSUE TITLE
在使用tabbar时遇到的问题

### ISSUE THREAD

**Issue by Ljiawen** [ElemeFE/mint-ui#275]
### What is Expected?
vue.common.js?e6cb:2569[Vue warn]: Failed to resolve directive: link (found in component <page-tabbar>)

是按照官方demo来写的

**Comment by QingWei-Li** [comment]
先检查版本，如果还有问题请给重现代码

**Comment by Ljiawen** [comment]
`<template>
  <div id="app">
 <div class="page-tabbar">
    <div class="page-wrap">
     <mt-header title="标题过长会隐藏后面的内容啊哈哈哈哈">
  <mt-button icon="more" slot="right"></mt-button>
</mt-header>
      <mt-tab-container style="page-tabbar-container" :active.sync="selected" swipeable>
        <mt-tab-container-item id="小王">
          <mt-cell v-for="n in 10" :title="'小王 '"></mt-cell>
        </mt-tab-container-item>
        <mt-tab-container-item id="订单">
          <mt-cell v-for="n in 5" :title="'订单 ' "></mt-cell>
        </mt-tab-container-item>
        <mt-tab-container-item id="发现">
          <mt-cell v-for="n in 7" :title="'发现 ' "></mt-cell>
        </mt-tab-container-item>
        <mt-tab-container-item id="我的">
          <div class="page-part">
            <mt-cell v-for="n in 12" :title="'我的 '"></mt-cell>
          </div>
          <mt-button v-link="'/'" style="margin: 0 10px;" type="danger" size="large">退出</mt-button>
        </mt-tab-container-item>
      </mt-tab-container>
    </div>

    <mt-tabbar :selected.sync="selected">
      <mt-tab-item id="小王">
        <img slot="icon" src="../src/assets/logo.png">
        小王
      </mt-tab-item>
      <mt-tab-item id="订单">
        <img slot="icon" src="../src/assets/logo.png">
        订单
      </mt-tab-item>
      <mt-tab-item id="发现">
        <img slot="icon" src="../src/assets/logo.png">
        发现
      </mt-tab-item>
      <mt-tab-item id="我的">
        <img slot="icon" src="../src/assets/logo.png">
        我的
      </mt-tab-item>
    </mt-tabbar>
  </div>


</div>
</template>

<script>
export default {
  name:'page-tabbar',
  data() {
    return {
      selected: '小王'
    };
  }
};
</script>`


版本
 "mint-ui": "^2.0.0-rc.2",
 "vue": "^2.0.1"
