### ISSUE TITLE
UC浏览器中picker组件样式问题

### ISSUE THREAD

**Issue by wan-bing** [ElemeFE/mint-ui#280]
### Mint UI version
"mint-ui": "^0.2.10",
    "vue": "^1.0.21"
### Device model
picker 组件

### What is Expected?
建议使用动态增加flex: 1,1, 0%，增加
/* for uc */
    -webkit-box-flex: 1,1, 0%;      
    -moz-box-flex: 1,1, 0%;         
    -ms-flex: 1,1, 0%;    
### What is actually happening?
UC浏览器中样式不一致。没有正确分配比例。使用flex  要加上
-webkit-box-flex: 1;      
-moz-box-flex: 1;         
-ms-flex: 1;

**Comment by Leopoldthecoder** [comment]
fixed in #301
