### ISSUE TITLE
请问一下，使用2.0的版本，看了Faq，照着你的配置处理了，还是报那个错，还需要处理些其它的吗？

### ISSUE THREAD

**Issue by nwug** [ElemeFE/mint-ui#281]
### What is actually happening?

**Comment by nwug** [comment]
[Error: ./~/mint-ui/lib/mint-ui.common.js
Module build failed: SyntaxError: E:/www/vv/node_modules/mint-ui/lib/mint-ui.common.js: 'with' in strict mode (9409:35)

**Comment by QingWei-Li** [comment]
请给出你的配置
