### ISSUE TITLE
Cell样式溢出问题

### ISSUE THREAD

**Issue by ringcrl** [ElemeFE/mint-ui#285]
<img width="727" alt="qq20161015-1 2x" src="https://cloud.githubusercontent.com/assets/16740021/19407863/20c9d35e-92e1-11e6-9f8c-67d895e25688.png">
如图，代码如下

```
<template>
	<div class="page-cell">
		<mt-cell v-for="fans in fansList" :title="fans.name" icon="more">
			<span>献花<img src="../assets/flower.png">{{fans.flower}}朵</span>
			<img slot="icon" :src="fans.imgs" width="20" height="20">
		</mt-cell>
	</div>
</template>
```

**Comment by QingWei-Li** [comment]
请报上版本号 最好能提供可复现的 demo

**Comment by ringcrl** [comment]
<img width="1169" alt="qq20161015-2 2x" src="https://cloud.githubusercontent.com/assets/16740021/19408642/12822e0e-92f5-11e6-9fcd-3e525dddde4d.png">

可复现demo，例子用的是官网那个那个
[mint-cell.zip](https://github.com/ElemeFE/mint-ui/files/531042/mint-cell.zip)

**Comment by QingWei-Li** [comment]
遗漏了这个样式，你可以先手动覆盖一下
```
.mint-cell-wrapper {
    box-sizing: border-box;
}
```
下版本更新
