### ISSUE TITLE
调用Toast的时候提示 ReferenceError: Can't find variable: Toast

### ISSUE THREAD

**Issue by ringcrl** [ElemeFE/mint-ui#286]
在main.js里面引入了全部组件
```
import Vue from 'vue'
import App from './App'
import MintUI from 'mint-ui';
import VueRouter from 'vue-router'
import VueResource from 'vue-resource'
import 'mint-ui/lib/style.css';

Vue.use(VueRouter)
Vue.use(VueResource)
Vue.use(MintUI);
```

在其中一个路由页面的methods里面调用了Toast('消息')
```
methods:{
  showToast: function() {
     alert('进来了')
     Toast('提示信息');
},
```

然后在后面的某个方法里面调用了this.showToast()

页面上会提示 “进来了” 的alert的弹窗，然后控制台就报错了
Can't find variable: Toast

版本号：

```
"dependencies": {
    "mint-ui": "^2.0.2",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.1"
  },
```

**Comment by purely-smile** [comment]
Toast 这个变量你没有定义。
可以单独引入，根据文档。import 'Toast' from 'mint-ui';
按照你这样，你可以尝试使用this.$toast('test')

**Comment by ringcrl** [comment]
@purely-smile 按照你的方式成功了！谢谢！文档上没看到哪里又说需要这样子this.$toast('test')用噢，你是怎么知道得，我也尝试过按照文档说的那样import 'Toast' from 'mint-ui';可是在调用Toast('提示信息');的时候还是没有任何反应，是我的用法不对吗。

**Comment by purely-smile** [comment]
我也刚接触Vuejs。console.log(this)能找到绑定的方法，因为一开始使用vuejs.use了。所以挂载了方法

**Comment by Leopoldthecoder** [comment]
@ringcrl `import { Toast } from 'mint-ui'` 应该写在你使用了 Toast 的那个文件里，而不是 main.js 里。

**Comment by lijicheng123** [comment]
我的toast使用也有问题
main.js:
```
import { Button, Cell,Toast} from 'mint-ui'
Vue.component(Button.name, Button)
Vue.component(Cell.name, Cell)
Vue.config.productionTip = false
Vue.use(Toast)
```
component/HelloWorld.vue:
```
<mt-button @click.native="handleClick">666</mt-button>


<script>
export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  methods: {
    handleClick: function() {
      // Toast('123456789')
      this.$toast(123456);
    }
  }
}
</script>

```
结果却是：
![image](https://user-images.githubusercontent.com/15669871/35151929-399a891a-fd5b-11e7-87e1-8ba6ec67392e.png)

但是如果在HelloWord.vue里边引入Toast  并且直接Toast(111)是为问题的，但我真的想

this.$toast('111222')

这么用，请问我该怎么办

谢谢

@purely-smile @ringcrl

**Comment by lijicheng123** [comment]
![image](https://user-images.githubusercontent.com/15669871/35152230-71a1d2fe-fd5c-11e7-8218-f5a5422260b4.png)

这样用也还报错

但是那个Toast(2222)是有效的

![image](https://user-images.githubusercontent.com/15669871/35152261-a2a0674e-fd5c-11e7-8fce-76d39526a03d.png)

**Comment by try-to-fly** [comment]
@lijicheng123 

### 方法1
建议先看文档使用[参考](http://mint-ui.github.io/docs/#/en2/toast)
### 方法2
main.js 中使用```Vue.use(Mint)``` 全局挂在toast方法，这样在组建里面使用this.$toast方法即可。
```js
import Vue from 'vue'
import App from './App'
import Mint from 'mint-ui';
import 'mint-ui/lib/style.css'

Vue.config.productionTip = false
Vue.use(Mint)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  components: { App },
  template: '<App/>'
})

```
App.vue
```js
export default {
  name: 'App',
  methods:{
    show(){
      this.$toast('hello world');
    }
  }
}
```

**Comment by lijicheng123** [comment]
试了一下，
```
import MintUi from 'mint-ui'
Vue.use(MintUi)
```
是可以用
```
this.$toast('hello world')
```




但是
```
import { Button, Cell,Toast,Header} from 'mint-ui'
Vue.component(Button.name, Button)
Vue.component(Cell.name, Cell)
Vue.component(Toast.name, Toast) || Vue.use(Toast)
Vue.component(Header.name, Header);
```
这种方式是不能使用
```
this.$toast('hello world')
```

我不想将整个mint-ui都引入使用

@purely-smile

**Comment by mangoooooo** [comment]
@lijicheng123 
同样遇到这个问题，请问现在有解决方案了吗？

**Comment by lijicheng123** [comment]
@mangoooooo 

自己写一个Vue.prototype.$toast = function (option){
Toast(option)
}

**Comment by mangoooooo** [comment]
@lijicheng123 
#1294
