### ISSUE TITLE
button @click事件

### ISSUE THREAD

**Issue by thonatos** [ElemeFE/mint-ui#287]
源代码：
```
<mt-button class="submit" @click="say" size="large">初始化</mt-button>
```

渲染后代码：
```
<button class="mint-button submit mint-button--default mint-button--large" data-xxxxx="">
    <label class="mint-button-text">初始化</label>
</button> 
```

直接写(正常)：
```
<button @click="say()" class="mint-button submit mint-button--default mint-button--large" data-xxxxx="">
    <label class="mint-button-text">初始化</label>
</button>  
```

**Comment by ringcrl** [comment]
我一般也没写在这个标签里面，写了好像不生效，写在初始化这几个字位置，放了一个新标签，渲染出来也不见了，所以我每次把`<mt-button class="submit" @click="say" size="large">初始化</mt-button>`放在一个自己的标签里面，感觉这么写也不科学

**Comment by thonatos** [comment]
@ringcrl 

我意思是这个绑定有问题，不能绑定事件

**Comment by purely-smile** [comment]
+1 ，我目前也是放在一个div绑定的click

**Comment by QingWei-Li** [comment]
你们....
难道不看 vue 的文档么.....
或者看看 faq.md 么.....
或者看看 example 里的写法么....
真的不知道自定义组件加原生事件要用 native 么....

**Comment by thonatos** [comment]
@QingWei-Li 

（加native这个，还真不知道... 都是自己写，没怎么用过别人的...T.T，补课了）
搜了一圈终于在提issues的位置看到了faq，建议faq放个显眼的位置吧，比如文档那边~
