### ISSUE TITLE
使用vue-cli搭建的环境，一引入组件就报错

### ISSUE THREAD

**Issue by killdada** [ElemeFE/mint-ui#289]
直接import { Spinner } from 'mint-ui' 报的error css-loader
import { Spinner } from '../../node_modules/mint-ui/lib/spinner';
这样引入的时候没报错，但是 named exports in *.vue files are ignored. 导致组件无法用，
请问配置需要怎么修改

**Comment by QingWei-Li** [comment]
所以你不打算列出完整的错误信息，以及你的配置，以及所使用的版本么？

**Comment by Evansy** [comment]
![qq 20161017105633](https://cloud.githubusercontent.com/assets/17985050/19424020/605fb7c2-9458-11e6-90bc-97e21bfda652.png)

**Comment by QingWei-Li** [comment]
也不算是 bug，只是 vue-loader 8.0 在判断 export 的地方有个逻辑错误，不过估计也不好修复。可以忽视的，修复在 https://github.com/ElemeFE/mint-ui/pull/297
