### ISSUE TITLE
Cell组件value和slot同时开启时，出现文本和图标遮挡

### ISSUE THREAD

**Issue by wenjingbiao** [ElemeFE/mint-ui#305]
### Mint UI version
2.0.2
### Device model
 @所有设备

### What is actually happening?
详情请看下图， cell组件中， value和slot同时开启时，会出现文本和图标遮挡
![image](https://cloud.githubusercontent.com/assets/8213998/19473614/f4d8b050-955e-11e6-97b7-cc3cf8c86e5a.png)

**Comment by cgygd** [comment]
今天也发现了这个问题，希望尽快修复～
