### ISSUE TITLE
lazy-load的缺陷吗？

### ISSUE THREAD

**Issue by ringcrl** [ElemeFE/mint-ui#306]
我的lazy-load和轮播一起使用的，有时候会出现图片位置一片空白的情况，在什么情况下会发生这种情况呢，等待再久也不出来图片，怎么改善这种情况比较好哦。如果有什么需要我再次汇报的我继续描述详细信息

**Comment by QingWei-Li** [comment]
给个 demo？

**Comment by ringcrl** [comment]
demo就是轮播图里面一片空白，我的页面结构是有数十个轮播，每个轮播里面有3、4张图片
复现场景就是看第一个轮播图的时候，划了几下，有时候会出现下面的轮播一片空白，滑动到后面或者滑动回来这张图片也不会再出现了，就一直空白状态，因为电脑浏览器不能滑动，也基本不会出现，所以就不给你demo了，这种情况比较频繁出现在手机上，我用了阿里云的图片cdn加速，可是检测到部分城市确实会存在比较慢的情况

我的代码使这样写的，不知道是不是代码写的不太好的问题，一般的浏览还是可以的，有时候个别图片空白了就一直空白了，等待再久也不会出来
```
 <li v-for="(belle,index) of belleList" style="padding: 15px 15px">
                <p>{{belle.name}}</p>
                <mt-swipe :auto="0">
                    <mt-swipe-item v-for="item of belle.imgs">
                        <img src="" v-lazy="item.url" height="100%">
                    </mt-swipe-item>
                </mt-swipe>
```

**Comment by QingWei-Li** [comment]
一片空白可能就是图片还没加载出来吧？

**Comment by ringcrl** [comment]
@QingWei-Li 

是的啊，可以做那种一次加载不出来，点击空白位置重新获取图片src的方法嘛~~

**Comment by ringcrl** [comment]
@QingWei-Li 

要不感觉挺不稳定的，在我自己手机上测试，代码写法如上，也会出现图片一直不出来的情况，但是如果不使用v-lazy，直接写在src=""里面，没有出现过图片出不来的情况，不知道具体细节问题出在哪里

**Comment by jakajacky** [comment]
@ringcrl 这个v-lazy的问题你找到原因了吗？我现在也是变成空白的，而且也并不是加载不出来

**Comment by huoxudong125** [comment]
没写解释就关了，是什么个意思？@galenyuan
