### ISSUE TITLE
Swicth 样式问题：

### ISSUE THREAD

**Issue by AngusFu** [ElemeFE/mint-ui#307]
## 问题描述

在 UC 浏览器和微信中，Switch 组件样式出现问题。如图：

![image](https://cloud.githubusercontent.com/assets/8180186/19474965/6ec230f8-9564-11e6-8d1e-05c8b351a76b.png)

## 测试环境

- OS: iOS 10.0.2
- WeChat: 6.3.27
- UC:   UC Browser 11

**Comment by QingWei-Li** [comment]
哪个版本的 Mint？我以为还是没设置 appearance，但是看了下代码都加上了

**Comment by AngusFu** [comment]
囧，我看的是 demo 版。所以已经修复了？

**Comment by QingWei-Li** [comment]
还真有。。。我再看看
