### ISSUE TITLE
index list load data from vue-resource

### ISSUE THREAD

**Issue by ibmsoft** [ElemeFE/mint-ui#308]
### Mint UI version
2.0.2
### Device model
iphone 6

### What is actually happening?
use the vue-resource to get data,the index list show ok,but when click the right index [A-Z] ,it not go to
the indexed section
my async load data code snip like 
` created() {
            Indicator.open({
                spinnerType: 'fading-circle'
            });
            this.init();
        },
        methods:{
            init:function () {
                var self = this;
                this.$http.get("/oauser/"+this.$route.params.bh).then((response)=> {
                    let datalist = response.body;
                    Object.keys(datalist).forEach(function (initial) {
                        var cells = datalist[initial];
                        self.alphabet.push({
                            initial,
                            cells
                        })
                    });
                   
                }, (response)=> {

                });
                Indicator.close();
            },
        }`

**Comment by Leopoldthecoder** [comment]
fixed in #312
