### ISSUE TITLE
mt-switch控件，获取值不稳定

### ISSUE THREAD

**Issue by winner3811** [ElemeFE/mint-ui#309]
mt-switch :value.sync="item.stateFlag" @click.stop="setTimeState(item)"></mt-switch
在setTimeState函数里面为什么获取值，ios和android值不一样，华为5c和小米m1又不一样？

**Comment by QingWei-Li** [comment]
请提供 demo 链接

**Comment by winner3811** [comment]
我更新到v1.0.0，就不会了，但是在ios的webview里面样式有问题，android的不会

**Comment by QingWei-Li** [comment]
什么样式问题，麻烦截个图
