### ISSUE TITLE
loadmore文档 api有一处描述错误

### ISSUE THREAD

**Issue by purely-smile** [ElemeFE/mint-ui#310]
2.0.2 版本
[loadmore文档](http://mint-ui.github.io/docs/#!/zh-cn2/loadmore)

topMethod	下拉刷新执行的方法	Function		
top-status-change	下拉刷新执行的方法	Function  （和上面的描述重复，看loadmore的源码。props里也没有top-status-change这个属性）

**Comment by Leopoldthecoder** [comment]
是的，多谢提醒。

**Comment by purely-smile** [comment]
@Leopoldthecoder 文档还有一处错误
[Infinite scroll](http://mint-ui.github.io/docs/#!/zh-cn2/infinite-scroll)
范例中的 v-infinite-scroll="loadMore()"   应该为v-infinite-scroll=“loadMore”， 看了下example/pages/infinite-scroll.vue里面的源码用的也是loadMore，不然导致浏览器死循环了。

**Comment by QingWei-Li** [comment]
欢迎 PR https://github.com/mint-ui/docs

**Comment by Leopoldthecoder** [comment]
fixed
