### ISSUE TITLE
minit-ui的vue-toast-mobile支持vue2.0吗？

### ISSUE THREAD

**Issue by tyrion-yu** [ElemeFE/mint-ui#313]
### What is Expected?

想单独使用支持VUE2.0的vue-toast-mobile

### What is actually happening?

观察代码，觉得他使用的不是vue2.x规范的语法。
https://github.com/ElemeFE/vue-toast-mobile/blob/master/src/toast.vue
如代码片段：
```
class="mint-toast {{ customClass }}" transition="mint-toast-pop"
```

在vue2.x中，`transition`已经不能这样用了。`customClass`也应该用`:class`语法。

**Comment by Leopoldthecoder** [comment]
直接使用 Mint UI 中的 toast：https://github.com/ElemeFE/mint-ui/blob/master/packages/toast/src/toast.vue
