### ISSUE TITLE
index-list

### ISSUE THREAD

**Issue by jiangzheng-web** [ElemeFE/mint-ui#316]
我用的vue2.0.3  mint-ui是2.0.2的 用index-list点击右侧导航字母的时候会报 'getBoundingClientRect' of undefined，求大牛帮忙看一下是哪里的问题

**Comment by Leopoldthecoder** [comment]
请提供在线 demo

**Comment by jiangzheng-web** [comment]
之前是好用的，但是前天晚上更新过版本之后就报错了
<mt-index-list>
          <mt-index-section v-for="(item,index) in cityList" :index="index">
             <mt-cell v-for="city in item" :title="isMtCityCdDscp(city)" @click.native="cityChoice(city)">            </mt-cell>
          </mt-index-section>
        </mt-index-list>
cityList里是下面这样的数据
a:[{mtCtryCd: "CN", mtCtryCdDscp: "中国", mtStateCd: "029", mtStateCdDscp: "内蒙古", mtCityCd: "152900",…},…]
b:[{mtCtryCd: "CN", mtCtryCdDscp: "中国", mtStateCd: "007", mtStateCdDscp: "河北", mtCityCd: "130600",…},…]
c:[{mtCtryCd: "CN", mtCtryCdDscp: "中国", mtStateCd: "007", mtStateCdDscp: "河北", mtCityCd: "130800",…},…]
我在项目里改过右侧abcd导航栏的位置，这个是不是也有些关系

**Comment by Leopoldthecoder** [comment]
还是需要一个 demo，包括你是怎样修改导航栏的位置的。可以建一个 GitHub 仓库，把最小可重现问题的代码放上去。

**Comment by jiangzheng-web** [comment]
应该是动态赋值的问题，谢谢大牛了，现在坐等版本更新了
