### ISSUE TITLE
组件本地可以访问，手机端内容无显示

### ISSUE THREAD

**Issue by NameLi** [ElemeFE/mint-ui#317]
### Mint UI version
"vue": "^2.0.1",
"mint-ui": "^2.0.2"
### Device model
 iOS 9.3 Safari or Wechat webview

### Reproduction Link
http://toblilinghui.tunnel.2bdata.com/

### What is actually happening?
组件本地可以访问，使用ngrok在手机端访问时，iphone5s，ios9下访问内容无显示，iphone6，ios10下访问正常。

**Comment by Leopoldthecoder** [comment]
你的代码里有一个 `const` 没有被处理，导致 iOS 9.3 的 Safari 报错了。
