### ISSUE TITLE
npm 安装mint-ui后，所有配置都设置好，也可以正常使用，但要如何定制UI？

### ISSUE THREAD

**Issue by leson1986** [ElemeFE/mint-ui#337]
npm 安装mint-ui后，所有配置都设置好，也可以正常使用，但要如何定制UI？比如，我引用了MessageBox的弹窗，但我要改弹窗的整个内容（包括div布局，样式等），不知道在哪修改，可不可以修改！？

**Comment by Leopoldthecoder** [comment]
HTML 结构不能配置，样式可以自行覆盖。

仅就 MessageBox 而言，后面会考虑支持传入 HTML 模板。
