### ISSUE TITLE
icon能不能自定义 现在<mt-cell>里的icon只能用mintui的

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#338]
![image](https://cloud.githubusercontent.com/assets/13248613/19632179/c7b81d00-99d6-11e6-8985-4e28cf386ad2.png)
![image](https://cloud.githubusercontent.com/assets/13248613/19632181/d073bd0a-99d6-11e6-9add-2aa483763d0e.png)

**Comment by QingWei-Li** [comment]
icon 支持 slot

**Comment by ecitlm** [comment]
现在支持吗
