### ISSUE TITLE
iOS平台上，Switch开关聚焦时，出现黑色背景

### ISSUE THREAD

**Issue by wenjingbiao** [ElemeFE/mint-ui#339]
### Mint UI version

2.02

### Device model
all iOS 

### What is Expected?
当开关打开时，不应该出现黑色背景，
 解决方案是 把mint-switch-input的透明度降为0

### What is actually happening?
 如下图
![image](https://cloud.githubusercontent.com/assets/8213998/19633202/7c030856-99e1-11e6-8234-ba79eddbf7b5.png)

**Comment by Leopoldthecoder** [comment]
Duplicate of #307
