### ISSUE TITLE
tabbar 中 tab-item 不能选中

### ISSUE THREAD

**Issue by yixiaohuan** [ElemeFE/mint-ui#343]
刚用Vue-cli. Vue版本号 2.0
运行环境： Mac, Chrome
html代码：
# <body>
    <div id="app">
      <mt-tabbar :selected.sync="tabIndex">
        <mt-tab-item id="tab1">
          <img slot="icon" src="./assets/logo.png">
          tab1
        </mt-tab-item>
        <mt-tab-item id="tab2">
          <img slot="icon" src="./assets/logo.png">
          tab2
        </mt-tab-item>
      </mt-tabbar>
    </div>
    
  </body>

js代码

`new Vue({
  el: '#app',
  data: {
    tabIndex: 'tab1'
  },
  methods: {
  }
})
`

问题： 界面上 tab1 没有被选中

**Comment by QingWei-Li** [comment]
2.0 没有 sync，用 v-model，具体看文档 http://mint-ui.github.io/docs/#!/zh-cn2/tabbar

**Comment by ghost** [comment]
必须设置id 。。。
