### ISSUE TITLE
checkBottomReached 方法检测在pc版chrome 版本 54.0.2840.59 m中失效

### ISSUE THREAD

**Issue by chenEdgar** [ElemeFE/mint-ui#344]
checkBottomReached检测方法如下，当this.scrollEventTarget === window时，
    ` checkBottomReached() {
          if (this.scrollEventTarget === window) {
            return document.body.scrollTop + document.documentElement.clientHeight === document.body.scrollHeight;
          } else {
            return this.$el.getBoundingClientRect().bottom <=   this.scrollEventTarget.getBoundingClientRect().bottom;
          }
        },`
chrome pc下测试（后者模拟手机模式测试）结果如下：当垂直滚动条到底部是，.scrollTop的值不在是整数（这一点与MDN上的文档说明不符合[element.scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop)）

![360 20161024204800](https://cloud.githubusercontent.com/assets/12596622/19646361/a91432bc-9a2b-11e6-9647-9d9e931a5a74.jpg)

在移动端测试是没有问题de

**Comment by Leopoldthecoder** [comment]
感谢提醒。

1.x 的时候修过这个问题，迁到 2.0 的时候不知怎么丢了这个修复。现已补充。
