### ISSUE TITLE
在微信、UC浏览器中有问题，

### ISSUE THREAD

**Issue by gao-xiang** [ElemeFE/mint-ui#350]
演示中的内容在微信 中有卡顿的感觉，不是很流畅，
在UC中把页面向上拖后，向下时需要两次以上才有反应，Switch 是错乱的。

**Comment by QingWei-Li** [comment]
Switch 问题刚刚已经修复，卡顿是哪些组件卡顿？

**Comment by fuchao2012** [comment]
Android UC浏览器中有很多兼容性问题，建议统一修改

**Comment by run27017** [comment]
没错，Android UC浏览器中有很多兼容性问题，建议统一修改
