### ISSUE TITLE
pull up loadBottom方法一开始就执行。请问如何解决？

### ISSUE THREAD

**Issue by varrant** [ElemeFE/mint-ui#352]

**Comment by Leopoldthecoder** [comment]
参考文档，将 `autoFill` 设为 `false`。

**Comment by a312586670** [comment]
autoFill 在哪里设置，我看api中设置这些发现都是没有起效果

**Comment by Leopoldthecoder** [comment]
在 `mt-loadmore` 标签上加 `:auto-fill="false"`

**Comment by a312586670** [comment]
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-bb578392!./~/vue-load                   er/lib/selector.js?type=template&index=0!./src/views/circle/science.vue
template syntax error - invalid expression: :bottomLoadingText="加载中..."

**Comment by a312586670** [comment]
这感觉不对，应该不用“：”号吧

**Comment by a312586670** [comment]
发现还是不行

**Comment by a312586670** [comment]
貌似api中所说的哪些属性加了没有，应该是一个bug

**Comment by Leopoldthecoder** [comment]
`auto-fill` 前面是要加冒号的，因为 `false` 不是一个字符串字面量。
如果不行请提供在线 demo。

**Comment by a312586670** [comment]
加了还是没有用，你可以用微信访问下我的看下我的效果，刚刚滑动就在触发了下面的上拉滚动加载数据了
http://cms.huobanj.cn/#/science

**Comment by a312586670** [comment]
目前出现的问题是我滚动条还没到达底部，就触发了上拉加载数据的方法（bottomMethod）

**Comment by Leopoldthecoder** [comment]
嗯，看上去不是 `auto-fill` 的问题了。把无关代码去掉，然后发一个在线 demo 吧。

**Comment by a312586670** [comment]
已经放到git上了，你可以帮我看看那个pull up问题
地址https://github.com/a312586670/vue-mint-demo

**Comment by a312586670** [comment]
已经好了，发现是我的滚动条的样式没弄好，不过现在有了另外一个新的问题
pull up 上拉状态变成drop后，那个箭头的方向不会变，看代码有控制drop状态时应该是向下的箭头了，是不是触摸下来还没放开阻断了js的线程问题呢

**Comment by Leopoldthecoder** [comment]
箭头的方向需要你自己通过 CSS 控制。我没有找到对应于 `is-rotate` 的样式。
