### ISSUE TITLE
Spinner放在Cell里为什么右侧会有一块不见了

### ISSUE THREAD

**Issue by hezhongfeng** [ElemeFE/mint-ui#353]
如图这样，右边缺少一块,右边应该是三个点的
![qq 20161025153905](https://cloud.githubusercontent.com/assets/12163050/19676898/5d74a438-9ac9-11e6-9e86-433439afdca9.png)
代码和咱们的example里的是一样的
```
    <mt-cell title="triple-bounce">
      <mt-spinner color="#26a2ff" type="triple-bounce"></mt-spinner>
    </mt-cell>
```
应该是使用cell的问题，不知道为啥，下图的字也有问题
![qq 20161025162756](https://cloud.githubusercontent.com/assets/12163050/19678394/2b2e84ba-9ad0-11e6-8586-798639022d45.png)

**Comment by QingWei-Li** [comment]
请带上版本号

**Comment by hezhongfeng** [comment]
@QingWei-Li 
最新的tag 2.0.2v

**Comment by QingWei-Li** [comment]
Duplicated in https://github.com/ElemeFE/mint-ui/issues/285

**Comment by hezhongfeng** [comment]
@QingWei-Li 
谢谢
