### ISSUE TITLE
datetimepicker插件,设置了endDate,选择更早年份的时候，月份不恢复限制。

### ISSUE THREAD

**Issue by deepcoldy** [ElemeFE/mint-ui#355]
下图是刚执行open()，是正常显示的
![image](https://cloud.githubusercontent.com/assets/10922642/19683057/0e7e542c-9ae3-11e6-9126-3d239afdcb86.png)

下图是往下滑了一下，2016年的11月和12月由于限制了startDate，而消失。
![image](https://cloud.githubusercontent.com/assets/10922642/19683107/69aeb4d6-9ae3-11e6-8a3b-7b49698e8da7.png)

下图是选择了2015年，但是11月和12月不恢复。
![image](https://cloud.githubusercontent.com/assets/10922642/19683079/3c14937e-9ae3-11e6-9893-dc5ef548d6b3.png)

另外如果设置了endDate会出现如下情况：时间选择栏为空
![image](https://cloud.githubusercontent.com/assets/10922642/19683838/a94546fc-9ae6-11e6-871f-57792bc99e8e.png)

### Device model
Chrome

**Comment by Leopoldthecoder** [comment]
已经修复，本周会发布新版。

**Comment by HereSinceres** [comment]
你好,你是否在两个版本上都更新了

**Comment by deepcoldy** [comment]
@HereSinceres 你说的哪两个版本？我用的2.0.2目前是最新版。

**Comment by HereSinceres** [comment]
@deepcoldy vue1.0 和vue2.0中是否都更新  我现在用的mint-ui 1.0.0

**Comment by deepcoldy** [comment]
@HereSinceres 我觉得要修复应该都会一起修复的

**Comment by Leopoldthecoder** [comment]
两个版本都已修复，预计明天一起发新版。

**Comment by deepcoldy** [comment]
@Leopoldthecoder 非常感谢~

**Comment by Jabbar2010** [comment]
+1
