### ISSUE TITLE
下拉刷新微信内问题

### ISSUE THREAD

**Issue by HereSinceres** [ElemeFE/mint-ui#365]
## 微信内下拉刷新

下拉刷新过程中（要很快）再次下拉【此时出现此网页有129.12.2.*提供】，导致下拉一直处于loading状态。
## 尝试方案

是否在触发事件【下拉 上拉】时，判断当前状态如果是loading状态直接return

**Comment by Leopoldthecoder** [comment]
再次下拉出现「此网页由129.12.2.*提供」是微信浏览器的行为。

loadmore 本身是会判断是否处于 loading 状态的，具体可以查看官方示例：http://elemefe.github.io/mint-ui/#/pull-down 。如果你在使用时发现会一直处于 loading 状态，请给出在线 demo

**Comment by Leopoldthecoder** [comment]
标有 need repro 标签的 issue，如果 7 天没有收到任何 repro 的步骤或者 Demo，我们会做关闭处理。如果可以重现了，请再打开这个 issue。
