### ISSUE TITLE
button组件disabled以后还能触发click

### ISSUE THREAD

**Issue by russellmars** [ElemeFE/mint-ui#366]
button组件disabled以后还能触发click，代码如下
``` html
<mt-button type="primary" @click.native="testDisabledClick()"
      :disabled="true">默认</mt-button>
```

``` javascript
testDisabledClick () {
   console.log(11)
}
```
按钮看起来确实被disabled了，但是当点击按钮的边缘的时候还是可以触发click事件，更离谱的是，当我不使用chrome的设备模拟的时候，也就是正常pc页面中，按钮的样式是变了，但是完全不能不起作用了

**Comment by ringcrl** [comment]
你确定。。testDisabledClick()要带括号嘛。。

**Comment by russellmars** [comment]
@ringcrl 带括号 内联语句 事件处理器的写法，代表不传参数，默认不带括号的事件处理器可以拿到一个event 参数的[vue文档里有说明](https://vuefe.cn/guide/events.html)， 但是这个disabled确实有问题
