### ISSUE TITLE
button引用的时候报错

### ISSUE THREAD

**Issue by nieyulin112** [ElemeFE/mint-ui#368]
Do not use built-in or reserved HTML elements as component id: button 

代码如下:
html:<mt-cell class="page-part" title="当前选中" :value="selected" />
import {
    button
} from 'mint-ui'

export default {
    name: 'app',
    components: {
        button
    },
    data () {
        return {
            selected: '外卖'
        }
    }
}

求讲解，谢谢！

**Comment by Leopoldthecoder** [comment]
看一下 #358
