### ISSUE TITLE
DatePicker设置startDate之后，切换年份之后月份不会变化

### ISSUE THREAD

**Issue by muermaru** [ElemeFE/mint-ui#373]
### Mint UI version
1.0
### Device model

 iOS 10.03 WKWebview
### What is Expected?
datepicker的startDate设置之后，切换年份月份也一起变化
### What is actually happening?
datepicker的startDate设置为当前时间，之后切换年份，月份依然是今年剩下的月份，不会变动

**Comment by Leopoldthecoder** [comment]
刚发布了新版，试试更新到 1.0.1

**Comment by muermaru** [comment]
多谢回复。看了下，我用的还是0.2几版本……如果已经修复了的话，我后续项目里再试试吧

**Comment by Leopoldthecoder** [comment]
好的，issue 先关闭了，有问题的话可以重新提。
