### ISSUE TITLE
mint-ui.common.js 更新到2.0.3后一直报错

### ISSUE THREAD

**Issue by forzalianjunting** [ElemeFE/mint-ui#374]
![image](https://cloud.githubusercontent.com/assets/15181706/19794502/3f88768c-9d05-11e6-8fa7-a9ae16ff48ed.png)
怎么解决啊？刚退回到2.0.2版本就没有报错了

**Comment by Leopoldthecoder** [comment]
抱歉，我们的问题，升级到 2.0.4
