### ISSUE TITLE
基础问题：我想问我用一个button组件 但是不同页面要触发不同的方法，我应该怎么实现？

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#377]
![image](https://cloud.githubusercontent.com/assets/13248613/19796671/a70faf42-9d18-11e6-94df-868170a27ed7.png)
我不用mt-button改为用原生button的就可以emit

**Comment by JounQin** [comment]
`v-on:click.native`?

**Comment by QingWei-Li** [comment]
楼上 + 1
