### ISSUE TITLE
Switch 组件不能以'@change="event"'形式绑定change 事件

### ISSUE THREAD

**Issue by allenou** [ElemeFE/mint-ui#385]
### Mint UI version
2.0.2
### Device model
Chrome

not working：

``<mt-switch v-model="isSafeModel" @change="safeMode"></mt-switch>``

not working：

``<mt-switch v-model="isSafeModel" :change="safeMode"></mt-switch>``

working：

``<mt-switch v-model="isSafeModel" :change="safeMode()"></mt-switch>``

但是这样绑定会立即执行，所以当我根据 `isSafaModel` 的状态弹出提示时，就会一载入页面就弹出提示了。

**Comment by QingWei-Li** [comment]
请更新到 2.0.4

**Comment by allenou** [comment]
已解决，感谢:)
