### ISSUE TITLE
search 如何让点击item触发事件后，进行一下操作？

### ISSUE THREAD

**Issue by varrant** [ElemeFE/mint-ui#386]
```
<div class="page-search">
    <mt-search v-model="value" :placeholder="placeholder" ref="search">
      <mt-cell v-for="item in filterResult" :title="item" @click.native="searchMission(item)"></mt-cell>
    </mt-search>
  </div>
```

1.执行搜索，搜索框的内容和item内容一致，但是没能绑定在一起。 
2.我想把search-list给隐藏了，并且进行搜索。
how？

**Comment by QingWei-Li** [comment]
你到底用的是 1 还是 2？
我怎么看到你有 1 又有 2 的语法

**Comment by varrant** [comment]
<div class="page-search">
        <mt-search v-model="value" :result="filterResult" :placeholder="placeholder">
          <mt-cell v-for="item in filterResult" :title="item" @click.native="searchMission(item)"></mt-cell>
        </mt-search>
      </div>

**Comment by varrant** [comment]
<div class="page-search">
        <mt-search v-model="value" :result="filterResult" :placeholder="placeholder">
          <mt-cell v-for="item in filterResult" :title="item" @click.native="searchMission(item)"></mt-cell>
        </mt-search>
      </div>

**Comment by varrant** [comment]
我把语法改了一下，我是参考你的search 源码写的。

**Comment by varrant** [comment]
我现在想点击选择某个cell中的item之后。进行搜索，希望搜索框的名字能够和选择item中的名字一致，并且之后隐藏其中search-list。

**Comment by QingWei-Li** [comment]
没看懂 给个在线 demo 吧

**Comment by varrant** [comment]
看了你写的源码，currentValue为空的时候，不显示mint-search-list 这个div，对吧？

**Comment by QingWei-Li** [comment]
是的

**Comment by varrant** [comment]
但是，我强制this.value = ''的时候，这个div还显示着。

**Comment by varrant** [comment]
<mt-search v-model="projectValue" :placeholder="placeholder" ref="search">
          <mt-cell v-for="item in filterResult" :title="item" @click.native="searchMission(item)" ref="test"></mt-cell>
</mt-search>

js部分
this.$refs.search.$data.currentValue = '';
this.$refs.search.$data.visible = false;

解决了这个问题
