### ISSUE TITLE
pull down 高度问题

### ISSUE THREAD

**Issue by varrant** [ElemeFE/mint-ui#387]
当只有一条数据的时候，pull down 下拉，会隐藏数据。不知道遇到过没？

**Comment by Leopoldthecoder** [comment]
`div.mint-loadmore` 是由内部元素撑高的，并且有 `overflow-hidden` 属性。给它赋予一个具体的高度值就可以解决。

**Comment by varrant** [comment]
如何隐藏箭头呢？

**Comment by varrant** [comment]
还有下拉的时候，不流畅，只能一点一点下拉，是什么问题呢？
