### ISSUE TITLE
页面切换时，Indicator过早关闭

### ISSUE THREAD

**Issue by caikeal** [ElemeFE/mint-ui#390]
### Mint UI version
v1.0.1

### Vue related
vue:1.0.28，vue-router:0.7.13

### Device model
all

### Reproduction Link
https://github.com/caikeal/demo-for-mintui.git

### What is actually happening?
在含有2个Indicator组件的页面切换时，组件过早被关闭

**Comment by Leopoldthecoder** [comment]
Fixed in #391
