### ISSUE TITLE
模板可以正确引入但没样式

### ISSUE THREAD

**Issue by MichelleMM** [ElemeFE/mint-ui#404]
为什么生成的页面中却没有样式呢？
代码如下：
![image](https://cloud.githubusercontent.com/assets/19641718/19885446/9359ae6e-a059-11e6-8f34-eaba8b3e06ce.png)
webpack：（ loader部分）
![image](https://cloud.githubusercontent.com/assets/19641718/19914533/526a41ec-a0e6-11e6-8a9b-262fbdc7b6f3.png)

求解，谢谢

**Comment by Leopoldthecoder** [comment]
有使用 babel-plugin-component 吗？没有的话需要手动引入样式文件。具体查看：http://mint-ui.github.io/docs/#!/zh-cn2/quickstart

**Comment by MichelleMM** [comment]
已经解决了，谢谢
