### ISSUE TITLE
cell 组件在title和value的内容较长是布局乱

### ISSUE THREAD

**Issue by bigrats** [ElemeFE/mint-ui#411]
当cell组件的value文字长时，布局效果如下：
![image](https://cloud.githubusercontent.com/assets/3138644/19930097/d175a548-a141-11e6-81be-0b0cbcbe663f.png)

建议参考framework7的布局，title和value分别设置max-width为30%,70%，以及text-overflow:ellipsis
![image](https://cloud.githubusercontent.com/assets/3138644/19930168/2003a16a-a142-11e6-8041-151a05cfa96d.png)

![image](https://cloud.githubusercontent.com/assets/3138644/19930180/2c950b76-a142-11e6-86f9-ff0b1bd9ad97.png)

**Comment by QingWei-Li** [comment]
这个建议自己控制样式，cell 有可能会用在多行内容的情况
