### ISSUE TITLE
DatetimePicker bug

### ISSUE THREAD

**Issue by alekoshen712** [ElemeFE/mint-ui#413]
在日期组件中若设置了endData 会出现月份少了的情况
![image](https://cloud.githubusercontent.com/assets/19506220/19954075/bacfff50-a1af-11e6-9719-35a895daf138.png)
回到之前的年份后
![image](https://cloud.githubusercontent.com/assets/19506220/19954085/ce79e61a-a1af-11e6-9087-3c5635c7b9be.png)
12 月没有了
![image](https://cloud.githubusercontent.com/assets/19506220/19954086/d658cf72-a1af-11e6-92e5-247980d53529.png)
在绑定了model后不会出现上述bug,但是会出现明显的抖动和闪烁

mint-ui版本:2.0.0-rc.2
vue版本:2.0.1

**Comment by Leopoldthecoder** [comment]
请把 mint-ui 升级至 2.0.4
