### ISSUE TITLE
安卓系统中Cell Swipe 点击删除后，弹出选项中，点击确定没反应，

### ISSUE THREAD

**Issue by gao-xiang** [ElemeFE/mint-ui#415]
而且各种弹出类的功能，点击后感觉有卡顿，从中心位置一小块一卡后弹出成一个大的，感觉不是很流畅

以上是在官方演示中感受到的。

**Comment by QingWei-Li** [comment]
官网的删除按钮时假的，不流畅的问题还在找解决方法
