### ISSUE TITLE
Cell Swipe 点击cell时跳转路由，滑动右边菜单时是删除，但现在删除了之后而且跳转页面

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#420]
我有个功能，点击cell时跳转路由，滑动右边菜单时是删除，但现在是删除了之后而且跳转
1.我加了is-link to='xxxx'都好像无法跳转页面，而是弹出右边的菜单。
2.（弱弱问一句）我点击右边的菜单怎么阻止冒泡
3.官方例子这段有什么用？
![image](https://cloud.githubusercontent.com/assets/13248613/20026976/ef13e414-a341-11e6-8c4a-5573752cfb65.png)

**Comment by QingWei-Li** [comment]
请给个复现 demo
