### ISSUE TITLE
lazyload加载失败时能显示错误图片？

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#421]

**Comment by ringcrl** [comment]
不是一件事情，不过就想Mark一下，lazyload让我有点苦恼，电脑上一切正常使用。

手机上lazyload图片多的时候，100来张，有时候中间一张加载不出来，（原因未知），后面的都加载不出来了，还比较难复现这场景，基本情况都是正常使用的

**Comment by galenyuan** [comment]
lazyload相关可去https://github.com/hilongjw/vue-lazyload提issue
