### ISSUE TITLE
vue 组件化开发的时候在 mutation 怎么访问到refs

### ISSUE THREAD

**Issue by ac51300696** [ElemeFE/mint-ui#424]
[types.ADD_TO_LIST] ( state, { indexlist } ) {
    state.list = state.list.concat(indexlist.list)
    state.allLoaded = indexlist.allLoaded
    this.$refs.loadmore.onBottomLoaded(id);
  },
这是个mutations
在这里应该怎么访问到vue对象

**Comment by juyod** [comment]
mutations 是vuex操作数据的方法，不建议在这里访问vue对象，建议在上一层，action访问。

**Comment by ac51300696** [comment]
我加了vuex,怎么在action里面触发this.$refs.loadmore.onBottomLoaded(indexlist);
