### ISSUE TITLE
Cell中跳转，在router设置base的情况下，会append多一个base的路径

### ISSUE THREAD

**Issue by js5323** [ElemeFE/mint-ui#425]
如router设置了base：view，
cell配置 to=“/order/index”
生成a的href为 “/view/order/index”
但是点击跳转的地址变成 /view/view/order/index

**Comment by QingWei-Li** [comment]
cell 的 to 并能当作真正的 router-link 使用，只是模仿了一些简单的行为。简直将 router-link 放在 cell 内使用

```html
<mt-cell title="标题文字" is-link value="带链接">
  <router-link to="cell">链接地址</router-link>
</mt-cell>
```
