### ISSUE TITLE
亲。文档是不是挂了啊

### ISSUE THREAD

**Issue by y-xin** [ElemeFE/mint-ui#431]
这两地址访问不了， title 都加载出来了，就是什么都没有
http://mint-ui.github.io/
http://mint-ui.github.io/docs/

**Comment by QingWei-Li** [comment]
是你网络不好吧 亲

**Comment by theseawolves** [comment]
建立把链接都默认为 https ，ubuntu chrome无法访问 http://mint-ui.github.io/，需要改成https://mint-ui.github.io/
