### ISSUE TITLE
为什么组件标签名字是<mt-cell>，而渲染出来的class名字是.mint-cell

### ISSUE THREAD

**Issue by ringcrl** [ElemeFE/mint-ui#432]
额，就是不太理解这么设计的用意，有时候需要微调一下样式，还要去看看这个元素渲染出来的class叫什么。。。

额，这是个比较无聊的问题，嫌我烦直接close掉吧。。。

**Comment by QingWei-Li** [comment]
没啥用意，反正就是为了加个命名空间，已经这样写了再改就不好了。

**Comment by ringcrl** [comment]
好的哦 ，记住就好了，其实规律性挺强的~

还有，在另外那个issue，点击全屏大图预览的代码已经贴着了，真的能用的噢，就是不太知道怎么封装成符合mint-ui的组件~~~

**Comment by QingWei-Li** [comment]
通过 npm run new 创建新组件
