### ISSUE TITLE
请问mint-ui如何实现省市级联动选择，我看了官方文档只有省市联动

### ISSUE THREAD

**Issue by yb707893334** [ElemeFE/mint-ui#433]
请问mint-ui如何实现省市级联动选择，我看了官方文档只有省市联动
<mt-picker :slots="addressSlots" @change="onAddressChange" :visible-item-count="5"></mt-picker>

**Comment by Leopoldthecoder** [comment]
你是指省市区三级联动？同样的思路就可以。
