### ISSUE TITLE
结合vuex的时候没有把this传递过来不能调用其对应的方法

### ISSUE THREAD

**Issue by ac51300696** [ElemeFE/mint-ui#437]
比如在案例中的pull-up组件里面的example里

    loadBottom(id) {
        setTimeout(() => {
          let lastValue = this.list[this.list.length - 1];
          if (lastValue < 300) {
            for (let i = 1; i <= 10; i++) {
              this.list.push(lastValue + i);
            }
          } else {
            this.allLoaded = true;
          }
          this.$refs.loadmore.onBottomLoaded(id);
        }, 1500);
      }

把他改成vue的大型项目各个文件分离模式的时候
在action里如
export const getList = ({ commit },indexlist) => {
  index.getArticle((indexlist) => {
    commit(types.ADD_TO_LIST, { indexlist : indexlist })
    
  },indexlist)
this.$refs.loadmore.onBottomLoaded(indexlist);
  
}
 index.getArticle是写的一个增加数据的回调，
能获取到id，可是this对象没有传递过来，所以是不是在函数里添加传递一个this对象过来

**Comment by Leopoldthecoder** [comment]
`this.$refs.loadmore.onBottomLoaded(indexlist);` 里面的 `this` 其实是你使用了 `loadmore` 的那个页面或组件的实例，而不是 `loadmore` 实例本身。不知道你的场景里方不方便把页面实例传给 `getList` 方法？

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
<mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， <mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore">
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
额。用的是你们官方的案例， 
mt-loadmore :bottom-method="getList" @bottom-status-change="handleBottomChange" :bottom-all-loaded="indexlist.allLoaded" ref="loadmore"
绑定的是这个 :bottom-method="getList" 不知道要怎么改呢，源码里顺便问下=-=没找到bottom-method这个事件啊

**Comment by ac51300696** [comment]
@Leopoldthecoder
