### ISSUE TITLE
给<mt-popup/>添加style属性会导致默认状态弹窗就显示的BUG

### ISSUE THREAD

**Issue by tyrion-yu** [ElemeFE/mint-ui#442]
### Mint UI version
2.0.2

### What is actually happening?

下面的写法会导致弹窗默认就显示着，即使 value 为 false。

``` html
<mt-popup v-model="popupRules" style="top:45%;"></mt-popup>
```

**Comment by Leopoldthecoder** [comment]
看起来是 Vue 的问题，已经给官方提了 issue：https://github.com/vuejs/vue/issues/4192

暂时先不要写内联样式吧。

**Comment by Leopoldthecoder** [comment]
Vue 那边已经修了，等他们的下个版本吧。

**Comment by ringcrl** [comment]
@Leopoldthecoder 

好专业的 issue ！！
