### ISSUE TITLE
关于 Field的校验问题

### ISSUE THREAD

**Issue by Bing-Xia** [ElemeFE/mint-ui#448]
### Mint UI version
2.0.4
### Device model

Wechat webview
### What is Expected?
实时校验输入是否合法，比如设置的 type="email", 在未输入完整时 state="error"，输入合法时 state="success"
### What is actually happening?
比如设置的 mt-field type="email", 在输入的过程中并没有出发email地址验证，只能手动的通过 watch 去监视输入值，然后改变 mt-field 的 state 值从而体现输入的合法性。

**Comment by QingWei-Li** [comment]
对啊 本来就没有集成校验功能

**Comment by BigKongfuPanda** [comment]
请问有计划集成一下表单校验的功能吗？？
