### ISSUE TITLE
picker组件中的slots的备选数组，不支持动态变换吗？

### ISSUE THREAD

**Issue by Jabbar2010** [ElemeFE/mint-ui#449]
![image](https://cloud.githubusercontent.com/assets/11782524/20333136/8952d66e-abeb-11e6-94d0-bdbfde09e50b.png)

如图所示，动态设置的values，在change事件中是这个样子。。。

**Comment by Leopoldthecoder** [comment]
动态改变备选值数组需要使用 `setSlotValues` 方法。

**Comment by Jabbar2010** [comment]
@Leopoldthecoder 你好，按照你说的，那么这个picker对象怎么获取呢？目前我只知道在onDataChange事件中的回调里面有picker对象，我可能需要全局的Picker对象来setSlotValues

**Comment by Leopoldthecoder** [comment]
```html
<mt-picker ref="picker">
...
</mt-picker>
```

这样就可以获取到 Picker 实例：
```javascript
this.$refs.picker.setSlotValues(...)
```

**Comment by Jabbar2010** [comment]
@Leopoldthecoder 非常感谢，可以了~

**Comment by roy-yi** [comment]
你好，请问，你获取的到的values[0]是不是undefined?
