### ISSUE TITLE
<mt-tabbar>的item选择改变后有什么事件可以捕获？

### ISSUE THREAD

**Issue by hezhongfeng** [ElemeFE/mint-ui#450]
我的需求是这样的
我从别的路由切换到tabbar的时候刚才选择的item已经改变，会变为默认的那个
所以现在想通过vuex来读取选择的item 赋给<mt-tabbar>的value，要满足两个功能
1、得从vuex中读取初始的item
2、当我选择变化后得去更新vuex中的值
所以有了题目的问题，我怎么才能知道selected item改变了？

**Comment by hezhongfeng** [comment]
忽然想起来
我在组件创建和销毁的时候分别对 `selected` 进行赋值和取值
应该是比较好的做法

**Comment by hezhongfeng** [comment]
现在的解决办法是利用'created''beforeDestroy'这俩函数在组件创建和销毁的时候进行赋值和读取

**Comment by philasting** [comment]
在点击的时候vuex的值怎么去改变？会报错的。
我也遇到这个问题，试过localStorage去保存，然后发现软件退出重新进的时候，会读取保存的值，而不能默认值。感觉vuex是最好的方法，但是点击赋值会报错，你是怎么解决的？
