### ISSUE TITLE
win下npm run dev报错

### ISSUE THREAD

**Issue by hetianhe** [ElemeFE/mint-ui#451]
$ npm run dev

> mint-ui@2.0.5 dev D:\work\test\mint-ui
> npm run bootstrap && npm run build:entry && cooking watch -c build/cooking.dem                       o.js -p

> mint-ui@2.0.5 bootstrap D:\work\test\mint-ui
> npm i

npm WARN skippingAction Module is inside a symlinked module: not running add nan                       @2.4.0 node_modules\nan
npm WARN 2webpack2@0.4.0 requires a peer of webpack@^2.1.0-beta.24 but none was                        installed.
npm WARN buble-loader@0.3.2 requires a peer of buble@^0.14.0 but none was installed.
npm WARN cooking@1.2.0 requires a peer of babel-core@^6.0.0 but none was installed.
npm WARN cooking@1.2.0 requires a peer of babel-loader@^6.0.0 but none was insta                       lled.
npm WARN cooking@1.2.0 requires a peer of css-loader@^0.24.0 but none was installed.
npm WARN cooking@1.2.0 requires a peer of postcss-loader@^1.0.0 but none was ins                       talled.
npm WARN 2webpack2@0.4.0 requires a peer of webpack@^2.1.0-beta.24 but none was                        installed.
npm WARN cooking-buble@0.1.3 requires a peer of webpack@^2.0.0-beta but none was                        installed.
npm WARN buble-loader@0.3.2 requires a peer of buble@^0.14.0 but none was installed.

> mint-ui@2.0.5 build:entry D:\work\test\mint-ui
> node build/bin/build-entry

[build entry] DONE: D:\work\test\mint-ui\src\index.js

[cooking] - Loaded success: vue2
[cooking] - Loaded success: lint
[cooking] - Loaded success: saladcss
[cooking] - Loaded success: buble

[cooking] - Loading server...
[cooking] - Listening at http://192.168.253.1:8790
Child html-webpack-plugin for "index.html":

**Comment by QingWei-Li** [comment]
那些是警告，不用理会
