### ISSUE TITLE
checklist for vue2.0.6 error

### ISSUE THREAD

**Issue by SoyMeng** [ElemeFE/mint-ui#454]
### Mint UI version
2.0.5
### What is Expected?

For Vue 2.0.6
TypeError: Cannot read property 'length' of undefined

### What is actually happening?
use simple demo
`<mt-checklist
        title="checkbox list"
        v-model="value"
        :options="['选项A', '选项B', '选项C']">
 </mt-checklist>`

**Comment by Jie-OY** [comment]
@SoyMeng 你好，有找到是为什么么？
