### ISSUE TITLE
vue-infinite-scroll无限触发loadmore方法

### ISSUE THREAD

**Issue by andylei18** [ElemeFE/mint-ui#456]
每次请求完，回调里的数组list为空的时候 就会触发无限加载方法

**Comment by xyDiva** [comment]
之前写这个功能的时候看文档疏忽有遇到无限触发loadmore方法的问题，是因为**没有设置容器高度**。**loadMore组件初始化会自动检测容器高度，如果没有撑满会自动调取bottom-method直到撑满或者人为阻止。**
不太确定是不是你需要的，暂提个可能的思路。

**Comment by Leopoldthecoder** [comment]
@andylei18 返回的数组为空的时候，设置 `infinite-scroll-disabled` 为 `true` 似乎可以解决。

**Comment by andylei18** [comment]
这样的话 你不能触发 再次加载啦？这样流程就断了

**Comment by andylei18** [comment]
@Leopoldthecoder 那这样的话，你再次滚动就触发不了。。。。流程就断了

**Comment by andylei18** [comment]
@xyDiva 列表容易高度我有计算，你说的bottom-method，autoFill:false  API里也没有，vue-infinite-scroll 那个issues里 N多 和我一样情况的人

**Comment by watership** [comment]
如果返回的数组为空的时候，确实会引发无限加载，而且设置 `infinite-scroll-disabled` 为` true`，没有用处，还是在一直加载。

**Comment by YanwuSenlu** [comment]
我这还是会无限加载，这个问题解决了么？

**Comment by wsqy182** [comment]
我这里已经解决了，这个东西完全可以人工阻止。写几个判断判断是否需要加载

**Comment by th720309** [comment]
问题怎么解决的？

**Comment by wsqy182** [comment]
@th720309 忘记了，好久以前了，代码在家里的固态硬盘上。

**Comment by wsqy182** [comment]
@th720309 那个loadMore方法不是会调用很多次么。在 第一次调用的时候，就要拿到数据的总数(total)。然后之后每次调用loadMore的时候，在loadMore里面判断，如果当前vue组件里面的list 数据 和 total(总数)相等，说明数据已经全部加载完了，就在前端直接return，不发ajax去后台了 . 这样不管这个loadMore调用多少次，都只有第一次loadMore的数据。不要质疑这个解决方案。你可以在每次loadMore的时候都更新这个total值

**Comment by androidxu** [comment]
> @th720309 大概意思就loadMore方法 里面判断数据有没有加载完，数据全部加载完了，loadMore就直接返回，不在发ajax请求了。

试了很多方法，无奈只能这样处理了...
在极端的情况下，infinite-scroll-disabled这个根本没什么用

**Comment by dinglittle** [comment]
这个无限滚动真是用的 有点无语 , 默认请求两次 是什么鬼
