### ISSUE TITLE
我想问mint-ui 图片懒加载 假如image type=error的时候怎么换默认图片

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#457]
![image](https://cloud.githubusercontent.com/assets/13248613/20385878/306815be-acf4-11e6-951a-bfc109e16d9f.png)
![image](https://cloud.githubusercontent.com/assets/13248613/20385879/32db568a-acf4-11e6-8f63-16dc0b8d9571.png)

**Comment by Leopoldthecoder** [comment]
目前没有这个接口。
Mint 内置的是 [vue-lazyload](https://github.com/hilongjw/vue-lazyload)，可以考虑直接使用这个插件，它是提供了相关接口的。
