### ISSUE TITLE
按组件引入报错

### ISSUE THREAD

**Issue by huangzhenxian** [ElemeFE/mint-ui#459]
![image](https://cloud.githubusercontent.com/assets/8416974/20421171/419cb070-ad9d-11e6-891f-52b0a06da2c6.png)
 vue2   mint-ui最新版本
我用全局引入 Vue.use(mint-ui)就没事
分到各个组件部分引入就这样  不知道从哪里下手  
![image](https://cloud.githubusercontent.com/assets/8416974/20421304/ec9f0af4-ad9d-11e6-82ca-f5fd8cad0632.png)
loader 的设置 
我是用vue-cli搭的手脚架

**Comment by huangzhenxian** [comment]
![image](https://cloud.githubusercontent.com/assets/8416974/20421349/45a1800a-ad9e-11e6-8f4e-6cb30079f624.png)
main 页面  

![image](https://cloud.githubusercontent.com/assets/8416974/20421363/57876c80-ad9e-11e6-8d55-a16acc26908b.png)
到这里总是失败

**Comment by godmeng** [comment]
@huangzhenxian  你的问题解决了吗，我全部引入的话会出现这个错误.

**Comment by huangzhenxian** [comment]
@godmeng  css-loader 在babel去掉  单组件引入目前我还是没成功的  在首页单组件引入就行 路由导入的vue页面就不行了  我感觉是路由的原因了  有时间再研究源码
