### ISSUE TITLE
swipe 在手动左右滑动时，图片会有闪现情况

### ISSUE THREAD

**Issue by flftfqwxf** [ElemeFE/mint-ui#462]
### Mint UI version
2.0.5
### Device model

MAC chrome 54  / iOS 1011 safari / 微信
### Reproduction Link
> <mt-swipe v-if="swipeList.length" id="swipe"   :auto="4000">
            <mt-swipe-item class="black" v-for="item in swipeList">
                <router-link :to="{path:'articles/'+item.target_id}">
                    <img :src="item.img" alt="">
                </router-link>
            </mt-swipe-item>
        </mt-swipe>

### What is actually happening?
swipe 在手动左右滑动时，图片会有闪现情况
![111](https://cloud.githubusercontent.com/assets/5468564/20476402/c0f5c562-b00b-11e6-8095-98c2374873ad.png)

**Comment by qcdys** [comment]
解决了么

**Comment by flftfqwxf** [comment]
@qcdys 感觉没人维护了，一个多月 还是没人理

**Comment by feifanyajun** [comment]
作者很忙啊看来这个ui库活跃不起来了

**Comment by flftfqwxf** [comment]
@qcdys 问题找到了，原因是swiper内的图片大小没有设置宽度为100%，图片大小超过了swiper容器大小，而swiper在滑动时，会将其最后一个元素设置为block，图片超出了容器就显示出来了
解决办法就是将图片宽设为100%就OK了

**Comment by Say-Hello** [comment]
我的也有闪动，不知道，width是百分百的，其他人还遇到这样的情况了吗
