### ISSUE TITLE
想问一下用淘宝lib-flexible库的时候mint-ui组件样式都变得很小了~该怎么解决

### ISSUE THREAD

**Issue by ChangeZhang** [ElemeFE/mint-ui#463]
想问一下用淘宝lib-flexible库的时候mint-ui组件样式都变得很小了~该怎么解决!!!!!!!

**Comment by PriestsHsiung** [comment]
同问这个问题，是要手动的调整rem值么？谢谢

**Comment by deepcoldy** [comment]
mint不是自带了rem么，为什么还用淘宝的

**Comment by zhy6421867** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
这段加上去,lib-flexible就会原来的缩放来进行设置根字体大小.

**Comment by zhy6421867** [comment]
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />`

**Comment by u3u** [comment]
@ChangeZhang @PriestsHsiung 
可以使用 `px2rem-loader` 转化单位：https://www.npmjs.com/package/px2rem-loader
``` javascript
loaders: [{ test: /\.css$/, loader: 'style!css!px2rem?remUnit=37.5&remPrecision=8&baseDpr=1' }]
```

不过我发现有些组建有些地方没有设置 `font-size` 所以转换无效
比如说 `MessageBox` 组件的 `.mint-msgbox-btn` 没有设置 `font-size`

**Comment by ChangeZhang** [comment]
@u3u 您好，我想请问下您这种结合vue-cli应该怎么配置呢，谢谢！

**Comment by u3u** [comment]
@ChangeZhang 

安装 [`postcss-px2rem`](https://www.npmjs.com/package/postcss-px2rem) 包
``` sh
cnpm i postcss-px2rem -D
```
然后在 `/build/vue-loader.conf.js` 文件中配置一下

![](http://p1.bqimg.com/549484/66840a8838f51785.png)

不过不建议使用 因为 `mint-ui` 本身没有考虑 `rem` 和 `dpr`
除非你写死 `meta` 如果自适应 `dpr` 的话 有些组件会有问题
比如说下拉刷新和 `picker` 是需要根据高度判断的 但是代码中的高度像素是写死的 并不是获取元素的高度
这是我遇到的坑： https://github.com/mint-ui/mint-loadmore/issues/23

**Comment by wx85745997** [comment]
@u3u  你好 我想问一下 你这样写的话 750设计稿上1px算到css里面应该写多少px

**Comment by u3u** [comment]
@wx85745997 
直接写 `1px` 就好了 会自动转化成 `rem`
以 `iPhone 6` 为例 `dpr=2` 如果不写死 `viewport ` 页面会缩放 `0.5` 倍
这时候页面的实际大小为 `750px * 1334px`

**Comment by otaku1951** [comment]
@u3u px2rem-loader的配置加在vue脚手架工程的那个文件里？好像没办法把mint-ui转成rem

**Comment by Luolei1992** [comment]
用了flexble.js再用其他组件库（antd-mobile）就会缩小，具体要怎么解决???

**Comment by lettgers** [comment]
怎么解决啊

**Comment by ytianzaishui** [comment]
> 怎么解决啊

所以最好你的解决方法是什么
