### ISSUE TITLE
ver 2.x 中 infinite-scroll 指令在V-IF时产生的问题

### ISSUE THREAD

**Issue by zppro** [ElemeFE/mint-ui#469]
ver 2.x 中 infinite-scroll 指令：

<template lang="jade">
.hot-list(v-infinite-scroll="appendHotList", infinite-scroll-disabled="appendHotDiabled", infinite-scroll-distance="infiniteScrollDistance", `v-if`="experiencesHot.length > 0" )
如上面的代码
使用v-if时 bind没有执行
但是在离开时，回去调用unbind

>  el[ctx].scrollEventTarget.removeEventListener('scroll', el[ctx].scrollListener);
这时
 el[ctx].scrollEventTarget = undefined 会报错
如果把`v-if` 换成`v-show`让dom元素生成就没有问题了
希望把这个BUG修复

**Comment by AlvinYuXT** [comment]
大致看了一下，感觉像是因为v-if是延迟处理的，所以在父组件mounted时候，infinite-scroll还没有开始compile，就兼听不到mounted事件，整个的bind也就不会执行。

**Comment by 617450941** [comment]
我的也有同样问题 v-if的时候 infinite-scroll 无法滚动 版本是2.2.2
