### ISSUE TITLE
cell-swipe的问题

### ISSUE THREAD

**Issue by nieyulin112** [ElemeFE/mint-ui#470]
大神们，cell-swipe这个插件，在安卓手机上，页面会有两层的效果，谢谢

**Comment by nieyulin112** [comment]
安卓机上有阴影的效果

**Comment by Leopoldthecoder** [comment]
请给出截图或者 demo

**Comment by Hootoo** [comment]
![16 11 29 0019_3](https://cloud.githubusercontent.com/assets/15854551/20676472/c502ee72-b5ca-11e6-98d0-b551573bb8cf.png)
应该是这样的问题。在一个页面中，最顶部的cellswipe是没有问题的，但是下面的都会出现右滑而text没有重绘，应该是css的问题。试了下安卓和pc浏览器都会这样。

**Comment by alexqdjay** [comment]
将position改为 relative就修复了，实测

**Comment by Hootoo** [comment]
哪个css的position，alex具体怎么做的？其实在pc浏览器上改变下设备大小或者随便改变css属性让它重绘一下就没问题了,

**Comment by alexqdjay** [comment]
mint-cell-wrapper 的

**Comment by galenyuan** [comment]
fixed in #685
