### ISSUE TITLE
Picker中的slots.values只支持字符串数组么，不能像select那样name,value分离么？

### ISSUE THREAD

**Issue by tofuxb** [ElemeFE/mint-ui#472]
在使用Picker的时候，发现slots中的values只支持['选项一', '选项二', ...]这种，我希望能支持[{ name: '选项一', value: 1 }, { name: '选项二', value: 2 }] 。这个需要应该挺大的，望解决，谢谢！

**Comment by Leopoldthecoder** [comment]
目前只支持字符串。如果是刚需，欢迎 PR。

**Comment by yezongyang** [comment]
+1

**Comment by realbasin** [comment]
+1
