### ISSUE TITLE
我想问你们radio的组件value值的问题

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#475]
![image](https://cloud.githubusercontent.com/assets/13248613/20637473/3564a22c-b3c4-11e6-807c-8b9ebe31fd98.png)
这里只能存string
![image](https://cloud.githubusercontent.com/assets/13248613/20637476/3de2a8cc-b3c4-11e6-9091-f5d216b9dc22.png)
但是这里又能有整个对象？

**Comment by Hubu** [comment]
如果option就是字符串就没有问题了

**Comment by galenyuan** [comment]
option为string时传option，option为object时传option.value

**Comment by RunningV** [comment]
options为对象时失效如下图：
![radio](https://cloud.githubusercontent.com/assets/14954266/24490120/b25551aa-1553-11e7-8bde-184c9c8c92e7.png)
我想为什么不能设计成一致的，像`picker`组件一样，可以指定`keyValue`,自定义循环数组的key？

**Comment by shimangdian** [comment]
why only String ?why not number?and i give him String, him told me get a Number...how to fix it?
