### ISSUE TITLE
index list左侧内容在iPhone 6s Safari里无法上下滑动

### ISSUE THREAD

**Issue by xiaozhu188** [ElemeFE/mint-ui#476]
右侧字母栏滑动正常

**Comment by galenyuan** [comment]
检查一下自己有没有设置 `overflow: hidden`,  index list 使用的是原生的滚动条

**Comment by lwyi188** [comment]
@galenyuan 你好，这个问题在iPhone6 微信里也存在，用UC，QQ浏览器则没有任何问题。 @xiaozhu188 问题后面怎么解决的呢。
