### ISSUE TITLE
Index List要做手机联系人，我想问我应该怎么分页还是不做分页比较好

### ISSUE THREAD

**Issue by hopkinson** [ElemeFE/mint-ui#477]
我用了mint-ui里的Index List做了手机联系人的功能，但是呢我想不懂应该怎么分页，这里涉及到拼音，人，如果没有拼音我还好办，但是现在多了拼音我就不知道怎么搞了，请问你们有什么好的建议，数据结构应该怎么样比较好？

**Comment by Leopoldthecoder** [comment]
此问题与 Mint UI 本身无关。
