### ISSUE TITLE
Swipe组件无法跳转链接

### ISSUE THREAD

**Issue by DullSky** [ElemeFE/mint-ui#482]
Swipe里面就算加了<a href="http://....">......</a>也不会跳转，加个<div @click>也没办法绑定到事件，轮播图点击跳转到某个链接应该是很常用的功能啊

**Comment by Leopoldthecoder** [comment]
请给出 Mint 和 Vue 的版本信息，以及代码片段。

**Comment by DullSky** [comment]
![image](https://cloud.githubusercontent.com/assets/15259698/20700117/53f55f90-b646-11e6-8ff8-3ab3663ee11e.png)
![image](https://cloud.githubusercontent.com/assets/15259698/20700124/5d735400-b646-11e6-9b62-cde08725a2a6.png)
![image](https://cloud.githubusercontent.com/assets/15259698/20700127/624b5f5e-b646-11e6-9f06-6a825592f93a.png)

**Comment by Leopoldthecoder** [comment]
可以跳转：https://jsfiddle.net/leopoldthecuber/w0h59ekt/
请检查是否受到其他代码的影响。
