### ISSUE TITLE
pick组件异步获取values，defaultIndex设置无效

### ISSUE THREAD

**Issue by JaneScript** [ElemeFE/mint-ui#483]
vue.js v2.0.5
mint-ui v2.0.5

运用picker组件时，如果选项是请求后台获取的，defaultIndex设置无效。。

**Comment by acmeid** [comment]
我也遇到了同样的问题。
你可以通过v-if 让picker组件在加载好选项之后再渲染，临时解决这个问题。比如：
`<mt-picker v-if="isLoad"></mt-picker>`
因为这个picker这个组件是在created处理默认值的，在改变defaultIndex之后，不会触发picker去更新默认值。这个逻辑需要优化。

**Comment by galenyuan** [comment]
可以通过 @acmeid 的方法解决，也欢迎提PR

**Comment by zhangxinxinWTB** [comment]
马克

**Comment by xiangcaozhu** [comment]
@acmeid 你好，我刚刚也遇到一个问题，使用axios数据加载到vuex后，需要数据的组件去mapGetters。问题：点击选项时候，弹出picker，默认defaultIndex失效，默认选择器没有被默认选中的效果！请教一下v-if渲染条件是"picker组件在加载好选项之后"，这个是怎么判断的？？

**Comment by acmeid** [comment]
@xiangcaozhu 不是很明白你的意思，v-if里面的条件就是你的数据已经到位

**Comment by galenyuan** [comment]
fixed in #673
