### ISSUE TITLE
picker组件-改变defaultIndex无法更新试图

### ISSUE THREAD

**Issue by JaneScript** [ElemeFE/mint-ui#486]
vue.js v2.0.5
mint-ui v2.0.5

或者除了change事件有没有方法 可以改变picker的选中值
如图，用户保存的是27-30，页面load进来，打开Picker可否直接选中27-30
![706894548765699964](https://cloud.githubusercontent.com/assets/2151253/20705092/9439fb04-b65c-11e6-8fd7-bc5b2d0a0fbb.jpg)

**Comment by Leopoldthecoder** [comment]
可以直接调用实例上的 setSlotValue 方法。

**Comment by JaneScript** [comment]
这是我的代码，请教我应该怎么调用setSlotValue
![111](https://cloud.githubusercontent.com/assets/2151253/20707138/4b9095a8-b665-11e6-97ca-403afbcd1a2a.jpg)
![222](https://cloud.githubusercontent.com/assets/2151253/20707141/518c710c-b665-11e6-85b5-799de7d026d8.jpg)
