### ISSUE TITLE
把router-link 放在 mt-tab-item的里面还是外面，其内部的 icon 都消失了

### ISSUE THREAD

**Issue by senyawang** [ElemeFE/mint-ui#489]
Vue 2.0
mint-ui 2.0

示例代码：
<mt-tabbar v-model="currentTab">
      <mt-tab-item id="外卖">
        <router-link to='home'>
          <img slot='icon' src="./assets/i-home@2x.png">
          外卖
        </router-link>

      </mt-tab-item>
      <mt-tab-item id="订单">
        <img slot="icon" src="./assets/i-home@2x.png">
        订单
      </mt-tab-item>
      <mt-tab-item id="发现">
        <img slot="icon" src="./assets/i-home@2x.png">
        发现
      </mt-tab-item>
      <mt-tab-item id="我的">
        <img slot="icon" src="./assets/i-home@2x.png">
        我的
      </mt-tab-item>
    </mt-tabbar>

无论是把router-link 放在 mt-tab-item的里面还是外面，其内部的 icon 都消失了，看最终生成的节点中，只有一个空的<div class="mint-tab-item-icon"></div>

**Comment by lixutao** [comment]
问题解决了吗？我也遇到这个问题了

**Comment by iqiuye** [comment]
问题没解决就关闭了，我也是醉了

**Comment by senyawang** [comment]
改道而行吧。。。
