### ISSUE TITLE
field插入自定义内容时，input的输入框输入内容溢出

### ISSUE THREAD

**Issue by PonyC** [ElemeFE/mint-ui#490]
![image](https://cloud.githubusercontent.com/assets/6700288/20799326/c322f7f6-b81c-11e6-8abb-61619f625130.png)

是不是应该把 mint-field-other 设成 position: relative 才对？

**Comment by PonyC** [comment]
是不是应该把 mint-field-other 设成 position: relative 才对？

**Comment by QingWei-Li** [comment]
PR welcome

**Comment by roy-yi** [comment]
Is this bug fixed or not?

**Comment by galenyuan** [comment]
fixed in #755
