### ISSUE TITLE
例子代码里的CSS写法需要哪个babel loader处理？

### ISSUE THREAD

**Issue by baryon** [ElemeFE/mint-ui#495]
将example里的代码拷贝到mint-ui-starter里修改了部分引用mint-ui的代码，例子可以跑起来了，但是一些css的是乱的，特别是下面这部分，如何修改webpack来正确处理呢？
```
  @component-namespace page {
    @component title {
      font-size: 20px;
      margin: 20px auto;
      text-align: center;
      display: block;
      line-height: 1;
    }

    @component part {
      margin-bottom: 15px;
    }
  }
```

webpack的配置文件是mint-ui-starter里的，没有修改。如何改才好？

**Comment by baryon** [comment]
这个style如何改成普通的写法？

**Comment by baryon** [comment]
我做了一个分叉，https://github.com/baryon/mint-ui-starter 希望可以帮助大家

**Comment by baryon** [comment]
使用postcss sarad的例子在这个分支 https://github.com/baryon/mint-ui-starter/tree/postcss
以后等有时间了学习一下postcss

**Comment by zbyztl** [comment]
> 我做了一个分叉，https://github.com/baryon/mint-ui-starter 希望可以帮助大家

哈哈哈，还是喜欢这个的，postcss 这个优点难搞，虽然跑起来了，移植难度有点大
