### ISSUE TITLE
Cell Swipe对TabContainer的支持不好呢

### ISSUE THREAD

**Issue by Array-Huang** [ElemeFE/mint-ui#499]
主要问题还是出在滑动按钮上，问题表现是这样的：

TabContainer有个默认打开的tab吧，在这个默认打开的tab里一切都是正常的。问题出现在，切换到其它tab的时候，就发现Cell Swipe的滑动按钮已经展示出来了，而且不受控制，还挡住文字的部分了

![qq 20161206225041](https://cloud.githubusercontent.com/assets/2235699/20929866/74ea3f3e-bc06-11e6-8801-8eefb5fb4c0b.jpg)

**Comment by galenyuan** [comment]
能提供复现demo或repository么？

**Comment by hehos** [comment]
这个问题解决了吗？
我有个demo可以重现这个问题。
