### ISSUE TITLE
[mt-picker] 能否按下toolbar 確認的同時，回傳所選值

### ISSUE THREAD

**Issue by red010182** [ElemeFE/mint-ui#507]
### Mint UI version
2.0.5

如題，既然picker都提供toolbar了，那麼選擇完成之時，為何不能回傳所選值呢？

現在的用法需要自行監聽@change才能得到結果，甚至如果user沒有滾動picker直接按下toolbar確定，@change還不會被觸發，需要另外處理

能否提供一個簡便的方式：按下確定後直接回傳所選值？

**Comment by Leopoldthecoder** [comment]
目前的设计，toolbar 里面的内容和行为都是自定义的，可能不太好侵入。不过你的问题仍然可以解决：
```html
<mt-picker :slots="someSlots" show-toolbar ref="picker">
  <mt-button @click="handleConfirm">确认</mt-button>
</mt-picker>
```

```javascript
handleConfirm() {
  console.log(this.$refs.picker.getValues())
}
```
