### ISSUE TITLE
toast 弹出层做成单例模式会不会更好，要不然几秒内连续出现几个toast就会显得很奇怪。

### ISSUE THREAD

**Issue by TongchengQiu** [ElemeFE/mint-ui#51]

**Comment by flybbjcs70** [comment]
那就不是toast了。

**Comment by furybean** [comment]
如果需要阻塞用户操作，Indicator 更适合你的需求。

**Comment by ChangeZhang** [comment]
意思是能不能改成在第二个toast出来之前，把前面的toast清掉。。。。要不然几秒内连续出现几个toast就会显得很奇怪。。。。。。。。

**Comment by zhao-ping** [comment]
能不能追加一个方法，可以清掉之前的所有toast

**Comment by yaoazhen** [comment]
@zhao-ping 同样需要一个方法清除之前所有的toast
