### ISSUE TITLE
mt-tab-container中的组件无法响应touchmove事件

### ISSUE THREAD

**Issue by caohongtao** [ElemeFE/mint-ui#510]
### Mint UI version
2.0.5

### Device model
任何"移动端设备"

### Reproduction Link
https://jsfiddle.net/x9z6xoh4/

### What is Expected?
我需要实现如下菜单功能。但是`mt-tab-container`的drag事件处理貌似会禁止掉dom的scroll功能。
![image](https://cloud.githubusercontent.com/assets/7335304/21102487/68d7e996-c0b9-11e6-8464-40dd4b8bf27f.png)

### What is actually happening?
必须在移动端设备上会发生。
表现为pc上的响应式设计选择手机时，鼠标无法通过拖动来使菜单条滚动。
表现为手机真机上，无法通过手指拖动来使菜单条滚动。
另外，我把此菜单组件移到`mt-tab-container`之外，scroll左右滚动即可生效。
https://jsfiddle.net/7xdy0awe/

**Comment by galenyuan** [comment]
fixed in https://github.com/ElemeFE/mint-ui/pull/606
