### ISSUE TITLE
微信webview或手机QQ浏览器使用palette-button有bug

### ISSUE THREAD

**Issue by lesd121** [ElemeFE/mint-ui#514]
我是使用官方demo
android5.1，微信webview或手机QQ浏览器使用palette-button时候，点击button能展开子项，有部分子项不能展开，但不能收回！
ios10 ，微信webview能展开收回，但有部分子项不能展开！

**Comment by Leungkingman** [comment]
我也遇到这个问题了，请问您解决了吗？

**Comment by lesd121** [comment]
@Leungkingman 先不使用了，用其他展示方式代替

**Comment by galenyuan** [comment]
fixed in #595
