### ISSUE TITLE
checklist显示不出来

### ISSUE THREAD

**Issue by csyangwen** [ElemeFE/mint-ui#515]
### Mint UI version
2.0.5
### Device model

webkit
### Reproduction Link

·<mt-checklist
  title="复选框列表"
  v-model="value"
  :options="['选项A', '选项B', '选项C']">
</mt-checklist>·
### What is Expected?
正常显示出来
### What is actually happening?
Error when rendering component <mt-checklist>Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by Jie-OY** [comment]
@csyangwen 你好，有找到是为什么么？
