### ISSUE TITLE
为什么indicator关闭,要延时400ms? 是因为transition吗?

### ISSUE THREAD

**Issue by LouisaNikita** [ElemeFE/mint-ui#519]
为什么indicator关闭,要延时400ms ? 直接置visible为false不行吗?

`

         close() {
              if (instance) {
                   instance.visible = false;
                   timer = setTimeout(() => {
                        if (instance.$el) {
                            instance.$el.style.display = 'none';
                         }
                   }, 400);
              }
         }
`

是因为这个吗?
`
transition: opacity .2s linear;
`

**Comment by Leopoldthecoder** [comment]
这段代码确实冗余了，已经在 #528 中去除。
