### ISSUE TITLE
建议参考其他移动端 UI 组件库，新增更多组件

### ISSUE THREAD

**Issue by Loyalsoldier** [ElemeFE/mint-ui#52]
给几个参考：

Hui：http://git.oschina.net/winu.net/Hui  （可能打不开，需要在 Git@OSChina 上搜“Hui”）
AUI：http://www.auicss.com

还有阿里巴巴的 SUI

**Comment by furybean** [comment]
感谢建议，mint-ui 暂时只实现了我们自己常见的一些场景的组件。
我们更倾向于听到具体的功能的反馈：比如你可以提出某个你认为非常常用，但是我们并没有实现的组件。

**Comment by playniuniu** [comment]
想要一个聊天界面的组件，类似 framework7 的 messages组件 
http://framework7.io/docs/messages.html，不知道难度大不？

**Comment by Loyalsoldier** [comment]
@furybean 
这个就要看项目定位啦，只是想提供最基础最简单的元素组合，如 HTML5 一样提供一个最基础的标准，还是说也为开发者提高效率着想，甚至提供一些页面模板……定位不同，程度不一。

我上面提到的 AUI 和 Hui 是 APICloud 这个混合开发平台的一些开发者开源的。既然是混合开发平台，那平台的用户肯定是想要超高效率完成工作的，所以 Hui 甚至会有像登录页、注册页的页面模板、聊天界面的模板、通讯录界面的模板等等……例如登录/注册、聊天、通讯录、九宫格、列表等等都是最最常用的东西

**Comment by Loyalsoldier** [comment]
BTW, 整个项目的完成度很高，无论是设计，还是体验都很棒。所以个人而言，希望这个项目能为我做更多的事情（这个纯粹是私心）

**Comment by godfox2012** [comment]
@furybean 有考虑出一个侧边栏菜单吗，android app那样的侧边滑动导航菜单

**Comment by boboxiao** [comment]
你好，有非vue版本的么？

**Comment by QingWei-Li** [comment]
@boboxiao 
所有组件都是基于 Vue 开发的，不过你可以直接扒代码用。

**Comment by boboxiao** [comment]
@QingWei-Li  后续有考虑剥离 Vue 不啊？

**Comment by QingWei-Li** [comment]
@boboxiao 

目前没有计划

**Comment by yuu2lee4** [comment]
什么时候能用在vue2上呢

**Comment by cdll** [comment]
前排围观建议～

**Comment by gjx870327** [comment]
如果不通过nodejs可以直接在页面引用吗

**Comment by QingWei-Li** [comment]
@gjx870327 要 CDN ?
https://npmcdn.com/mint-ui@0.1.19/lib/index.js
https://npmcdn.com/mint-ui@0.1.19/lib/style.css

**Comment by ChangeZhang** [comment]
能不能加一个滑动删除的组件~非常感谢

**Comment by mithenji** [comment]
Hi，我觉得目前mint-ui 就差一个Accordion 组件了

在 2016年6月5日 上午12:11，FuryBean <notifications@github.com>写道：

**Comment by angusjiang** [comment]
index-list  为什么不支持异步数据，异步获取的数据index-list无法使用，报错
 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

**Comment by dingyiming** [comment]
希望组件能进一步美化，或者可以提供结构标准，让我们都能自己定制组件样式，增强组件的灵活可用

**Comment by QingWei-Li** [comment]
@dingyiming 结构标准是指什么？

**Comment by adonishong** [comment]
@Loyalsoldier SUI已死，有事烧纸。。。

**Comment by qcdys** [comment]
强烈要求增加modal

**Comment by zileyuan** [comment]
应该有必要增加 Card吧，用的挺多的

**Comment by Leopoldthecoder** [comment]
@zileyuan Card 一直都有的。

**Comment by lmyzzu** [comment]
期望实现侧边栏

**Comment by krongk** [comment]
一直有个疑问，通是ele.me的团队开发的组件，Element和MintUI的各自定位是什么，如何选择，同时建议MintUI也应该增加Element的如下几个组件，都很好用


- Tabs 标签页
- Breadcrumb 面包屑
- Dropdown 下拉菜单
- Steps 步骤条
- Tooltip 文字提示
- Popover 弹出框
- Card 卡片
- Carousel 走马灯
- Collapse 折叠面板

**Comment by yangjunwu** [comment]
希望增加select组件

**Comment by BenzHuang** [comment]
希望增加select组件，可以参考 vue-select
