### ISSUE TITLE
手动打包后vuejs报错

### ISSUE THREAD

**Issue by xiangpaopao** [ElemeFE/mint-ui#520]
从github直接下载2.0.6源码，直接引用lib目录的index.js 没有问题，`npm run dist`手动打包后，引用lib/index.js 报错如下

![dfcbec48-f772-47ad-9e25-dd1cc1470fc5](https://cloud.githubusercontent.com/assets/2008850/21249949/8ce691dc-c37c-11e6-9ad7-bbe518fa38af.png)

代码
```
<script src="http://unpkg.com/vue@2.0.2/dist/vue.js"></script>
<script src="lib/index.js"></script>
new Vue({
  el:'body',
  data:{ },
  created: function() {
        this.$toast('Hello world!')
  },
})
```

 

### Mint UI version
2.0.6

### Device model

chrome

**Comment by galenyuan** [comment]
@QingWei-Li @Leopoldthecoder 可重现，原因未知

**Comment by QingWei-Li** [comment]
最低兼容 Vue 2.1.0
