### ISSUE TITLE
MessageBox prompt 

### ISSUE THREAD

**Issue by w550** [ElemeFE/mint-ui#521]
### Mint UI version
^2.0.6
### Device model
iOS 9.3 Safari and Wechat webview

当弹出的框的 输入框 自动获取焦点的时候，键盘会弹出来，键盘弹出来了以后 弹出框就消失了，其实是跑下面去了。前提是你这个页面有很多 内容，出现滚动条了。

**Comment by InTwoDisease** [comment]
弹出的时候 设置 
最外层的 div  overflow hidden height:100%
 ios   设置 body 无效 
ios   设置 body 无效
ios   设置 body 无效
ios   设置 body 无效

**Comment by galenyuan** [comment]
是通过代码控制的__自动获取焦点__能出现还是手动点击获得焦点也会出现？

**Comment by lihaochen** [comment]
$type === 'promt' 时，messagebox 自动获取焦点。
在 iOS 设备上会出现键盘不会弹出来的情况，safari 和微信浏览器均可重现。
`if (val && this.$type === 'prompt') {
          setTimeout(() => {
            if (this.$refs.input) {
              this.$refs.input.focus();
            }
          }, 500);
        }`
在 iOS 上 input dom 的 focus 操作被忽视了，同时导致了 input 无法被选中，点不出键盘，运气好三四次兴许也能出来。
如果将 MessageBox 的弹出方式改为:
`MessageBox({
  message: 'test',
  showInput: true,
  $type: 'confirm'
})`
这时点击输入框键盘正常弹出。

**Comment by yinxianwei** [comment]
最近也碰到这个问题，我是这样解决的：

```js
MessageBox.prompt('title', 'message', {'$type': 'confirm'}).then(({
  value
}) => {
  console.log(value);
}, () => {});
```

**Comment by h404bi** [comment]
这个问题还存在啊。在iOS设备上。
