### ISSUE TITLE
IOS 下loadmore有异常

### ISSUE THREAD

**Issue by Bing-Xia** [ElemeFE/mint-ui#533]
### Mint UI version 
2.0.6

### Device model 
iphone6s Wechat webview

### What is actually happening?
1. 在微信浏览器中使用loadmore, 快速下拉加载，回调方法中执行 this.$refs.loadmore.onTopLoaded() 会报错，经查找发现是this.$refs为 {}。如果缓慢的下拉等待执行完则不会报错。
2. 快速下拉，在执行完操作后，如果列表项有点击事件，也会触发点击事件，造成页面跳转。缓慢的下拉则不会出现这问题。
loadTop方法如下：
`this.$http.post(Constant.api_user_messages, postData)`
`        .then((response) => {`
         ` if (response.data) {`
            `this.messages = response.data.body`
         ` }`
         ` this.loadmoreRef.onTopLoaded()`
        `}).catch((response)=>{`
          `alert('加载异常，请稍后重试。')`
       ` })`
   ` }`

在mounted方法中获取的 this.$refs.loadmore 则有值， 因此在mounted中添加了
`this.loadmoreRef = this.$refs.loadmore` 解决了回调方法中报错的问题，但是依然会触发列表项的点击事件。
_**以上问题在 android 微信端均未出现**_

**Comment by galenyuan** [comment]
$refs的问题可以确定一下如何重现然后到https://github.com/vuejs/vue/issues提一个issue
快速下拉的问题是不是页面引入了fastclick?

**Comment by Bing-Xia** [comment]
@galenyuan  确实引入了 fastclick, 谢谢提醒 👍

**Comment by areyouse7en** [comment]
所以，然后呢？就弃用fastclick了？

**Comment by Bing-Xia** [comment]
@areyouse7en 就弃用了，就这么简单～

**Comment by areyouse7en** [comment]
@Bing-Xia  哈哈，我也差点弃用。不过后来还是解决了。 https://github.com/ElemeFE/mint-ui/issues/120

**Comment by yang3406** [comment]
引入fastclick怎么解决呢
