### ISSUE TITLE
index list 放在pop中 点击index navigator indicator中文字不显示，同时也不跳转到对应的位置

### ISSUE THREAD

**Issue by greenlemonA** [ElemeFE/mint-ui#535]
<mt-popup
  v-model="popupVisible"
  position="bottom">
  <div class="page-indexlist">
    <div class="page-indexlist-wrapper">
      <mt-index-list>
        <div class="bg-light">
          <div class="city-pop-close">关闭</div>
          <div class="lost-title">当前所在</div>
          <div class="lost-title">国内热门城市</div>
          <section class="lost-section">
            <div class="sec-third" v-for="cell in hot">{{cell.name}}</div>
          </section>
        </div>
        <mt-index-section v-for="item in alphabet" :index="item.initial">
          <mt-cell v-for="cell in item.cells" :title="cell.name"></mt-cell>
        </mt-index-section>
      </mt-index-list>
    </div>
  </div>
</mt-popup>

这样嵌套使用，点击右边的navigator 不会导航到对应的位置，就算不使用popup组件 单个index list 我设置它position fixed 同样不再跳转，想知道这个怎么解决

**Comment by galenyuan** [comment]
描述不清，请提供在线demo
