### ISSUE TITLE
怎么在tabbar中设置一个跳转的链接

### ISSUE THREAD

**Issue by iqiuye** [ElemeFE/mint-ui#536]
怎么在mt-tab-item中设置一个跳转的链接

**Comment by iqiuye** [comment]
文档还是太简单了...
在mt-tabbar中监听到mt-tab-item的点击事件

**Comment by lzp0301** [comment]
@click.native="function()" 可以解决，我也搞了好久，但是这个input貌似只给父组件用的

**Comment by huangyanxiong01** [comment]
确实，文档只字不提啊

**Comment by wfxiaolong** [comment]
搜着答案，简单看了一下代码，直接加个href属性就行。..想太多了，各位....方法太多了...
`<mt-tab-item id="home" href="#/home">  
    <img slot="icon" src="../assets/logo.png"> 首页
</mt-tab-item>  `
