### ISSUE TITLE
Loadmore上拉加载新内容后mint-loadmore-content还是偏移50px

### ISSUE THREAD

**Issue by CodeDreamfy** [ElemeFE/mint-ui#537]
使用Loadmore上拉加载更多，加载完成后.mint-loadmore-content这个类的translateY还是没有恢复到0还是向上偏移50px，如何解决呢？

**Comment by Leopoldthecoder** [comment]
看文档，需要手动调用 `onBottomLoaded` 方法。

**Comment by yangmeijuan** [comment]
请问问题解决掉了吗
