### ISSUE TITLE
请问mint-ui可以找unxt运行吗？mint-ui 是否支持ssr

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/mint-ui#539]
Will the mint-ui can find unxt operation? Whether mint-ui supports ssr
请问mint-ui可以找unxt运行吗？mint-ui 是否支持ssr

**Comment by yuchonghua** [comment]
请问mint-ui可以找unxt运行吗？mint-ui 是否支持ssr

**Comment by QingWei-Li** [comment]
不支持
