### ISSUE TITLE
message box 性能问题

### ISSUE THREAD

**Issue by transtone** [ElemeFE/mint-ui#54]
demo页面在微信中打开的时候，message box的动画非常的卡顿，而vux的没有这个问题。

action sheet  也是一样，上拉动画不流畅。

**Comment by QingWei-Li** [comment]
@transtone Hi
麻烦提供下手机系统和型号

**Comment by transtone** [comment]
魅蓝note2 Android5.1 Flyme-5.1.6.0A

**Comment by Leopoldthecoder** [comment]
@transtone 提升了一些组件的性能，上面说的组件在微信浏览器上应该流畅了
