### ISSUE TITLE
datetime-picker 在改变系统字体大小时 组件中的时间会消失

### ISSUE THREAD

**Issue by deepcoldy** [ElemeFE/mint-ui#544]
### Mint UI version
2.0.4

### Device model
安卓Nexus 6 版本6.0.1 以及很多OPPO 华为手机中

下图为系统默认字体大小，显示正常的情况。
![wechatimg15](https://cloud.githubusercontent.com/assets/10922642/21493741/0bb86dcc-cc48-11e6-82da-95de16f71f26.png)

当增加了系统字体大小时，如下图，控件中的时间选择消失。
![wechatimg16](https://cloud.githubusercontent.com/assets/10922642/21493755/1bf7a950-cc48-11e6-8632-83f9f1b1fb6e.png)

**Comment by ringcrl** [comment]
我也遇到了同样的情况，请问你解决了吗

**Comment by deepcoldy** [comment]
@ringcrl 没有解决，一头雾水。。。
还没想明白是什么原因导致的

**Comment by JounQin** [comment]
如果安卓微信或者QQ 浏览器之类的，可能是 TBS 的 bug [渲染 bug?](http://bbs.mb.qq.com/thread-1482728-1-1.html)

那个是自己实现的 modal + picker，目前是通过先把 modal 从原结构处移到 body 根下，再移回去，强制重新渲染，你们可以尝试看看。

**Comment by ringcrl** [comment]
@deepcoldy 后台换了 weui.js，部分手机还会出现错位

**Comment by ringcrl** [comment]
@deepcoldy 后来换了 weui.js，部分手机还会出现错位选不准

**Comment by deepcoldy** [comment]
@ringcrl  试了weui确实可以解决，可能手边手机不够丰富没有再发现错位的问题。
还是希望能找到真正的原因。
稍后我会按 @JounQin  说的去尝试一下，非常感谢~

**Comment by ringcrl** [comment]
@deepcoldy 用户量多就会出现问题了，不幸的是我老板奇怪的安卓手机出了问题= =

现在看到微信钱包右上角交易记录里面那个选择器不错，就是不知道怎么做的

**Comment by galenyuan** [comment]
看起来应该是TBS渲染的BUG，回头会详细定位一下，感谢反馈

**Comment by otizis** [comment]
在特定华为手机下，必现。也修改了html的fontsize属性

**Comment by IIS1102** [comment]
mate9 EMUI5.0 必现

**Comment by deepcoldy** [comment]
@otizis @IIS1102 
其实可以给body加段css试试，忽略掉更改系统字体大小造成的影响。
   body{
        -webkit-text-size-adjust: 100% !important;
        -ms-text-size-adjust: 100% !important;
    }

**Comment by Jialufeng** [comment]
6s  也有同样的问题。还在找解决问题。。

**Comment by hsir05** [comment]
我也遇到这个问题了，试试上面的方法

**Comment by hsir05** [comment]
@deepcoldy 可以说下是怎么解决的么，我也出现这个问题了

**Comment by Jialufeng** [comment]
@hsir05   微信右上角  可以修改字体大小，修改为标准就可以了

**Comment by hsir05** [comment]
@deepcoldy 我的不是微信啊，是嵌入道App中的，在6splus下会显得很小，而且样式不好看，改变样式后，日期就显示的错乱了，而且选不了，你知道怎么解决么，非常感谢！

**Comment by deepcoldy** [comment]
@hsir05 我上面提供的css是可以禁用页面上字体的缩放（以此方式来规避字体大小对插件的影响）。
所以你看下是否因为这个css影响了你的页面布局。

**Comment by hsir05** [comment]
@deepcoldy 如果按你说的设置了以后，在6splus下样式还会出问题么？我这边试了以后，还是不行啊

**Comment by deepcoldy** [comment]
@hsir05 可以发个测试页面我帮你看看，我这边的所有页面都是OK的。

**Comment by hsir05** [comment]
@deepcoldy 可以给个方式联系下么，非常感谢

**Comment by hsir05** [comment]
@deepcoldy  或者我怎么给你发啊

**Comment by deepcoldy** [comment]
@hsir05 加我微信吧: Deepcold

**Comment by Pioneer-Linzi** [comment]
我的在一些手机里会特别的小

**Comment by deepcoldy** [comment]
@Pioneer-Linzi 之前给 @hsir05 解决的时候发现 是他的dpr设置问题，你可以看一下是否修改过页面的dpr

**Comment by Pioneer-Linzi** [comment]
@deepcoldy  没有，我是用了淘宝的Flexiblejs 用的 rem 这种去写的，比较小的情况是在ios的手机里会出现

**Comment by Pioneer-Linzi** [comment]
dpr 越大，这个显示就越小，这个是不是没有做适配？

**Comment by Pioneer-Linzi** [comment]
我现在已经改到别的控件了，

2017-11-02 15:54 GMT+08:00 deepcoldy <notifications@github.com>:

**Comment by sjjgithub** [comment]
我现在照着设置-webkit-text-size-adjust: 100% !important;
-ms-text-size-adjust: 100% !important;这个与起作用感觉

**Comment by deepcoldy** [comment]
@sjjgithub 可以详细描述一下么，光说不起作用没法帮你啊

**Comment by front-end-john** [comment]
微信设置-webkit-text-size-adjust: 100% !important;
-ms-text-size-adjust: 100% !important;解决了

**Comment by w-halo** [comment]
flex bug 
`.picker-items {
     min-width: 0.1%;
}`
