### ISSUE TITLE
nuxt.js 如何添加 Mint UI

### ISSUE THREAD

**Issue by yuchonghua** [ElemeFE/mint-ui#548]
nuxt.js 如何添加 Mint UI

**Comment by Ethennoob** [comment]
同问!

**Comment by QingWei-Li** [comment]
不支持

**Comment by yuchonghua** [comment]
你会支持吗

**Comment by QingWei-Li** [comment]
@yuchonghua 我支持，但没精力做

**Comment by yuchonghua** [comment]
@QingWei-Li 方便给个我自己去实现支持的建议吗？

**Comment by HadiChen** [comment]
@QingWei-Li 期待能支持一下，或者给个实现方向，非常感谢您的回答！

**Comment by QingWei-Li** [comment]
Vue 有提供 vm.$isServer 的属性来判断当前环境是不是服务端，要做的事情就是

1. 遇到操作 DOM 的地方就跳过 可以参考这条 PR https://github.com/ElemeFE/element/pull/1982

举个例子 https://github.com/ElemeFE/mint-ui/blob/69093cd074e7bb0f27e445a36f3af3654db138f7/packages/spinner/src/spinner/fading-circle.vue#L19 里面有 DOM 操作，那么应该改成

```js
created() {
     if (this.$isServer) return;
      this.styleNode = document.createElement('style');
      const css = `.circle-color-${this._uid} > div::before { background-color: ${this.spinnerColor}; }`;
      this.styleNode.type = 'text/css';
      this.styleNode.rel = 'stylesheet';
      this.styleNode.title = 'fading circle style';
      document.getElementsByTagName('head')[0].appendChild(this.styleNode);
      this.styleNode.appendChild(document.createTextNode(css));
    },
```

2. 把 `wind-dom` 换成 https://github.com/ElemeFE/element/pull/1982/files#diff-59f8408372ddda8f24a02c32d02f6547 因为 wind-dom 没有 window 的判断

**Comment by yuchonghua** [comment]
我这边可以帮助到您们的Mint UI  支持nuxt吗

**Comment by yuchonghua** [comment]
如果我这边抽时间

**Comment by QingWei-Li** [comment]
@yuchonghua 欢迎 👏

**Comment by yuchonghua** [comment]
@QingWei-Li 后期遇到问题，期待您能百忙中抽一点点时间指导一下，谢谢

**Comment by yuchonghua** [comment]
我现在已经fork，我是改那个分支呢
![image](https://cloud.githubusercontent.com/assets/17898715/21515217/911fcfe4-cd08-11e6-8a97-8396c12e30cc.png)

**Comment by QingWei-Li** [comment]
@yuchonghua master

**Comment by yuchonghua** [comment]
好的

**Comment by yuchonghua** [comment]
![image](https://cloud.githubusercontent.com/assets/17898715/21515425/862fbaac-cd0a-11e6-9978-661272adc262.png)
我是改这个文件夹吗

**Comment by yuchonghua** [comment]
if (this.$isServer) return;
是仅仅加在有dom的地方还是所有的 created() {呢
![image](https://cloud.githubusercontent.com/assets/17898715/21515473/15331942-cd0b-11e6-9b99-cc08827f03d6.png)

**Comment by yuchonghua** [comment]
![image](https://cloud.githubusercontent.com/assets/17898715/21515515/6f7f7986-cd0b-11e6-9d92-9a01609062da.png)

**Comment by QingWei-Li** [comment]
@yuchonghua 不是说在 created 上加判断，我只是给了例子

建议你不要着急改，先了解下 SSR 的工作原理以及 Vue 的渲染机制，同时 Element 里我已经给了个示范你可以参考 https://github.com/ElemeFE/element/pull/1982 

还有 issue 是拿来讨论问题，如果你要问问题去 Gitter 里，我也在那里面。毕竟每条 issue 评论都会其他关注者收到邮件。

**Comment by yuchonghua** [comment]
Has been submitted to [pull](https://github.com/ElemeFE/mint-ui/pull/555), please test, thank you

**Comment by yuchonghua** [comment]
@QingWei-Li 你好，可以帮忙看一下吗

**Comment by glass4pk** [comment]
great！
ssr现在支持了吗？求支持

**Comment by yuchonghua** [comment]
@glass4pk 我已经fork做了[ssr支持](https://github.com/ElemeFE/mint-ui/pull/557)修改，等待作者那边审查

**Comment by venn515** [comment]
@QingWei-Li 大概什么时候可以发布呢？

**Comment by Elfantasmal** [comment]
非常期待！:thumbsup::thumbsup::thumbsup:

**Comment by HadiChen** [comment]
@QingWei-Li 什么时候能发布ssr呢？

**Comment by yuchonghua** [comment]
@Leopoldthecoder
 @QingWei-Li 

![image](https://cloud.githubusercontent.com/assets/17898715/21639394/c17fd43e-d2aa-11e6-8071-5e9650f138df.png)
我通过npm i mint-ui -S安装后配置到nuxt会有这个报错，可是我如果是下载github上面的代码自己npm run dist 然后去把lib 复制替换nuxt项目下面的node_modules下的mint-ui下的lib竟然正常，这个是什么原因呢
![image](https://cloud.githubusercontent.com/assets/17898715/21639430/ee272cc6-d2aa-11e6-8c92-afe4a2cd601f.png)

**Comment by chuanxd** [comment]
期待 `mint-ui` 支持 SSR !

**Comment by QingWei-Li** [comment]
`2.1.0` 已支持并修复上述问题

**Comment by Timnny** [comment]
我在插件里写的，
import Vue from 'vue'
import MintUI from 'mint-ui'
Vue.use(MintUI)
使用Indicator 依然报错
Indicator is not defined

**Comment by yuchonghua** [comment]
不会啊，我一直在用啊

**Comment by yuchonghua** [comment]
你这个描述似乎太简单，查不到问题所在

**Comment by Timnny** [comment]
我局部引入，就可以正常使用。
好像是Indicator并不是全是变量

**Comment by yuchonghua** [comment]
你怎么使用的呢

**Comment by Timnny** [comment]
在.vue里面：
Indicator.open({
			  text: '加载中...',
			  spinnerType: 'fading-circle'
			});



这么写不行，所以我在组件里面又加了一句：
import { Indicator, Toast } from 'mint-ui';

**Comment by yuchonghua** [comment]
肯定不行啊 Indicator 本身就不是全局的

**Comment by lmf** [comment]
使用ssr后，在使用button组件后服务端渲染会报如下错误，但浏览器渲染时候没有问题：
@font-face {font-family: "mintui";
^
SyntaxError: Invalid or unexpected token

查看mint-ui/lib/button/index.js 有这么一段：

module.exports = require("mint-ui/lib/font/style.css");

求问是什么原因，或者需要特殊的配置？

**Comment by lmf** [comment]
上面这个问题终于找到原因了，在使用webpack打包编译服务端产出时候，如果配置了
`
   externals: nodeExternals({
        whitelist: /\.css$/
    })`
就不会将node_modules中的依赖打包进去，这时候node层渲染时候require css文件就会报错，解决办法在这个whitelist配置中加上mint-ui

**Comment by sxy1992** [comment]
@QingWei-Li 你好，请问mint ui支持jsx语法吗，有一些组件传递model无效

**Comment by YOUNGmaxer** [comment]
@lmf 感谢，我遇到了同样的问题，按你的方式解决了，不过不知道为什么 whitelist 里面写 'mint-ui' 不行，写成正则 /^mint-ui/ 才可以。
