### ISSUE TITLE
tab 不能左右滑动切换

### ISSUE THREAD

**Issue by transtone** [ElemeFE/mint-ui#55]
tab类的tabbar, tabcontainer, navbar都不能左右滑动切换。

**Comment by furybean** [comment]
感谢建议，这个 feature 可能会放到后续计划里面。

**Comment by beeplin** [comment]
非常支持。建议参考framework7相关滑动动态效果的实现：http://framework7.io/docs/tabs.html

**Comment by xiongyujie** [comment]
tabcontainer可以点击面板切换下面的内容，是否可以通过滑动页面内容来切换上面的面板？
