### ISSUE TITLE
Indicator组件异步关闭后再打开无法显示

### ISSUE THREAD

**Issue by CoolAndCold** [ElemeFE/mint-ui#550]
在HTML中可以看到DOM组件，但是opacity为0。代码如下：
        Indicator.open({
            text: '加载中...',
            spinnerType: 'fading-circle',
        });
        setTimeout(() => {
            Indicator.close();
            Indicator.open({
                text: '加载中...',
                spinnerType: 'fading-circle',
            });
        }, 200);

**Comment by CoolAndCold** [comment]
mint版本：2.0.6
vue版本：2.1.0

**Comment by CoolAndCold** [comment]
![image](https://cloud.githubusercontent.com/assets/17401351/21558990/2d2ada3e-ce7e-11e6-97d0-7b5b118f439a.png)

**Comment by galenyuan** [comment]
使用你贴的代码无法复现，能写个在线demo么？

**Comment by CoolAndCold** [comment]
刚升级了vue和mint-ui的版本。。。发现BUG已经没有了~
