### ISSUE TITLE
picker组件多级联动 bug

### ISSUE THREAD

**Issue by weien601** [ElemeFE/mint-ui#551]
### Mint UI version
2.0.5
### Device model

开发环境 mac chrome浏览器
### Reproduction Link

npm install

### What is Expected?
期望在修改 picker 内容后，滚动位置能够正确，还希望如果重置数据中有上一次选中的值时，能够使用上一次的值不要重置到第一个

### What is actually happening?
使用 picker 组件实现多级联动时，出现的问题，比如比如数据为[1: [3,4,5], 2:[1,2,3,4,5]]，当我在第一列为2的时候，第二列选中3，再调整第一列为1，这时第二列的数据为[3,4,5], 显示结果为选中的是5，但是3是黑色标亮的。（按照你们的逻辑，上一次选中的3在刷新数据后，index 为-1时才会重置为第一个选项，才会产生滚动正确，但是上一次选中的值正好在刷新的内容中）

**Comment by returnjinx** [comment]
没有遇到过这个
