### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by Stevenzwzhai** [ElemeFE/mint-ui#554]
### Mint UI version
2.0.6
### Device model
ios10 android

### What is Expected?
滑动日期控件实列表不应该跟随滚动
### What is actually happening?
当日期控件上选择年或是在空白区域上滑动会带动页面列表也在滚动

**Comment by galenyuan** [comment]
无法重现，能提供重现步骤或在线demo么？

**Comment by Stevenzwzhai** [comment]
就是在iphone上滑动日期控件的空白部分（年和月中间），日期不动的时候，被控件遮住页面的列表会跟着滑动，安卓上不明显，iphone上应该很容易测试到。

**Comment by hasbug** [comment]
其实就是在datepicker的空白处滑动，事件会穿透到datepicker遮罩层下方的页面，造成下方页面滚动条滚动

**Comment by lulu-ls** [comment]
同问  特别是再微信中几乎用不了
