### ISSUE TITLE
官网以及文档，一直无法访问，告诉我不是一个人...

### ISSUE THREAD

**Issue by ChristianYeap** [ElemeFE/mint-ui#558]
如题。。 改了host也不行哦，求个解决方法。急，在线等~

**Comment by chuanxd** [comment]
http://mint-ui.github.io/#!/en
正常

**Comment by ChristianYeap** [comment]
楼上的链接我也是打不开，能不能教我下，打开文档的办法。

**Comment by theseawolves** [comment]
用https方式访问试试  https://mint-ui.github.io/#!/en

**Comment by ChristianYeap** [comment]
感谢楼上们的回答，终于不小心能上去了
