### ISSUE TITLE
search样式破损

### ISSUE THREAD

**Issue by transtone** [ElemeFE/mint-ui#56]
微信下search样式破损

魅蓝note2 Android5.1 Flyme-5.1.6.0A ： 有问题
华为mate8： 没问题

**Comment by furybean** [comment]
@QingWei-Li

**Comment by QingWei-Li** [comment]
@transtone 你好
我现在手头没机器，可否发一下截图？

**Comment by transtone** [comment]
其实一直在发截图，可恨一直没能传上去。一会换个网络环境再试试。

**Comment by transtone** [comment]
其实一直在发截图，可恨一直没能传上去。一会换个网络环境再试试。

**Comment by furybean** [comment]
@QingWei-Li 应该有 flyme 的测试机， 你可以试试看。

**Comment by QingWei-Li** [comment]
今天试过了没重现 😂
