### ISSUE TITLE
模块导出方式变更属于break change吗？

### ISSUE THREAD

**Issue by wssgcg1213** [ElemeFE/mint-ui#562]
版本 2.0.6 -> 2.0.7  
模块的导出方式发生了变更：
参见 `src/index.js `

原先是
```js
module.exports = {
  install,
  A,
  B
}
```

现在变成了
```js
export {
  install as default,
  A,
  B
}
```

相当于是从 CommonJS 标准变更到了 ES6 Module 标准，是一个不兼容的更新，不应该使用 patch 位的更新？  

我的症状是从2.0.6升到2.0.7之后无法正常 `Vue.use`, 查看了一下2.0.7的发布日期是今天推测并验证跟版本有关才提问的

**Comment by QingWei-Li** [comment]
是的 今天会回滚回去

**Comment by QingWei-Li** [comment]
fixed in `2.1.0`
