### ISSUE TITLE
Popup 多层级时 关闭最上层 下层也会关闭

### ISSUE THREAD

**Issue by bibiuc** [ElemeFE/mint-ui#565]
### Mint UI version
2.1.0
### Device model
any

### Reproduction Link
any

### What is Expected?
因为popup-manager只存一个遮罩
### What is actually happening?
打开两层mt-popup的时候

**Comment by galenyuan** [comment]
这个case比较少见，并且通常来讲我们也不建议多层popup，用户体验也不是很好，后续会讨论是否要每个popup使用单独的遮罩
