### ISSUE TITLE
Cannot read property 'installed' of undefined

### ISSUE THREAD

**Issue by linshicheng** [ElemeFE/mint-ui#567]
What is actually happening?

安装了yarn，然后github克隆项目下来，按照流程安装，确定模块依赖都有，npm run dev过程未报错，打开提示 Cannot read property 'installed' of undefined

![image](https://cloud.githubusercontent.com/assets/18699401/21705873/b00053ec-d3fd-11e6-93b4-09051d04963a.png)

> Uncaught TypeError: Cannot read property 'installed' of undefined
>     at Function.Vue.use (eval at ./node_modules/vue/dist/vue.runtime.common.js (app.js:3525), <anonymous>:3428:15)
>     at Object.eval (eval at ./example/entry.js (app.js:746), <anonymous>:20:45)
>     at eval (eval at ./example/entry.js (app.js:746), <anonymous>:53:30)
>     at Object../example/entry.js (app.js:746)
>     at __webpack_require__ (app.js:660)
>     at fn (app.js:84)
>     at Object.1 (app.js:4275)
>     at __webpack_require__ (app.js:660)
>     at ./example recursive ^\.\/pages.*$ (app.js:709)
>     at app.js:712

Mint UI version

2.1.0

**Comment by xuelq007** [comment]
遇到了一样的问题
ncaught TypeError: Cannot read property 'install' of undefined
    at Function.e.use (vue.esm.js:4750)
    at Object.NHnr (main.js:13)
    at o (bootstrap 7c12fd69839dfdaf1a8b:54)
    at window.webpackJsonp (bootstrap 7c12fd69839dfdaf1a8b:25)
    at app.add56870369406d6cbd0.js:1
