### ISSUE TITLE
Swipe的基础用法问题

### ISSUE THREAD

**Issue by user20161119** [ElemeFE/mint-ui#572]
http://jsfiddle.net/cinwell_li/Lr75y28t/1/?utm_source=website&utm_medium=embed&utm_campaign=Lr75y28t#&togetherjs=fjP81OQbtU

请问这段代码怎么用原生的vue调用mint-ui swipe组件？

**Comment by galenyuan** [comment]
什么叫叫原生的vue调用mint-ui的swipe组件?
