### ISSUE TITLE
有没有类似vux的 flexbox布局组件？组件可以再丰富点

### ISSUE THREAD

**Issue by spiritelf** [ElemeFE/mint-ui#574]

**Comment by spiritelf** [comment]
组件方面我觉得可以参考参考vux 更丰富

**Comment by baiyaaaaa** [comment]
在layout目录有flex布局组件

**Comment by galenyuan** [comment]
刚才去看了一下vux的flexbox组件，说实话意义不大，因为不需要像bootstrap那样通过class来控制在不同分辨率下的布局样式，只做手机端业务的话，让开发者自行控制CSS更好一些，封装成组件反而不够灵活
