### ISSUE TITLE
Datetime picker设置自定义hour-format模版bug

### ISSUE THREAD

**Issue by wangjl6** [ElemeFE/mint-ui#577]
### Mint UI version
2.1.0
### Device model

chrome浏览器
### Reproduction Link

https://unpkg.com/mint-ui/lib/index.js
### What is actually happening?
datetime-picker组件设置type为time时,设置属性hour-format和minute-format模版后无法选择具体值。
拖动后会自己滑倒初始值

**Comment by galenyuan** [comment]
fixed in #613

**Comment by DeepenLau** [comment]
这个 bug 在 1.0.2 的版本目前尚未修复
