### ISSUE TITLE
通过 babel-plugin-component 自动按需导入 loadmore 模块 ，样式没有被导入

### ISSUE THREAD

**Issue by LeisureZjj** [ElemeFE/mint-ui#58]
loadmore 功能可以用，但是样式引入不进来。以下是我的代码片段：

页面组件导入 loadmore 模块：
`import { Loadmore } from 'mint-ui'`

.babelrc 文件：
`"plugins": [
  	"transform-runtime",
  	["component", [{ "libraryName": "mint-ui", "style": true }]]
  ]`

**Comment by QingWei-Li** [comment]
我试了下是可以引入样式的，你是指哪些样式？你可以看看类似这个元素上有没有样式，如果有就说明已经成功引入了

```html
<div class="mint-loadmore"></div>
```

```style
.mint-loadmore {
    overflow: hidden;
}
```

**Comment by LeisureZjj** [comment]
@QingWei-Li 
这个 class 没有样式 
![qq 20160606011331](https://cloud.githubusercontent.com/assets/6189670/15807001/2ff87584-2b84-11e6-93de-49a04e54556f.png)

**Comment by LeisureZjj** [comment]
@QingWei-Li 
这个 class 没有实际值
![Uploading QQ截图20160606012125.png…]()
![Uploading QQ截图20160606012125.png…]()

**Comment by LeisureZjj** [comment]
@QingWei-Li  

 class 里边没有实际值

![qq 20160606012300](https://cloud.githubusercontent.com/assets/6189670/15807071/c931e928-2b85-11e6-9e9b-f9a741501a9a.png)
![qq 20160606012125](https://cloud.githubusercontent.com/assets/6189670/15807072/cb806862-2b85-11e6-82f8-17ff33bf038b.png)

**Comment by QingWei-Li** [comment]
- 我记得 vue-loader 8.5之前有个 scoped style 的 bug 你看看你的 vue loader 是不是这个版本之前的，升级下就好了。
- 如果还是不行看看头部 style 标签有没有 loadmore 的样式？直接全局搜索
- 如果没有你先手动引入央视看看有没有效果

我猜目测第一个问题

**Comment by LeisureZjj** [comment]
之前只加了 css-loader，后来再加上 style-loader，样式出来了。
谢谢答复。
