### ISSUE TITLE
picker 

### ISSUE THREAD

**Issue by BusyHe** [ElemeFE/mint-ui#580]
![image](https://cloud.githubusercontent.com/assets/17348825/21792852/a25717f8-d727-11e6-845e-e2acd0db2f7e.png)
![image](https://cloud.githubusercontent.com/assets/17348825/21792865/b44408e0-d727-11e6-9b5f-93754ef2cbd5.png)
滑动的时候的报错，pc下无法滑动

**Comment by galenyuan** [comment]
PC下需要先进入模拟手机模式再刷新页面才能正确监听ontouchstart
