### ISSUE TITLE
Message-Box

### ISSUE THREAD

**Issue by shufangjian** [ElemeFE/mint-ui#581]
### chrome

Message-Box 加入验证 报错

Cannot read property 'classList' of undefined

自己的代码
`
var reg = new RegExp("[1]{1}[0-9]{10}")
MessageBox({
    title: ' ',
    $type:'prompt',
    message: ' ', 
    showCancelButton: true, 
    inputValue: data,
    showInput: true,
    inputPattern:reg,
    editorErrorMessage:null,
    callback:function(action){
      console.log(action)
    }
 })`

请问源码的watch value 里面$refs 是指向的哪个dom
`
value(val) {
  this.handleInputType(this.inputType);
  if (val && this.$type === 'prompt') {
    setTimeout(() => {
      if (this.$refs.input) {
        this.$refs.input.focus();
      } }, 500);
     }
 }`

**Comment by shufangjian** [comment]
又看了下 是验证的时候不能往里面传inputValue 触发了watch 此时ref还没有

**Comment by amanzyw** [comment]
MessageBox.prompt里面的input想换成textarea怎么换，还有就是能不能加个参数，可以给组件添加自定义class
