### ISSUE TITLE
我看demo中的返回按钮，可以直接定位到列表页面 刚刚选的那个行，然而在实际项目上，不行

### ISSUE THREAD

**Issue by tangyouwo** [ElemeFE/mint-ui#593]
RT，是实际项目上，我返回的时候都会重新加载数据，我看项目的demo源码里就一个router link /
请问你这个返回是如何做到不重新加载数据的。

**Comment by galenyuan** [comment]
https://router.vuejs.org/zh-cn/api/router-link.html

> 在 HTML5 history 模式下，router-link 会拦截点击事件，让浏览器不在重新加载页面。
下次建议去StackOverflow或专门的问答社区提问。

**Comment by tangyouwo** [comment]
然而你关闭的时候。我是测过的。即使是history 模式，浏览器仍然是重新加载了页面。重新请求接口。。这个文档我是看了的。。。。所以才很奇怪的提问。

**Comment by galenyuan** [comment]
组件的生命周期是会被重新触发的，你可以看看https://cn.vuejs.org/v2/guide/components.html#keep-alive

**Comment by tangyouwo** [comment]
然而这个文档，我也看了。在正确使用keep-alive的情况下，不使用history也是可以不重新渲染的 不重新加载数据。。。。  刚好，我使用keep-alive 会让所有的页面都这样，这就比较矛盾了。。。所以想办法在解决这个问题。如果你那也是这样，，那就意味着我得继续找一下其他办法。。。。 还是感谢你的回复

**Comment by tangyouwo** [comment]
我觉得在activated重新加载数据 应该就没大问题了。。。
