### ISSUE TITLE
根据1.0文档配置package.json和wepack.config.js后，运行npm run dev报错

### ISSUE THREAD

**Issue by pensula** [ElemeFE/mint-ui#598]
根据1.0文档配置package.json和wepack.config.js后，运行npm run dev报错。node和npm已经升级到最新版了。以下是报错信息。
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-project@ dev: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8087`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@ dev script 'cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8087'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server --inline --hot --port 8087
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

**Comment by galenyuan** [comment]
源代码是1.x的还是master上的?

**Comment by pensula** [comment]
@galenyuan 是按照文档http://mint-ui.github.io/docs/#!/zh-cn/quickstart配置的，已经定位到问题了，webpack.config.js里出现了root选项，新webpack不能出现这个的。
