### ISSUE TITLE
popup lockscroll 设置为true 当popup 中内容滚动到边缘后body 仍可以滚动

### ISSUE THREAD

**Issue by DingWentao1234** [ElemeFE/mint-ui#602]
使用了lock-scroll 但是当popup 中内容也可以滚动的时候，popup内容滚动到边缘后，body又可以滚动，这里应当要做边缘限制

**Comment by galenyuan** [comment]
lockscroll是什么？

**Comment by DingWentao1234** [comment]
🤣  你去看下popup 源码

**Comment by galenyuan** [comment]
能详细描述或提供在线demo么 无法重现

**Comment by hahazexia** [comment]
我还发现个问题，我把picker放在popup里用，在ios下滑动picker选项的时候，如果一直往边缘滑动，比如一直往最上面或最下面滑，最后会死屏，直接picker和popup就都死掉了，这算不算bug
