### ISSUE TITLE
Indicator在Open之后接着调用Close无法关闭

### ISSUE THREAD

**Issue by CoolAndCold** [ElemeFE/mint-ui#603]
测试代码如下：

export default {
    name: 'app',
    mounted() {
        this.showLoading();
        this.hideLoading();
    },
    methods: {
        showLoading() {
            Indicator.open({
                text: '正在加载...',
                spinnerType: 'fading-circle',
            });
        },
        hideLoading() {
            Indicator.close();
        },
    },
}

**Comment by CoolAndCold** [comment]
Vue版本：2.1.0
Mint-UI版本：2.1.0
浏览器：Chrome

**Comment by galenyuan** [comment]
```javascript
setTimeout(() => {
  this.hideLoading();
}, 0)
```

**Comment by CoolAndCold** [comment]
= =！心塞...不能把instance.visible = true丢到上一个事件轮询里面嘛！~
