### ISSUE TITLE
mint-ui.github.io首页有一处错误

### ISSUE THREAD

**Issue by jaeheng** [ElemeFE/mint-ui#604]
> 地址： http://mint-ui.github.io/#!/zh-cn

### 如下图，mint-ui 写成了 minu-ui

![image](https://cloud.githubusercontent.com/assets/7394473/22132882/bd271f42-def7-11e6-9636-e758c527838f.png)

**Comment by galenyuan** [comment]
https://github.com/mint-ui/docs 欢迎PR
