### ISSUE TITLE
mint-ui 实用iconfont 问题

### ISSUE THREAD

**Issue by ecitlm** [ElemeFE/mint-ui#607]
<mt-cell title="首页" to="/home" icon="iconfont icon-home" value=""></mt-cell>

<i class="mintui mintui-iconfont icon-home"></i> 和iconfont之间如何处理

**Comment by galenyuan** [comment]
正常引入使用即可

**Comment by ecitlm** [comment]
引入之后默认添加了 mint-ui 的默认icon class 以及 font-family被mint-ui覆盖，mint-ui 没有提供一套icon图标库吗

**Comment by imdlan** [comment]
> 引入之后默认添加了 mint-ui 的默认icon class 以及 font-family被mint-ui覆盖，mint-ui 没有提供一套icon图标库吗

有7个可以用：
```
<i class="mint-toast-icon mintui mintui-more"></i>
<i class="mint-toast-icon mintui mintui-back"></i>
<i class="mint-toast-icon mintui mintui-search"></i>
<i class="mint-toast-icon mintui mintui-field-error"></i>
<i class="mint-toast-icon mintui mintui-field-warning"></i>
<i class="mint-toast-icon mintui mintui-success"></i>
<i class="mint-toast-icon mintui mintui-field-success"></i>
```
图标如下：
![](https://ws1.sinaimg.cn/large/006tNbRwly1fye5mzwnbcj301m03kjr6.jpg)

**Comment by cooper1x** [comment]
> > 引入之后默认添加了 mint-ui 的默认icon class 以及 font-family被mint-ui覆盖，mint-ui 没有提供一套icon图标库吗
> 
> 有7个可以用：
> 
> ```
> <i class="mint-toast-icon mintui mintui-more"></i>
> <i class="mint-toast-icon mintui mintui-back"></i>
> <i class="mint-toast-icon mintui mintui-search"></i>
> <i class="mint-toast-icon mintui mintui-field-error"></i>
> <i class="mint-toast-icon mintui mintui-field-warning"></i>
> <i class="mint-toast-icon mintui mintui-success"></i>
> <i class="mint-toast-icon mintui mintui-field-success"></i>
> ```
> 图标如下：
> ![](https://camo.githubusercontent.com/93669f26bc31307692031c988cce3200267a2d92/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f303036744e6252776c7931667965356d7a776e62636a3330316d30336b6a72362e6a7067)

这个字好小…………
