### ISSUE TITLE
Datetime Picker组件在IPHONE 6P IOS10.2.1下异常

### ISSUE THREAD

**Issue by yakecan** [ElemeFE/mint-ui#616]
如题，效果如图：
 
<img src="https://i.screenshot.net/0zz9bz1">

**Comment by hahazexia** [comment]
类似日期选择控件这种滑动的好像都有问题，往最上面边缘或者最下面边缘不停地滑动，页面会直接死掉，不知道怎么回事

**Comment by galenyuan** [comment]
请参考 #544
