### ISSUE TITLE
网站demo只有一个page全部重新渲染，效果不太好，最好有两个，有切换效果。会好些

### ISSUE THREAD

**Issue by bibiuc** [ElemeFE/mint-ui#62]

**Comment by furybean** [comment]
感谢反馈，本周会加上。

**Comment by QingWei-Li** [comment]
@bibiuc 

请问下具体是指什么效果？是说左边要有导航栏，点击切换？还是指什么？

**Comment by bibiuc** [comment]
@QingWei-Li  点击切换，指的是从主的demo列表到各个demo的详情的切换

**Comment by bibiuc** [comment]
@QingWei-Li http://elemefe.github.io/mint-ui/#!/popup
这种右侧弹出的效果好。

**Comment by QingWei-Li** [comment]
@bibiuc Get.
