### ISSUE TITLE
switch组件

### ISSUE THREAD

**Issue by H2rmone** [ElemeFE/mint-ui#621]
<mt-switch @change="chatSwitch" class="chat-switch" v-model="switchVal" slot="chat-switch"></mt-switch>

其中switchVal我从接口中获取的话。如果是true是好的，false的话，每次进入都会出发动画，从开变为关，而不是直接关。。。

**Comment by galenyuan** [comment]
因为你是异步改变的switch value，当然会触发动画，可以在loading时隐藏掉switch组件
