### ISSUE TITLE
Datetime picker 增加 当前日期参数

### ISSUE THREAD

**Issue by 17leba** [ElemeFE/mint-ui#622]
看文档没有一个currentDate，即自定义当前选中值。
比如填出生日期，想设置当前选中值为1949-01-01，startDate为1909-01-01，endDate为当前日期。
现在startDate即为当前选中值，用户得从1909往上滑，操作不便。

**Comment by Leopoldthecoder** [comment]
给 v-model 绑定的变量赋初始值就行。
