### ISSUE TITLE
DateTime Picker 想让时间选择的空白区域也能滚动选择，请问该怎么处理？

### ISSUE THREAD

**Issue by zhangping1** [ElemeFE/mint-ui#623]
DateTime Picker 想让时间选择的空白区域也能滚动选择，请问该怎么处理？
<img width="341" alt="1" src="https://cloud.githubusercontent.com/assets/6762555/22812771/b0c864be-ef81-11e6-9dd4-b72780e2cdee.png">
谢谢

**Comment by galenyuan** [comment]
暂无方案，可尝试自行订制

**Comment by yoyo0926** [comment]
+1 同样的问题
