### ISSUE TITLE
Search placeholder的文字比较长时，后面的文字被截断

### ISSUE THREAD

**Issue by caoyr** [ElemeFE/mint-ui#624]
### Mint UI version
V2.1.1

### Device model
ios 10.1.1 safari

### What is actually happening?
<mt-search v-model="value"  placeholder="输入单号/客户姓名/手机号搜索"></mt-search>
Search组件中placeholder的文字比较长时（比如，placeholder=“输入单号/客户姓名/手机号搜索”），后面的文字会被截断不显示。<br>
![11](https://cloud.githubusercontent.com/assets/16284105/22818472/52ae8ab2-efa8-11e6-805d-52b10c5465cc.png)

**Comment by galenyuan** [comment]
无法重现，下面是我手机上的样式
![wechatimg5](https://cloud.githubusercontent.com/assets/10335062/22968225/8c5ee00e-f3a4-11e6-8228-a17d34ac8187.png)
