### ISSUE TITLE
Indicator有时候会被新的覆盖层遮挡了，有办法让它永远显示在最外层不被遮挡吗？

### ISSUE THREAD

**Issue by wonghoman** [ElemeFE/mint-ui#626]
你好，我在使用Indicator的时候发现，Indicator有时候会被新的覆盖层遮挡了，有办法让它永远显示在最外层不被遮挡吗？

**Comment by galenyuan** [comment]
设置元素的`z-index`

**Comment by wonghoman** [comment]
@galenyuan 你好，我是用以下的代码使用Indicator的，设置元素z-index我也想到了，但就是不知道怎么修改，难道跑去改源码？望指教
`import { Indicator } from 'mint-ui';
Indicator.open('加载中...');
`

**Comment by Tian-Hun** [comment]
@wonghoman 请教一下你是怎么处理的

**Comment by RobotJohns** [comment]
没人 解决这个问题吗？ 
奇怪的是 
Toast 显示的层级是对的
Indicator 是会被遮挡的

**Comment by RobotJohns** [comment]
https://blog.csdn.net/nicepainkiller/article/details/89406344
