### ISSUE TITLE
picker组件点击picker-item元素时，会出现点击区域翻动的bug

### ISSUE THREAD

**Issue by julyL** [ElemeFE/mint-ui#628]
地址：http://elemefe.github.io/mint-ui/#/picker   可以点击地区选择的pricker进行测试
![image](https://cloud.githubusercontent.com/assets/12106591/22870635/ffc2b1e6-f1e3-11e6-9746-1acb455d479a.png)

例如：我点击上图中红框标注区域，会导致整个省份这一级数据向上滚动多级。(而且有时候会向下滚动) 
每次点击同一个红框部分，每次滚动的距离可能不一样，有时方向也会不一样。可能是红框部分的点击事件出发了多次造成的。
小米4和ios均有此问题。

最好改成：点击上海就滚动到上海这个地方：)

**Comment by galenyuan** [comment]
fixed in #634 
此组件没有之前的设计就没有点击操作，所以要实现此功能改动较大，暂时先不考虑，当然欢迎提PR。

**Comment by Molly0920** [comment]
这个bug又出现了，设置了初始值，点击picker-item就会出现滚动2.2.5版本
