### ISSUE TITLE
popup里面的内容在手机端滑动时，总是会滑动到body，这很苦恼

### ISSUE THREAD

**Issue by reversesoul** [ElemeFE/mint-ui#629]
vue2.0的环境。我注意到，popup的modal被滑动的时候，body是不会跟随滑动的，可是内容部分被滑动就会。能否给个解决的方法。

**Comment by galenyuan** [comment]
`:lock-scroll="true"`

**Comment by hzx930415** [comment]
我也遇到了这个问题 。但是 @galenyuan  的回答并不能解决我的问题。

**Comment by reversesoul** [comment]
我也没解决
