### ISSUE TITLE
想看源码学习一下，但有些组件怎么看不到源码

### ISSUE THREAD

**Issue by WilliamDu1981** [ElemeFE/mint-ui#63]
比如toast，始终没找到源码

**Comment by Leopoldthecoder** [comment]
请移步[这里](http://mint-ui.github.io/docs/#!/zh-cn/repositories)

**Comment by Leopoldthecoder** [comment]
请移步[这里](http://mint-ui.github.io/docs/#!/zh-cn/repositories)
