### ISSUE TITLE
picker 动态更改slots数bug

### ISSUE THREAD

**Issue by elevenkey** [ElemeFE/mint-ui#632]
项目里有一个表单，需要多次用到picker，于是在page里引入了一个picker组件。这个组件的slots绑定了一个compute属性，用于动态更改slots数据。

开始只测试了单slots的情况，多组slots数据切换没有问题。后来引入了一个3个slots的数据（省市区），发现picker出错。首先picker的后两个slot没有正确设置初始值。另外整个picker的返回值也出错总是返回：[Array[2], undefined, undefined]

3个slot无论哪个更改，都会把这个值返回到返回值数组第一项。后两项始终undefined。

请问picker是否支持动态改变slots? 我这么做是否支持。
另外尝试clone了项目源代码，进行修改，npm run dist以后，把生成的lib放入原来通过npm安装的项目目录，报错。如果手动打包，应该如何操作？
谢谢～

**Comment by galenyuan** [comment]
slots不支持动态更改
报错请提供报错信息
