### ISSUE TITLE
toast/src/toast.js 代码的bug

### ISSUE THREAD

**Issue by zeroone001** [ElemeFE/mint-ui#633]
`~duration && (instance.timer = setTimeout(function() {`这里应该改成`~~duration`，从代码要实现的功能来看

**Comment by galenyuan** [comment]
duration为0时：
  `~duration`是-1也就是`true`
  而`~~duration`为0也就是`false`

**Comment by galenyuan** [comment]
btw, 此处貌似有冗余，欢迎PR指正

**Comment by zeroone001** [comment]
从代码上来看，难道不是应该排除字符串和取整吗？一个按位非，貌似是不行的，还是有其他的目的

**Comment by zeroone001** [comment]
嗯，是考虑的为0时的情况，明白了
