### ISSUE TITLE
在Vue2中使用DatetimePicker组件，提示Failed to resolve directive: ref(found in component <mt-datetime-picker>) 

### ISSUE THREAD

**Issue by DwyaneYu** [ElemeFE/mint-ui#635]
vue版本2.1.10,按照官方方法安装mint-ui
使用DatetimePicker组件时也是按照官方做法
导入：
`import { DatetimePicker } from 'mint-ui';`
注册：
`export default {
    data () {
      return {
      }
    },
    components: {
      DatetimePicker
    },
    methods: {
    }
  }`
浏览器控制台报错:
`Failed to resolve directive: ref(found in component <mt-datetime-picker>) `
求解答，谢谢!

**Comment by galenyuan** [comment]
情况一：
``` javascript
import { DatetimePicker } from 'mint-ui';
components: {
  DatetimePicker
}
```
则标签为：
```vue
<datetime-picker></datetime-picker>
```

情况二：
``` javascript
import { DatetimePicker } from 'mint-ui';
components: {
  'mt-datetime-picker': DatetimePicker
}
```
则标签为：
```vue
<mt-datetime-picker></mt-datetime-picker>
```

情况三：
``` javascript
import { DatetimePicker } from 'mint-ui';
import Vue from 'vue';

Vue.component('mt-datetime-picker', DatetimePicker);
```
则标签为：
```vue
<mt-datetime-picker></mt-datetime-picker>
```

**Comment by DwyaneYu** [comment]
还是不行, 我用过其他的组件比如tabbar没有任何问题, 但是datetimepicker这个组件还是一直报错
