### ISSUE TITLE
LoadMore 下拉组件当里边的嵌套另一个内容比较多的list时会卡顿

### ISSUE THREAD

**Issue by hyhajnal** [ElemeFE/mint-ui#638]
LoadMore 下拉组件当里边嵌套的是简单的list(p)时还流畅，但如果嵌套的一个内容比较多的list时（cardlist）会卡顿
在Chrome模拟器上流畅，但换到手机上就卡顿，不知道大家有没有碰到类似的问题

**Comment by hyhajnal** [comment]
why？

**Comment by galenyuan** [comment]
无法避免，你自己也说了Chrome模拟器上流畅 手机上就卡顿，这种性能的优化Mint本身是做不了的，只能通过开发者自行处理解决

**Comment by limichange** [comment]
该css造成了卡顿，至于为什么还没有搞清楚。卡顿主要发生在安卓上，nexus7（2014）、小米4C上很明显。去除该css后卡顿消失。
```css
.mint-loadmore {
    overflow: hidden
}
```

**Comment by Lamborshea** [comment]
我也遇到这个问题，列表循环 card 的时候，card 的内容偏多， 就会出现卡顿，安卓手机几乎不能继续下拉刷新，ios 则没有这个问题。

**Comment by xiaocheng555** [comment]
遇到相同问题，当列表数据超过800+时，列表滑动不顺畅，出现掉帧的现象。
我的解决方法：在touchstart事件中加passive: true 来优化滚动的性能，具体要改动源码。
在node_modules/mint-ui/lib/mint-ui.common.js目录下修改：
![image](https://user-images.githubusercontent.com/19643785/53944237-eab0cb00-40f9-11e9-92a8-b9900967531a.png)

【只是在touchstart事件中加{passive: true} 】
