### ISSUE TITLE
picker组件设置showToolbar为true时报错,为false时无问题

### ISSUE THREAD

**Issue by DwyaneYu** [ElemeFE/mint-ui#639]
1、picker组件设置showToolbar为true时报错,为false时无问题
2、DatetimePicker组件默认隐藏, 自带open()方法用于点击后显示,且自带确认、取消按钮，为何picker组件没有？
求解答，谢谢！

**Comment by galenyuan** [comment]
1. 无法重现，请提供Online Demo / 代码 / 报错信息
2. 请仔细阅读文档http://mint-ui.github.io/docs/#!/zh-cn2/picker
