### ISSUE TITLE
使用index-list组件数据非常多时iphone6和6plus会崩溃，微信端微信直接闪退，Safari也是

### ISSUE THREAD

**Issue by wuyang158158** [ElemeFE/mint-ui#641]
### What is actually happening?

**Comment by galenyuan** [comment]
"非常多"是多少呢?

**Comment by wuyang158158** [comment]
大概是超过300张这样高度的名片。
发自网易邮箱大师
在2017年02月16日 22:49，Galen 写道：

"非常多"是多少呢?

**Comment by wuyang158158** [comment]
dom名片的高度是相当于750px宽的移动端设计稿高度是175px，大约到了300张就闪退了
