### ISSUE TITLE
2.1.1 运行报错

### ISSUE THREAD

**Issue by Ale-cc** [ElemeFE/mint-ui#643]
命令行历史：
  502  git clone https://github.com/ElemeFE/mint-ui.git
  503  cd mint-ui/
  504 npm install
  505  npm run dev
**然后即便运行 npm run dist也不行，照着报错是，在example下面找到了几个vue文件最后一行没有换行，但是报错依旧**。
`
$ npm run dev

> mint-ui@2.1.1 dev E:\Vue_project\mint-ui
> npm run bootstrap && npm run build:entry && cooking watch -c build/cooking.demo.js -p

> mint-ui@2.1.1 bootstrap E:\Vue_project\mint-ui
> yarn || npm i

'yarn' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\f                          sevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":                          "darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN buble-loader@0.3.2 requires a peer of buble@^0.14.0 but none was installed.
npm WARN cooking@1.5.0 requires a peer of babel-core@^6.0.0 but none was installed.
npm WARN cooking@1.5.0 requires a peer of babel-loader@^6.0.0 but none was installed.
npm WARN cooking@1.5.0 requires a peer of css-loader@^0.24.0 but none was installed.
npm WARN cooking@1.5.0 requires a peer of extract-text-webpack-plugin@1 || 2.0.0-beta.4 but none was                           installed.
npm WARN cooking@1.5.0 requires a peer of postcss-loader@^1.0.0 but none was installed.

> mint-ui@2.1.1 build:entry E:\Vue_project\mint-ui
> node build/bin/build-entry

[build entry] DONE: E:\Vue_project\mint-ui\src\index.js

[cooking@1.5.0] - Loaded success: vue2
[cooking@1.5.0] - Loaded success: lint
[cooking@1.5.0] - Loaded success: saladcss
[cooking@1.5.0] - Loaded success: buble

[cooking@1.5.0] - Loading server...
[cooking@1.5.0] - Listening at http://10.0.0.13:8790

WARNING in ./example/pages/palette-button.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\example\pages\palette-button.vue:69:2
  /* HTML */
    ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./packages/loadmore/src/loadmore.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\packages\loadmore\src\loadmore.vue:354:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./packages/loadmore/index.js 1:0-45
 @ ./src/index.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./packages/popup/src/popup.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\packages\popup\src\popup.vue:151:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./packages/popup/index.js 1:0-42
 @ ./src/index.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./packages/toast/src/toast.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\packages\toast\src\toast.vue:103:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./packages/toast/src/toast.js 3:34-56
 @ ./packages/toast/index.js
 @ ./src/index.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js
webpack: Failed to compile.
webpack: Compiling...

ERROR in ./example/pages/palette-button.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\example\pages\palette-button.vue:69:2
  /* HTML */
    ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./packages/loadmore/src/loadmore.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\packages\loadmore\src\loadmore.vue:354:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./packages/loadmore/index.js 1:0-45
 @ ./src/index.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./packages/popup/src/popup.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\packages\popup\src\popup.vue:151:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./packages/popup/index.js 1:0-42
 @ ./src/index.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./packages/toast/src/toast.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  E:\Vue_project\mint-ui\packages\toast\src\toast.vue:103:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./packages/toast/src/toast.js 3:34-56
 @ ./packages/toast/index.js
 @ ./src/index.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.0.0.13:8790/ webpack/hot/dev-server ./example/entry.js
webpack: Failed to compile.
`

**Comment by necfol** [comment]
+1

**Comment by necfol** [comment]
@Ale-cc  你可以使用yarn装一下，yarn install -> npm run dev,这样是ok的

**Comment by Ale-cc** [comment]
@necfol 谢谢了，yarn可以安装的。 刚好中午我也找到原因了，mint-ui是用他们自己的构建工具 cooking@1.2.12打包的。 ^_^

**Comment by necfol** [comment]
双击666，扎心了，老铁

**Comment by QingWei-Li** [comment]
这是 eslint-plugin-vue 升级规则导致的，需要在每个文件末尾加换行

**Comment by Ale-cc** [comment]
@QingWei-Li 命令行提示Listening at http://10.0.0.22:8790，但是打不开，我就不知道是哪个端口号了
