### ISSUE TITLE
Search获取焦点时，placeholder的文字被截断

### ISSUE THREAD

**Issue by caoyr** [ElemeFE/mint-ui#644]
Mint UI version

V2.1.1

Device model

ios 10.1.1 safari

What is actually happening?

Search组件获取焦点时，如果placeholder的文字比较长（如下, 搜索的“索”被截断），后面的文字会被截断不显示。
获取焦点时，
![2](https://cloud.githubusercontent.com/assets/16284105/23054497/31639d70-f51b-11e6-8930-76ebf9cb47c7.png)

未获取焦点时，
![1](https://cloud.githubusercontent.com/assets/16284105/23054503/388f1e26-f51b-11e6-8ad3-bcdce065c4e1.png)

**Comment by galenyuan** [comment]
fixed in #756
