### ISSUE TITLE
按需加载报错，提示未注册name

### ISSUE THREAD

**Issue by junjieit** [ElemeFE/mint-ui#645]
使用官方教程的按需加载，在main.js文件引入了Navbar, TabItem等
`
import { Progress,Toast,Search,Popup,Range,Navbar, TabItem } from 'mint-ui';
Vue.component(Progress.name, Progress);
Vue.component(Toast.name, Toast);
Vue.component(Search.name, Search);
Vue.component(Popup.name, Popup);
Vue.component(Range.name, Range);
Vue.component(Navbar.name, Navbar);
Vue.component(TabItem.name, TabItem);
`

在需要使用Navbar, TabItem的.vue文件中 使用报错。
`
<mt-navbar v-model="selected">
            <mt-tab-item id="1">登录</mt-tab-item>
            <mt-tab-item id="2">注册</mt-tab-item>
          </mt-navbar>
          
          <mt-tab-container v-model="selected">
            <mt-tab-container-item id="1">
              <mt-cell v-for="n in 10" :title="'内容 ' + n" />
            </mt-tab-container-item>
            <mt-tab-container-item id="2">
              <mt-cell v-for="n in 4" :title="'测试 ' + n" />
            </mt-tab-container-item>
          </mt-tab-container>
`
![image](https://cloud.githubusercontent.com/assets/12372886/23093252/c022f648-f618-11e6-8761-1ae107d916c3.png)

.babelrc 文件 
`{
  "presets": [
    ["es2015", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime",["component", [
    {
      "libraryName": "mint-ui",
      "style": true
    }
  ]]],
  "comments": false,
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}
`

**Comment by junjieit** [comment]
是因为使用了TabContainer, TabContainerItem 做面板切换，而没导入

**Comment by Foreverofh** [comment]
@junjieit  tab-container和Tabbar怎么默认显示第一页？

**Comment by junjieit** [comment]
@Foreverofh <mt-navbar v-model="selected">  设置 selected 为 1 就可以了。
