### ISSUE TITLE
根据文档的开始去引入，提示找不到模块

### ISSUE THREAD

**Issue by SkyeTang** [ElemeFE/mint-ui#65]
根据文档的描述，如下引用：
`import Vue from 'vue';

import Mint from 'mint-ui';

Vue.use(Mint);`
总是提示我找不到模块，请问我该如何排查问题哇。

**Comment by Leopoldthecoder** [comment]
请问具体的提示是什么？可以复制上来吗？

**Comment by QingWei-Li** [comment]
已修复
请使用 0.1.5
