### ISSUE TITLE
Indicator被新的覆盖层遮挡了，如何修改Indicator的z-index？

### ISSUE THREAD

**Issue by wonghoman** [ElemeFE/mint-ui#650]
你好，Indicator被新的覆盖层遮挡了，如何修改Indicator的z-index？
我是用以下的代码使用Indicator的，设置元素z-index我也想到了，但就是不知道怎么修改，难道跑去改源码？望指教
`import { Indicator } from 'mint-ui'; `
`Indicator.open('加载中...');`

**Comment by Leopoldthecoder** [comment]
直接加条 CSS

**Comment by wonghoman** [comment]
@Leopoldthecoder 如何直接加？能根据Indicator加z-index举个例子吗？非常感谢！

**Comment by wonghoman** [comment]
@Leopoldthecoder 已解决，非常感谢！

**Comment by DevinLwx** [comment]
同样遇到这个问题，同学是怎么解决的？

**Comment by RobotJohns** [comment]
代码贴出来 看看哇

**Comment by RobotJohns** [comment]
解决方法 https://blog.csdn.net/nicepainkiller/article/details/89406344
