### ISSUE TITLE
lazy-load一直是加载中状态 

### ISSUE THREAD

**Issue by arronf2e** [ElemeFE/mint-ui#657]
### Mint UI version
2.1.1
### Device model

android webview
### What is Expected?
正常懒加载
### What is actually happening?
PC上正常， 安卓机测的时候，一直是加载状态，加载不出来 

![http://o9xap42x4.bkt.clouddn.com/WechatIMG42.jpeg](http://o9xap42x4.bkt.clouddn.com/WechatIMG42.jpeg)

**Comment by galenyuan** [comment]
请提供具体报错信息/重现方式
