### ISSUE TITLE
vue更新到版本2.2.1后，Popup 以及MessageBox的背景色没有了

### ISSUE THREAD

**Issue by lwfyiwei** [ElemeFE/mint-ui#662]
Mint UI version
2.1.1

Vue version
2.2.1

vue更新到版本2.2.1后，MessageBox 以及Popup的背景没有了，请帮忙看下，多谢

**Comment by QingWei-Li** [comment]
Vue 2.2 的 break change 太多还来不及更新，建议继续使用 2.1.10

**Comment by psaren** [comment]
先用回2.1.10 
npm install vue@2.1.10 vue-template-compiler@2.1.10

**Comment by galenyuan** [comment]
fixed in #665
