### ISSUE TITLE
vue2.0以上，popup顶部弹层问题

### ISSUE THREAD

**Issue by files3** [ElemeFE/mint-ui#664]
### What is actually happening?
使用popup组件，设置position为top，想做官网展示的那种效果，顶层有一个50px的背景层，设置了v-model的值为true时，背景整个页面都有，设置为false顶部中间一小块
<img width="761" alt="wx20170227-183450 2x" src="https://cloud.githubusercontent.com/assets/15240870/23358323/7ca8c112-fd1c-11e6-80f3-a44efab7f7c3.png">
<img width="519" alt="wx20170227-183332 2x" src="https://cloud.githubusercontent.com/assets/15240870/23358333/859e444a-fd1c-11e6-979b-042841914e88.png">

**Comment by Leopoldthecoder** [comment]
自己加 `width: 100%`
