### ISSUE TITLE
MessageBox没有显示遮罩层

### ISSUE THREAD

**Issue by wanrengang** [ElemeFE/mint-ui#671]
我本地MessageBox没有显示遮罩层   但我看官方demo是有的，我下载的是最新2.1.1版本。
![image](https://cloud.githubusercontent.com/assets/9476557/23452672/202e4328-fea0-11e6-9102-a6b33ce1caab.png)
 
官方demo会生成一个<div class="v-modal" style="z-index: 1000;"></div>而我本地的没有

**Comment by galenyuan** [comment]
暂时不要升级vue 2.2.1

**Comment by koronero** [comment]
同样遇到这问题，是mint-ui 2.2.1的问题还是vue 2.2.1的问题啊？

**Comment by wanrengang** [comment]
是升级mint-ui 2.2.1

**Comment by koronero** [comment]
目前我是先暂时把vue和vue-template-compiler版本降到2.1.10

**Comment by hopkinson** [comment]
降了版本都不行

**Comment by galenyuan** [comment]
已发布最新版本，更新即可恢复

**Comment by aguegu** [comment]
刚为这个问题挠头，突然发现刚刚修复了～

**Comment by wanrengang** [comment]
@koronero  我试下
