### ISSUE TITLE
时间选择工具设置了开始时间之后出现了问题

### ISSUE THREAD

**Issue by AdoneZ** [ElemeFE/mint-ui#676]
用时间对象设置了startDate之后，拖动年份，月和日同样会动，然后点确定，返回的日期和我选择的日期不一致

**Comment by galenyuan** [comment]
请提供重现demo

**Comment by AdoneZ** [comment]
大概就是这个样子的：
`<mt-datetime-picker
      ref="picker"
      type="date"
      :start-date="cpStartDate"
      :end-date="cpEndDate"
      v-model="pickerDate"
      @confirm="setBirthday">
    </mt-datetime-picker>`

`data () {
      return {
        tempData: null,
        title: '设置',
        pickerDate: null,
        nicknameMaxLength: 10,
        usernameMaxLength: 6,
        introMaxLength: 30,
        valueLength: 0,
        bloods: ['A', 'B', 'AB', 'O'],
        relationships: ['单身', '热恋', '已婚'],
        educations: ['研究生', '本科', '专科', '中专', '高中', '初中', '小学'],
        statuses: ['幸福', '开心', '无感', '忧伤', '悲哀'],
        dataType: null
      }
    },
    computed: {
      cpStartDate () {
        let thisDate = new Date()
        let startYear = parseInt(thisDate.getFullYear()) - 100
        let tempStartDate = new Date()
        tempStartDate.setFullYear(startYear)
        return tempStartDate
      },
      cpEndDate () {
        return new Date()
      }
    },
    methods:{
      setBirthday () {
        this.tempData = this.pickerDate.getFullYear() + '-' + (this.pickerDate.getMonth() + 1) + '-' + this.pickerDate.getDay()
      },
    },
    mounted () {
      this.pickerDate = this.cpEndDate
    }`
