### ISSUE TITLE
想咨询一下，是否有官网实例中，Picker 关于省市地址的具体实现，能否提供下其在vue文件中使用源码。

### ISSUE THREAD

**Issue by zhuqiuyang** [ElemeFE/mint-ui#68]
![image](https://cloud.githubusercontent.com/assets/14734729/15861235/84e25936-2cfe-11e6-964b-f6b3b1f047e9.png)

新手，学习中，如果有的话，十分感谢啦~

**Comment by Leopoldthecoder** [comment]
有的，请移步[这里](https://github.com/ElemeFE/mint-ui/blob/master/example/pages/picker.vue)

**Comment by zhuqiuyang** [comment]
谢谢啦 我看下。
