### ISSUE TITLE
组件swipe与tab-container一起使用出现的bug

### ISSUE THREAD

**Issue by zhao-ping** [ElemeFE/mint-ui#680]
mint-ui的`swipe`和`tab-container`一起用的时候，tab-container的`swipeable=true`的时候，滑动切换swipe内容时，会触发tab-container的切换事件,不仅仅swipe内容切换了，tab-container也切换了。
建议传递一个阻止冒泡的参数，当滑动`swipe`时，阻止`tab-container`的切换事件

示意图（gif图传不上去怎么回事？）

![Uploading bug.gif…]()
![Uploading bug.png…]()

**Comment by zhao-ping** [comment]
![Uploading bug.png…]()

**Comment by galenyuan** [comment]
fixed in #681
