### ISSUE TITLE
DatePicker组件按需引入后使用时样式错乱，全部引入没有问题。请问怎么解决呢？

### ISSUE THREAD

**Issue by wsqy182** [ElemeFE/mint-ui#682]
![image](https://cloud.githubusercontent.com/assets/17962227/23641488/0894f6a6-032f-11e7-915b-72607ab73ffc.png)
截图中是DatePicker组件按需引入后弹出时的样式错乱，全部引入的话和官网的Demo一样。我们希望继续使用DatePicker组件的按需引入，请问有什么解决方案呢？
-------------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/17962227/23641714/050b4f74-0331-11e7-9c9a-f416d05e18cb.png)
这是在我项目中全部引入后的效果，和官网一样。
-------------------------------------------------------------------------------------------------------------------
下面是main.js中引入的mintUI的组件代码

/**
 * mintUI按需引入
 */
//actionsheet组件
import {Actionsheet} from 'mint-ui';
import 'mint-ui/lib/actionsheet/style.css';
Vue.component(Actionsheet.name, Actionsheet);
// loadMore组件
import { Loadmore } from 'mint-ui';
import 'mint-ui/lib/loadmore/style.css';
Vue.component(Loadmore.name, Loadmore);
//滚动条组件
import { Spinner } from 'mint-ui';
import 'mint-ui/lib/spinner/style.css';
Vue.component(Spinner.name, Spinner);
//日期选择器组件
import { DatetimePicker } from 'mint-ui';
import 'mint-ui/lib/datetime-picker/style.css';
Vue.component(DatetimePicker.name, DatetimePicker);

//mintUI全部引入
// import MintUI from 'mint-ui'
// import 'mint-ui/lib/style.css'
// Vue.use(MintUI)

-------------------------------------------------------------------------------------------------------------------
剩下的组件代码就没贴了，因为也是从Github上抠的

**Comment by galenyuan** [comment]
贴一下代码

**Comment by wsqy182** [comment]
下面是main.js中引入的mintUI的组件

/**
 * mintUI按需引入
 */
//actionsheet组件
import {Actionsheet} from 'mint-ui';
import 'mint-ui/lib/actionsheet/style.css';
Vue.component(Actionsheet.name, Actionsheet);
// loadMore组件
import { Loadmore } from 'mint-ui';
import 'mint-ui/lib/loadmore/style.css';
Vue.component(Loadmore.name, Loadmore);
//滚动条组件
import { Spinner } from 'mint-ui';
import 'mint-ui/lib/spinner/style.css';
Vue.component(Spinner.name, Spinner);
//日期选择器组件
import { DatetimePicker } from 'mint-ui';
import 'mint-ui/lib/datetime-picker/style.css';
Vue.component(DatetimePicker.name, DatetimePicker);

----------------------------------------------------------------------

**Comment by wsqy182** [comment]
@galenyuan 
还需要什么代码么？你是我在Github上提问第一个回答的人哎

**Comment by galenyuan** [comment]
暂时先加上
`import 'mint-ui/lib/picker/style.css';`
因为DatetimePicker是依赖picker的，但自己的样式又没有包含picker的样式

**Comment by galenyuan** [comment]
建议组件可以单独引用，但css还是引用全局的，Mint内部很多组件都是相互依赖的

**Comment by wsqy182** [comment]
@galenyuan 
谢谢你的建议，试了一下，除了颜色和官网不一样，展现形式已经是对的了。
![image](https://cloud.githubusercontent.com/assets/17962227/23641849/e76a6a4e-0331-11e7-9516-e6384b9587f1.png)
等会尝试下css引用全局的。

**Comment by wsqy182** [comment]
OK，已经解决了。

**Comment by galenyuan** [comment]
先不要close，我回头要跟其他人讨论一下这个问题是否有解

**Comment by nk097** [comment]
你好，请问你是直接复制文档上的模板下来的吗
如
<mt-datetime-picker
  v-model="pickerVisible"
  type="date"
  year-format="{value} 年"
  month-format="{value} 月"
  date-format="{value} 日">
</mt-datetime-picker>

是可以正常打开吗？

**Comment by galenyuan** [comment]
忽然想起来了，文档里有写，做按需引入需要按照文档中这样做 https://github.com/ElemeFE/mint-ui#babel-plugin-component
