### ISSUE TITLE
swipe和tab-container一起使用出现的BUG

### ISSUE THREAD

**Issue by zhao-ping** [ElemeFE/mint-ui#684]
当`mint-ui`的`Swipe`组件和`tab-container`组件一起使用，并且`swipeable=true`的时候，滑动`swipe`切换内容将会同事也触发`tab-container`的切换事件，bug示意例子链接如下：

[bug示意例子链接](https://zhao-ping.github.io/Panda-Travel/#/find)
（请用手机模式查看）

建议给`swipe`组件一个默认的参数，滑动`swipe`时，阻止冒泡`stopPropagation() `

**Comment by galenyuan** [comment]
#681
