### ISSUE TITLE
loadmore与tab-container一起使用时出现的bug

### ISSUE THREAD

**Issue by zhao-ping** [ElemeFE/mint-ui#686]
`loadmore`与`tab-container`一起使用，并且`swipeable==true`时，在`loadmore`区域想要切换`tab-container`,不能够切换的到

[bug例子地址](https://zhao-ping.github.io/Panda-Travel/#/find)

**Comment by Shadownc** [comment]
楼主 能不能加下你qq 问一下loadmore的问题

**Comment by zhao-ping** [comment]
有什么问题？在这里问一样的啊，而且，我也只是个菜鸟。

**Comment by WenRuGu** [comment]
我也是这两个一起用，我左右滑动，滑动不了，只能上下拉，什么情况？我看楼主的可以

**Comment by WenRuGu** [comment]
看了一下，内容没满屏时，allLoaded为false时，滑动不了。滑动角度也不行，不能调整一下
