### ISSUE TITLE
项目无法运行:

### ISSUE THREAD

**Issue by tiger8888** [ElemeFE/mint-ui#690]
1.下载下来,开始npm install:
  "extract-text-webpack-plugin": "beta",
报错,打不到相应的包. 这个总是搞好后,接着npm run dev,又是各种lint错误 
WARNING in ./example/pages/lazyload.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found  
  /Users/nova/Work/Vue/mint-ui-master/example/pages/lazyload.vue:55:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.1.6.190:8790/ webpack/hot/dev-server ./example/entry.js

WARNING in ./example/pages/palette-button.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found  
  /Users/nova/Work/Vue/mint-ui-master/example/pages/palette-button.vue:69:2
  /* HTML */
    ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.1.6.190:8790/ webpack/hot/dev-server ./example/entry.js

WARNING in ./example/pages/picker.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found  
  /Users/nova/Work/Vue/mint-ui-master/example/pages/picker.vue:178:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.1.6.190:8790/ webpack/hot/dev-server ./example/entry.js

WARNING in ./example/pages/progress.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found  
  /Users/nova/Work/Vue/mint-ui-master/example/pages/progress.vue:99:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.1.6.190:8790/ webpack/hot/dev-server ./example/entry.js

WARNING in ./example/pages/range.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found  
  /Users/nova/Work/Vue/mint-ui-master/example/pages/range.vue:118:10
  /* HTML */
            ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.1.6.190:8790/ webpack/hot/dev-server ./example/entry.js

WARNING in ./example/pages/spinner.vue

  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found  
  /Users/nova/Work/Vue/mint-ui-master/example/pages/spinner.vue:43:9
  /* HTML */
           ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/eol-last
 @ ./example ^\.\/pages.*$
 @ ./example/route.js
 @ ./example/entry.js
 @ multi webpack-dev-server/client?http://10.1.6.190:8790/ webpack/hot/dev-server ./example/entry.js

ERROR in ./example/route.js

  搞好后,运行了,结果页面无任何显示 ......,控制台报错:
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (eval at ./src/index.js (app.js:4218), <anonymous>:119:16)
    at eval (eval at ./src/index.js (app.js:4218), <anonymous>:157:30)
    at Object../src/index.js (app.js:4218)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at eval (eval at ./node_modules/buble-loader/index.js?objectAssign=Object.assign&jsx=h!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./example/pages/toast.vue (app.js:1227), <anonymous>:2:68)
    at Object../node_modules/buble-loader/index.js?objectAssign=Object.assign&jsx=h!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./example/pages/toast.vue (app.js:1227)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at eval (eval at ./example/pages/toast.vue (app.js:963), <anonymous>:7:3)

**Comment by wx85745997** [comment]
我昨天刚弄好的 
装个yarn
npm i  yarn -g
然后他又会自动装个cooking   build里的文件会变掉
在 run dev 不行就node_modules删了 
多试几次
昨天晚上最后run dev的时候还有一堆红色的报错 但是打开来有页面都可以跑了  就刚刚又run dev看了下 一个报错都没了 真神奇。。。

**Comment by galenyuan** [comment]
把node_modules删掉然后npm run dev，不要npm install

**Comment by yuanyuanshen** [comment]
问题怎么解决的就closed了？

**Comment by DNA643** [comment]
@yuanyuanshen 按照楼上说的就可以正常运行，我环境是装了yarn。

> 把node_modules删掉然后npm run dev，不要npm install

**Comment by yuanyuanshen** [comment]
@DNA643 不行啊，我也安装yarn，用npm run dev
安装提示package。json中有几个包bata版本太低报错，只能重新选版本号。我选了最高版本。但是说要在每行后面加换行。就报错跑不起来。醉了

**Comment by zhangxinmiao-study** [comment]
我用 npm run dev 跑也不行 也安装了yarn 请问楼主webpack版本是多少呢
