### ISSUE TITLE
MessageBox modal层点击关闭整个MessageBox

### ISSUE THREAD

**Issue by NotGeekAtAll** [ElemeFE/mint-ui#699]
### Mint UI version
2.2.0
### Reproduction Link
http://jsbin.com/roluwoqepu/edit?html,output

### What is Expected?
这类反馈类对话操作框的modal不应该点击modal层关闭，希望可以提供一个api控制，或不然他点击modal关闭。
### What is actually happening?
点击modal层关闭MessageBox

---
好吧，有这个参数closeOnClickModal控制点击modal关闭的，文档没有，看源码找到了，不过默认参数为true，我觉得这类控件在移动端点击modal框关闭的需求不多，默认为false比较好，所以先不关闭issue了

**Comment by wanrengang** [comment]
为什么我的边messageBox显示是 model没显示，没有背景色

**Comment by galenyuan** [comment]
@wanrengang 用最新版本的Mint

**Comment by galenyuan** [comment]
@NotGeekAtAll 这是文档的缺陷，晚点我会去把文档补上

**Comment by NotGeekAtAll** [comment]
@galenyuan 是否把这个参数默认为false

**Comment by galenyuan** [comment]
@NotGeekAtAll 不会，在我们的使用场景中都是点击遮罩就关闭popup的，我们还是认为大部分场景都是点击遮罩则关闭popup的，而且现有版本都是这样的，我们也不会在没有bug的情况下改变默认参数值
