### ISSUE TITLE
建议集成表单验证插件类似PC端的那样,很实用的功能!

### ISSUE THREAD

**Issue by dmlzj** [ElemeFE/mint-ui#700]
建议集成表单验证插件类似PC端的那样,很实用的功能....!

**Comment by galenyuan** [comment]
这个功能跟Mint的定位不符

**Comment by alosin** [comment]
建议集成表单验证插件类似PC端的那样,很实用的功能！TOO
加上并不会影响什么

**Comment by dmlzj** [comment]
@galenyuan 多么冠冕堂皇的帽子。。。。你们的领导就是这样说的吗？

**Comment by galenyuan** [comment]
第一，麻烦你分清“组件库”和“功能插件”的本质区别，如果分不清，你可以多读点书
第二，这个库跟我的工作没有一毛钱关系，完全是我个人利用“私人时间”在维护
第三，我求你别用了，你的智商跟本仓库的定位不符
@dmlzj

**Comment by galenyuan** [comment]
btw: 麻烦你分清“Collaborator”， "Member", "Owner" 的区别
