### ISSUE TITLE
使用 Cell Swipe 时，初次加载 会报错，右侧的红色删除按钮会出现

### ISSUE THREAD

**Issue by xuxia2013** [ElemeFE/mint-ui#702]
[Vue warn]: Error when evaluating expression "_slotContents.icon": TypeError: Cannot read property 'icon' of undefined (found in component: <mt-cell-swipe>)

**Comment by galenyuan** [comment]
请提供具体代码，从报错信息看是你的代码有问题

**Comment by xuxia2013** [comment]
` <mt-cell-swipe
          title="标题文字" icon="more"
          :right="[
            {
              content: 'Delete',
              style: { background: 'red', color: '#fff' },
              handler: () => this.$messagebox('delete')
            }
          ]"></mt-cell-swipe>
import { CellSwipe } from 'mint-ui/lib'`

**Comment by xuxia2013** [comment]
@galenyuan 直接引用的，并没有什么特别的

**Comment by xuxia2013** [comment]
@galenyuan "mint-ui": "^1.0.2"

**Comment by galenyuan** [comment]
vue版本？

**Comment by xuxia2013** [comment]
@galenyuan "vue": "^1.0.7",

**Comment by galenyuan** [comment]
...两个版本都太老了，已不再维护，建议用最新版本或自己查一下源码吧

**Comment by zhaowanhua** [comment]
"vue": "^2.0.1",
"mint-ui": "^2.2.12"
出现了同样的问题，但是只有安卓会出现，在杀掉app之后，再次打开，cell-swipe的右侧按钮会覆盖上层
