### ISSUE TITLE
picker组件做省市联动出现的bug

### ISSUE THREAD

**Issue by gg343917542** [ElemeFE/mint-ui#704]
mint-ui版本2.0.5的picker组件有一个bug,我的项目有一个三级省市区联动,省市区的数据是一个树形结构的数据(例:{children:{name:'广东',children:[{name:'广州',children:
[{name:'天河区',children:[]}]}]}}),slots的第一个solt的values给address.children,第二个solt的values给address.children[0].children,第三个slot的values给address.children
[0].children[0].children。当滑动第二或第三个slot的时候,触发change事件传入的values的第一个参数是undefined。但滑动第一slot则不是undefined。

### Mint UI version
2.0.5

**Comment by watonyweng** [comment]
Please provide jsFiddle url for the issue @gg343917542

**Comment by hopkinson** [comment]
这个不是bug
