### ISSUE TITLE
mt-cell 无法触发click事件 换成:to 则无法获取到params参数

### ISSUE THREAD

**Issue by dadiu** [ElemeFE/mint-ui#706]
click事件：

<mt-cell v-for="team in myTeamLists"
                            :key="team"
                            :title="team.name"
                            :label="team.id"
                            class="my-cell"
                            @click="openMemberListFn(team.num)"
                            is-link>
                        </mt-cell>

to参数：

<mt-cell v-for="team in myTeamLists"
                            :key="team"
                            :title="team.name"
                            :label="team.code"
                            class="my-cell"
                            is-link
                            :to="{name : 'teamDetail', params : {group_id : '111'}}">
                        </mt-cell>

**Comment by neelee** [comment]
在 Vue 2.0 中，为自定义组件绑定原生事件必须使用 .native 修饰符：
<my-component @click.native="handleClick">Click Me</my-component> 官方文档有说
