### ISSUE TITLE
Cell Swipe无法遍历使用

### ISSUE THREAD

**Issue by yhostc** [ElemeFE/mint-ui#707]
在实际应用时，期望可以遍历cell-swipe，但是目前使用v-for遍历就会异常，遇到handler无法执行的问题，似乎是上下文和全局变量都没法使用了，原因不明。

### Mint UI version
版本：^2.0.4
### Device model

Chrome 55.0.2883.95 (64-bit)
### Reproduction Link

示例代码在这里，暂时没有找到有啥方法可以直接输出HTML在手机上预览，所以只能土一点儿的办法，用Chrome来调试了。
[https://jsfiddle.net/yhostc/rj9j29no/5/](https://jsfiddle.net/yhostc/rj9j29no/5/)

### What is Expected?
期望handler可以正常响应。
### What is actually happening?
```
VM1961:6 Uncaught TypeError: this.$messagebox is not a function
    at Object.handler (eval at makeFunction (vue.js:8815), <anonymous>:6:27)
    at click (index.js:4)
    at HTMLAnchorElement.invoker (vue.js:1641)
</code>
```

**Comment by galenyuan** [comment]
保持现有的写法就把`this.$messagebox('delete')`改成`$messagebox('delete')`
也可以按文档中的写法，绑定到一个变量上http://mint-ui.github.io/docs/#!/zh-cn2/cell-swipe

**Comment by yhostc** [comment]
我的目的是handler去执行methods中的方法，可以介绍一下绑定到变量的方式，或者给你一个简单的例子吗？谢谢！

**Comment by galenyuan** [comment]
https://github.com/ElemeFE/mint-ui/blob/master/example/pages/cell-swipe.vue#L15
