### ISSUE TITLE
建议增加`bower.json`, 可以使用bower下载到本地,便于 script 引用 

### ISSUE THREAD

**Issue by cycold** [ElemeFE/mint-ui#708]
如题

like: https://github.com/vuejs/vuex/blob/dev/bower.json

> 主要是每次从公用CDN加载,在开发时由于没有启用缓存, 每次都很慢,
   所以希望可以通过`bower`安装到本地, 当发布到产品环境时再切换到公用CDN

> 为什么不从`node_modules`中引用? 
  1.文件路径引用过于麻烦
  2.感觉有点不合适

**Comment by galenyuan** [comment]
什么意思？你可以直接引本地的文件啊，又不是非要引cdn上的

**Comment by QingWei-Li** [comment]
@cycold PR welcome

**Comment by galenyuan** [comment]
不好意思 刚才没反应过来，你是需求一个bower源吧，可以PR，我们会发布，虽然我还是建议你用npm

**Comment by cycold** [comment]
是的, 希望增加一个bower源, 可以`bower install mint-ui` 

像可以`bower install vue vuex vue-router` 

```
    <script src="static/bower_components/vue/dist/vue.runtime.min.js"></script>
    <script src="static/bower_components/vuex/dist/vuex.min.js"></script>
    <script src="static/bower_components/vue-router/dist/vue-router.min.js"></script>
    <script src="node_modules/mint-ui/lib/index.js"></script>
```

因为我只是设置了static为express的静态文件目录 
同时将来传到服务时, 是没有`node_modules`文件夹中, 所以我需要去`node-modules`中将`mint-ui`手动复制到static/bower_components目录下.

主要是不想将`mint-ui`, `vue`, `vuex`, `vue-router`打包

**Comment by galenyuan** [comment]
PR welecome，我们会做发布

**Comment by cycold** [comment]
sorry 
我这边 不好做`PR` 
如果你们有时间,不忙的话, 可以注册一下 (你们那边直接注册方便很多)

https://bower.io/docs/creating-packages/#register

如果没有时间或者不想设置的话,也没关系;
毕竟开源维护一个库是需要很花时间与精力的,也没有义务满足每一个人的需求
之前用过https://github.com/ElemeFE/element 
真的非常好用
