### ISSUE TITLE
Datetime picker 在测试环境在谷歌浏览器模拟手机时不可滚动，浏览器警告“Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.”； 发布环境均可滚动

### ISSUE THREAD

**Issue by dadiu** [ElemeFE/mint-ui#710]
如题
代码如下：
 <a href="javascript:;" @click="openDate()">test</a>

<mt-datetime-picker
      ref="picker4"
      type="date"
      v-model="value4"
      year-format="{value} 年"
      month-format="{value} 月"
      date-format="{value} 日"
      @confirm="handleChange">
    </mt-datetime-picker>

import { TabContainer, TabContainerItem, Tabbar, TabItem, DatetimePicker } from 'mint-ui';

    export default {
        name: 'bossData',
        data () {
            return {
                value4 : null,
                value : null
            }
        },
        mounted (){
        },
        methods : {
            openDate(){
                
                this.$refs['picker4'].open();
            },

            handleChange (value){
                console.log(value);
            }
            
        }
    }

**Comment by galenyuan** [comment]
在打开模拟器的情况下刷新。

**Comment by hjdtl** [comment]
我也遇到这个情况，**跳转路由后再回到tabContainer组件**，就不能左右滑动了，也没有报错。非常头痛。我用的版本是2.2.9。

**Comment by Mark24Code** [comment]
同楼上
