### ISSUE TITLE
mt-popup组件低版本ios兼容问题

### ISSUE THREAD

**Issue by abelzeng** [ElemeFE/mint-ui#711]
1.transform会导致fixed失效
2.fixed在虚拟键盘弹出时，不正常关闭页面会卡住
mt-popup用的是transform和fixed，怎么解决？
注：ios 7.1.2

**Comment by galenyuan** [comment]
老生常谈了。。理论上Mint不会再对那些“前端开发的噩梦”做降级兼容了，但如果你愿意提PR修复的话我们还是很高兴的
