### ISSUE TITLE
tabbar和tabcontainer在google模拟器Nexus 5X不能关联

### ISSUE THREAD

**Issue by DarkYeahs** [ElemeFE/mint-ui#715]
添加Better-Scroll组件后会导致tabbar和tabcontainer在google模拟器Nexus 5X不能关联，在iphone模拟器下能够进行关联，同样在iphone safari下能够关联，在小米4s原生浏览器下不能关联
vue版本： 1.0.26
mini-ui版本：1.0.2

**Comment by galenyuan** [comment]
vue和Mint版本都太古老了，已不再维护了，用最新版的吧
