### ISSUE TITLE
datatime picker问题 引入该组件后报错 

### ISSUE THREAD

**Issue by mirkcale** [ElemeFE/mint-ui#719]
![image](https://cloud.githubusercontent.com/assets/19788310/24002159/fa7ebe1c-0a9a-11e7-8b9f-6fb33f2520e9.png)
引入这个组件后就报错 ，也没有做其他操作 ，不知道我是哪里没有配置好，在网上没有找到相同的问题，有哪位知道的告诉下，谢谢了

**Comment by galenyuan** [comment]
信息不足，猜不出来。
