### ISSUE TITLE
Date-Picker init error? "value.getFullYear is not a function"

### ISSUE THREAD

**Issue by goldenfreemanchina** [ElemeFE/mint-ui#720]
### Mint UI version
mint-ui: 2.2.1
vue: 2.2.1

### Device model
Crosswalk with Cordova 4.0;
Debug in chrome57@ubuntu16.04

### What is actually happening?

![default](https://cloud.githubusercontent.com/assets/6322013/24005519/3d0126d0-0a37-11e7-8c71-285096d5509c.jpg)

package.json:

`{...
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "vue": "^2.2.1"
  },
  "devDependencies": {
    "animate.css": "^3.5.2",
    "axios": "^0.15.3",
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-preset-latest": "^6.0.0",
    "cross-env": "^3.0.0",
    "crypto-js": "^3.1.9-1",
    "css-loader": "^0.25.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.9.0",
    "font-awesome": "^4.7.0",
    "less": "^2.7.2",
    "less-loader": "^3.0.0",
    "mint-ui": "^2.2.1",
    "node-sass": "^4.5.0",
    "qr-image": "^3.2.0",
    "sass-loader": "^5.0.1",
    "style-loader": "^0.13.2",
    "vue-chartjs": "^2.5.0",
    "vue-loader": "^11.1.4",
    "vue-router": "^2.3.0",
    "vue-template-compiler": "^2.2.1",
    "webpack": "^2.2.0",
    "webpack-dev-server": "^2.2.0"
  }
}
`

vue code here~
```html
<mt-datetime-picker v-model="selector.date" type="date" year-format="{value} 年" month-format="{value} 月" date-format="{value} 日" cancelText="取消" confirmText="确定" @confirm="datefilter" />
```

Copy from demo...

**Comment by goldenfreemanchina** [comment]
新建空项目使用，直接使用Date-Picker也是一样的报错;
／（ㄒｏㄒ）／～～

**Comment by galenyuan** [comment]
selector.date 初始值是什么？

**Comment by goldenfreemanchina** [comment]
```
selector: {
                store: false,
                date: false
            },
```

**Comment by goldenfreemanchina** [comment]
抱歉，错拿picker的方法用作dataPicker了；已正常....～（＠＾＿＾＠）～,
THX~
