### ISSUE TITLE
[Feature Request] 能否有份icon的说明文档？？？

### ISSUE THREAD

**Issue by ynioba** [ElemeFE/mint-ui#721]
翻了教程，没有。。。或者告诉我代码在哪里也可以。

**Comment by QingWei-Li** [comment]
没有提供 icon

**Comment by ynioba** [comment]
这个问题可以关闭，我仔细的看了一下icon，只有少数几个；
路径在：mint-ui/src/assets/font/iconfont.css

@font-face {font-family: "mintui";
  src: url('iconfont.ttf?t=1464927413')
}

.mintui {
  font-family:"mintui" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 0.2px;
  -moz-osx-font-smoothing: grayscale;
}
.mintui-search:before { content: "\e604"; }
.mintui-more:before { content: "\e601"; }
.mintui-back:before { content: "\e600"; }
.mintui-field-error:before { content: "\e605"; }
.mintui-field-warning:before { content: "\e608"; }
.mintui-success:before { content: "\e602"; }
.mintui-field-success:before { content: "\e609"; }

其实也差不多了。常用的也有了。
