### ISSUE TITLE
DateTimePicker 的取消事件应该怎么调用呢？还是说没有暴露出来？

### ISSUE THREAD

**Issue by wsqy182** [ElemeFE/mint-ui#724]
我有一个功能,就是选择日期时间，当点击取消（假设它担负清空的功能)的时候，需要清空之前选择的内容。
我看了了下nodejs_modules里面的mint-ui模块的的源码;
cancel的click事件里面一句visiable=false就完事了。

应该是取消按钮没暴露出方法。
但是我自己又不会修改。
请问他是否还有什么隐藏的API或者说我的打开方式是错误的？

**Comment by galenyuan** [comment]
值是由你绑定的 model 决定的，你想清空改掉 v-model 就可以了， visiable 是用来控制显示隐藏的，所以你的“取消”功能应该是先把 v-model 值重置，再把 visiable 变为 false

**Comment by sxn126** [comment]
提交的方法是confirm，那么取消的方法呢？

**Comment by wsqy182** [comment]
场景是在webApp下,时间日期的输入如果用v-model,那么这个DateTimePicker 的值就需要放到input标签当中。可是input标签在手机上点击打开，还会弹出一个输入法。这样输入法就把DateTimePicker 位置给顶上去了。只能取消input标签和v-model绑定的形式，使用其他的标签 才能正常的在webApp上正常使用DateTimePicker。我把取消按钮命名为清空，那么我改如何实现这个功能呢？
总结下来：就是楼上问的：提交的方法是confirm，那么取消的方法呢？

**Comment by galenyuan** [comment]
代码：https://github.com/ElemeFE/mint-ui/blob/master/example/pages/datetime-picker.vue#L14
页面：http://elemefe.github.io/mint-ui/#/datetime-picker
取消是不需要你手动做的，我说的 v-model 是绑定在 DatetimePicker 上的，跟你自己的代码没关系，至于结果你想怎么做是你自己的事情，跟 Mint 是无关的，至于你说的唤起键盘的问题，给 input 设置一个 readonly 就可以了。

**Comment by wsqy182** [comment]
ok，了解了，我没有了解到v-model绑定DatetimePicker。谢谢解答。

**Comment by sxn126** [comment]
你们的实例够奇葩的，date-pocker通常都是和input联用的，v-model同时也会和input绑定的。难道只允许date-pocker修改input的值，不允许input反过来修改date-pocker的值

**Comment by galenyuan** [comment]
@sxn126 https://cn.vuejs.org/v2/guide/components.html#使用自定义事件的表单输入组件 好好学习，天天向上， v-model 是 __双向__ 绑定

**Comment by sxn126** [comment]
看你给wsqy182的回复，我理解为：datetime-picker和input需要绑定不同的v-model。或许是我理解错了你的意思。现在我的问题是：我用v-model将一个data同时绑定到datetime-picker和input上，在datetime-picker修改日期后，点取消。input上的日期是修改过的日期，你们并没有提供cancel事件，那么我用什么来还原input的数据？

**Comment by galenyuan** [comment]
@sxn126 实际上就算我暴露一个 cancel 事件出来，你依然需要一个缓存原始值的地方啊，跟两个 model 并没有实质上的区别，除非我在组件内部 cancel 时帮你把 model 还原，但这样又会导致无法满足另一部分使用者的需求

**Comment by sxn126** [comment]
提供一个cancel 事件，可以方便用户做一些想要做的事，并不一定是要还原input的数值，比如，我希望点击取消时，弹出一个提示框来显示一些信息等。我希望的是通过一个v-model来实现双向的修改。既能够通过datetime-picker修改input上的显示，也能通过改变input来改变datetime-picker的默认值，

**Comment by 617450941** [comment]
cancel方法的确需要呀

**Comment by wzc0x0** [comment]
哈哈 有个@visible-change回调 大家都没看到 文档也没写 所以用不到cancel方式的
