### ISSUE TITLE
toast和indicate和popup的z-index关系

### ISSUE THREAD

**Issue by zhao-ping** [ElemeFE/mint-ui#727]
`toast`和`indicate`应该放在`popup`的上方，现在好像是放在下方的

bug：
1.点击`popup`中的内容然后执行`toast`或者`indicate`会被遮盖掉。
2.在`popup`上执行`indicate`，想要在`indicate`隐藏前不能执行任何操作，但是并不能实现，

所以个人认为`toast`和`indicate`应该在放在`popup`上面，

修改建议：
```
.mint-indicator{z-index: 2006;}
.mint-indicator-mask{z-index: 2005;}
.mint-indicator-wrapper{z-index:2007}
.mint-toast.is-placemiddle{z-index: 2008;}
```

**Comment by galenyuan** [comment]
这种需求比较特殊，建议在自己的代码中做修改，在 Mint 中做修改会导致很多已经引入 Mint 的项目发生奇奇怪怪的问题

**Comment by RobotJohns** [comment]
https://blog.csdn.net/nicepainkiller/article/details/89406344
