### ISSUE TITLE
Date Picker在ios下滑动到底部后直接死屏

### ISSUE THREAD

**Issue by hahazexia** [ElemeFE/mint-ui#728]
![mmexport1489977380191](https://cloud.githubusercontent.com/assets/20611129/24087385/30bd20ca-0d59-11e7-9bb7-c34903a2deb7.jpg)

**Comment by hahazexia** [comment]
iphone 6

**Comment by hahazexia** [comment]
iphone 6
ios 10.2.1(14D27)

**Comment by galenyuan** [comment]
见#544
