### ISSUE TITLE
trying make dist, get extract-text-webpack-plugin loader error

### ISSUE THREAD

**Issue by lymanlai** [ElemeFE/mint-ui#73]
ERROR in /Users/${userName}/~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/Users/${userName}/.cooking/~/vue-style-loader!/Users/${userName}/~/css-loader!/Users/${userName}/.cooking/~/vue-loader/lib/style-rewriter.js!/Users/${userName}/.cooking/~/vue-loader/lib/selector.js?type=style&index=0!./src/components/header.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.module.exports.pitch (/Users/${userName}/node_modules/extract-text-webpack-plugin/loader.js:21:9)
     @ ./src/components/header.vue 2:0-324

    ERROR in /Users/${userName}/~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/Users/${userName}/.cooking/~/vue-style-loader!/Users/${userName}/~/css-loader!/Users/${userName}/.cooking/~/vue-loader/lib/style-rewriter.js!/Users/${userName}/.cooking/~/vue-loader/lib/selector.js?type=style&index=0!./src/components/button.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.module.exports.pitch (/Users/${userName}/node_modules/extract-text-webpack-plugin/loader.js:21:9)
     @ ./src/components/button.vue 2:0-324

    ERROR in /Users/${userName}/~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/Users/${userName}/.cooking/~/vue-style-loader!/Users/${userName}/~/css-loader!/Users/${userName}/.cooking/~/vue-loader/lib/style-rewriter.js!/Users/${userName}/.cooking/~/vue-loader/lib/selector.js?type=style&index=0!./src/components/cell.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.module.exports.pitch (/Users/${userName}/node_modules/extract-text-webpack-plugin/loader.js:21:9)
     @ ./src/components/cell.vue 2:0-322

    ERROR in /Users/${userName}/~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/Users/${userName}/.cooking/~/vue-style-loader!/Users/${userName}/~/css-loader!/Users/${userName}/.cooking/~/vue-loader/lib/style-rewriter.js!/Users/${userName}/.cooking/~/vue-loader/lib/selector.js?type=style&index=0!./src/components/field.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.module.exports.pitch (/Users/${userName}/node_modules/extract-text-webpack-plugin/loader.js:21:9)
     @ ./src/components/field.vue 2:0-323

    ERROR in /Users/${userName}/~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/Users/${userName}/.cooking/~/vue-style-loader!/Users/${userName}/~/css-loader!/Users/${userName}/.cooking/~/vue-loader/lib/style-rewriter.js!/Users/${userName}/.cooking/~/vue-loader/lib/selector.js?type=style&index=0!./src/components/badge.vue
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.module.exports.pitch (/Users/${userName}/node_modules/extract-text-webpack-plugin/loader.js:21:9)
     @ ./src/components/badge.vue 2:0-323

**Comment by QingWei-Li** [comment]
Maybe you should upgrade node version. https://github.com/webpack/extract-text-webpack-plugin/issues/173

**Comment by lymanlai** [comment]
@QingWei-Li the same result, after I use nvm and use node v6.2.0

**Comment by QingWei-Li** [comment]
`node_modules` exists in your user homedir. you should delete it.

```shell
/Users/${userName}/node_modules
```
