### ISSUE TITLE
MessageBox怎么写取消和确定的回调事件？

### ISSUE THREAD

**Issue by sijinglei** [ElemeFE/mint-ui#733]
MessageBox怎么写取消和确定的回调事件？我想分别在点击取消和确定后做其他的事该怎么写呢？

**Comment by sijinglei** [comment]
`callback:function(action){
                    if (action =='confirm') {
                       //ok：confirm
                    }else{
                       //cancel：cancel
                       }
                }`

**Comment by ly-lewis** [comment]
这样我试了  不行

**Comment by xiuxxx** [comment]
```
MessageBox.confirm('msg').then((action,index) => {
    if (action === 'confirm') {
         //confirm callback
       ....
    }
    }).catch(err => {
        //cancel callback
       ...
    });;
```
