### ISSUE TITLE
2.2.1的cell-swipe组件有bug

### ISSUE THREAD

**Issue by xing393939** [ElemeFE/mint-ui#734]
页面不能滑动出菜单。使用2.0.6是ok的

**Comment by Molly0920** [comment]
2.2.1也发现了 楼上的问题

**Comment by galenyuan** [comment]
更新版本即可，在v2.2.3修复了

**Comment by liuzhibin123** [comment]
2.2.4版本依然会存在这个问题！
这问题是在按需引用的时候出现的。你们的demo都是全部引用的，所以不会出现这样的问题。
因为我的项目是按需引用的，希望大神能给予解决。

**Comment by galenyuan** [comment]
https://github.com/ElemeFE/mint-ui#babel-plugin-component
文档里有写哦，按需引入需要特殊配置，不加会乱的，试一下，有问题再回复
@xing393939 @Molly0920 都看一下

**Comment by Molly0920** [comment]
已经配置好了
![image](https://cloud.githubusercontent.com/assets/26627730/25259741/8580cc44-267a-11e7-8c3c-08acf33de2d7.png)
![image](https://cloud.githubusercontent.com/assets/26627730/25259782/c580fb52-267a-11e7-8093-e2ba53abfcf9.png)

**Comment by galenyuan** [comment]
@Molly0920 问题依旧存在？

**Comment by Molly0920** [comment]
是的，最新版本的也存在这个问题

**Comment by galenyuan** [comment]
建个仓库吧，我看一下代码

**Comment by Molly0920** [comment]
https://github.com/eaminhu/testOpen.git

**Comment by galenyuan** [comment]
```javascript
Vue.component(CellSwipe.name, Cell);
```
@Molly0920 大兄弟 你在逗我么...

**Comment by Molly0920** [comment]
![image](https://cloud.githubusercontent.com/assets/26627730/25266605/4e9f4780-26a4-11e7-85a4-b9c2434cdf6a.png)

**Comment by galenyuan** [comment]
文档已改正
