### ISSUE TITLE
Radio控件，被选中时，中间的小圆点没有居中

### ISSUE THREAD

**Issue by simon82** [ElemeFE/mint-ui#736]
Radio控件，被选中时，中间的小圆点没有居中。如图：
<img width="148" alt="core" src="https://cloud.githubusercontent.com/assets/11912423/24191315/6a5dc608-0f26-11e7-8cc3-b2b7262622e4.png">

.mint-radio-core::after
top和left为6px时才能居中。

但在MintUI的demo中却是居中的，不知道为什么

**Comment by galenyuan** [comment]
参考 #656

**Comment by simon82** [comment]
这个应该算是mint-ui的bug吧？我需要在.mint-radio-core里添加box-sizing为border-box
