### ISSUE TITLE
关于@reset-global mobile

### ISSUE THREAD

**Issue by simon82** [ElemeFE/mint-ui#737]
前面遇到Radio组件，中间小圆点不居中的情况。
但在官方demo中，显示是正常。
貌似是由于在app.vue中有句代码“@reset-global mobile;”，但这句话并没有在文档中做出说明或指引。希望能给出使用这句代码的详情方法。

谢谢

**Comment by galenyuan** [comment]
http://elemefe.github.io/postcss-salad/reset
其实跟这没什么关系，只是我们默认开发者都会用`border-box`，就忽略了这个问题，我去给圆点加一个border-box就好了

**Comment by simon82** [comment]
好的，谢谢

**Comment by natee** [comment]
@galenyuan

**Comment by natee** [comment]
@reset-global mobile  请问@reset-global mobile  这里的全局样式重置源码在哪里？
