### ISSUE TITLE
laodmore当有元素fixed在底部时，上拉加载触发不了

### ISSUE THREAD

**Issue by warwr1ck** [ElemeFE/mint-ui#739]
当我在用loadmore的时候，因为有一个元素fixed在底部，需要有一个占位元素，以显示全loadmore中的内容，不管我占位元素加在loadmore的父、子元素中还是在fixed元素的父元素中，都会导致loadmore上拉加载的事件不响应，或者时而响应，时而不响应……去掉这个占位的元素就可以很好地响应
占位元素不管是采用margin、padding、或是一个空白具有高度的元素，都会导致以上情况。
在不同设备中上述情况会发生变化

**Comment by warwr1ck** [comment]
似乎是因为我引入了淘宝的flexible导致的原因，在iphone（高dpr）的设备中会出现这种情况

**Comment by galenyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/10335062/24320669/c10905ee-1174-11e7-9234-90577b7f8c01.png)
我在 demo 里试了一下，加了 padding 是可以正常工作的

**Comment by galenyuan** [comment]
如果你那边依然有问题，可以提供一个 GitHub 的重现仓库

**Comment by wjf444128852** [comment]
经过测试，我这里该问题不存在，但是，加载好数据(模拟的)之后那个loading状态的html原生一直存在，就是绑定了loadTop或者loadBottom的元素在loadTop/Bottom事件之后的位置没有回到初始位置，看mint-ui的文档也没看到哪个参数去改变的，能否说一下呢？

**Comment by galenyuan** [comment]
@wjf444128852 
![image](https://cloud.githubusercontent.com/assets/10335062/24445989/808a89de-149e-11e7-9e8b-c65febf65114.png)
图中红框为完成加载后的处理，改成对应自己的名字就可以了

**Comment by wjf444128852** [comment]
@galenyuan 恩恩。。已經搞定了，忘記說了！
