### ISSUE TITLE
lazyLoad,在用于v-for循环中替换list不会更新图片

### ISSUE THREAD

**Issue by Molly0920** [ElemeFE/mint-ui#741]
例如：
`<div v-for="item in list">`
    `<img v-lazy="item.imagePath"/>`
`</div>`

通过请求去替换list，图片地址不会改变，如果用:src="item.imagePath"图片能够更新成功

**Comment by galenyuan** [comment]
这是 vue 的特性，不加冒号是参数，加冒号是动态参数

**Comment by Molly0920** [comment]
v-lazy可以加冒号？还没试过，谢谢解答

**Comment by galenyuan** [comment]
😂 刚才没看明白，别加冒号，用 Mint 的话最好用 `v-if` 包起来，等拿到 url 再显示出来
也可以直接用 https://github.com/hilongjw/vue-lazyload 的 lazy component

**Comment by Molly0920** [comment]
我早上试了一下，可以用
`<div v-for="item in list">`
`<img v-lazy="item.imagePath" :src="item.imagePath"/>`
`</div>`
这样就可以了
