### ISSUE TITLE
vue-cli +vue-router + mint-ui 创建的项目，npm run build 时报错

### ISSUE THREAD

**Issue by Jerry-web** [ElemeFE/mint-ui#742]
npm run dev 可以正常跑起来，但是npm run build 时mint-ui 报错了。

报错文件
//////////////////
// WEBPACK FOOTER
// ./~/.2.2.1@mint-ui/lib/index.js
// module id = 13
// module chunks = 0

报错
index.js:3Uncaught TypeError: n is not a function(…)

**Comment by galenyuan** [comment]
信息再多点，可以放个截图上来

**Comment by Jerry-web** [comment]
![console_error](https://cloud.githubusercontent.com/assets/16814493/24280235/f89e9546-1089-11e7-898b-c0771368385d.png)
![error](https://cloud.githubusercontent.com/assets/16814493/24280239/fe12caa6-1089-11e7-9b67-e0f0d4dc62b1.png)

**Comment by Jerry-web** [comment]
build以后生产环境在tomcat运行就出现这个错误了

**Comment by galenyuan** [comment]
无法重现，提供一下你的 package.json

**Comment by Jerry-web** [comment]
[package.txt](https://github.com/ElemeFE/mint-ui/files/866875/package.txt)
您修改一下文件名称，json文件无法上传我改成txt了

**Comment by Jerry-web** [comment]
在您的环境下问题重现了吗？

**Comment by galenyuan** [comment]
还是无法重现，你直接建个仓库吧

**Comment by Jerry-web** [comment]
开发环境是没问题的，一到生产环境就报错了

**Comment by Jerry-web** [comment]
要不我把项目demo给你看看吧

**Comment by galenyuan** [comment]
可以，你直接在 GitHub 上建个仓库就可以

**Comment by Jerry-web** [comment]
好的，谢谢

**Comment by Jerry-web** [comment]
你好，我刚创建完仓库地址：https://github.com/Jerry-web/NBS_OMP_DEMO.git  您试一下吧，多谢

**Comment by galenyuan** [comment]
跟 Mint 没关系，是构建方面的问题，你可以把依赖都升级一下，webpack的版本太新了，其他插件的版本太旧了

**Comment by biggercool** [comment]
楼主解决了么，我也有这个问题

**Comment by biggercool** [comment]
我 npm update以后 npm run dev直接报错 然后按照提示
加了一个"vue-template-compiler": "^2.1.10", 依赖
npm run dev 正常 但是build依旧和楼主一样的错误

index.js:3Uncaught TypeError: n is not a function(…)

**Comment by galenyuan** [comment]
可参考 #750 看看是否对症你的问题

**Comment by Jerry-web** [comment]
尝试了各种方法依然没解决啊！！

**Comment by galenyuan** [comment]
`.babelrc`里面
```json
["component", [
  { "libraryName": "mint-ui", "style": true }
]]
```
删掉，我去更新一下文档

**Comment by Jerry-web** [comment]
好的，我已经删了

**Comment by Jerry-web** [comment]
更新的文档我在哪里查阅啊？

**Comment by Jerry-web** [comment]
删了以后mint-ui好像就没法使用了！

**Comment by galenyuan** [comment]
“没法使用”是什么意思？

**Comment by Jerry-web** [comment]
删除了.babelrc的配置后，mintui就不起作用了

**Comment by galenyuan** [comment]
已修复并发布最新版，更新一下版本试试

**Comment by Jerry-web** [comment]
好的，我试试哦

**Comment by Jerry-web** [comment]
问题已解决，多谢！！
