### ISSUE TITLE
模版npm run dev成功以后 直接npm run build编译后 dist文件夹没有index.html

### ISSUE THREAD

**Issue by biggercool** [ElemeFE/mint-ui#745]
测试一下就知道了，dist里面就一个build.js文件

谁知道是什么坑？怎么解决！

**Comment by biggercool** [comment]
关闭可以，但确实没有index.html文件！

**Comment by galenyuan** [comment]
首先，Mint 没那么大能耐让你编译过程挂掉
其次，你去看医生都只跟医生说你难受，不跟医生说你吃什么喝什么哪难受的？

**Comment by galenyuan** [comment]
最后，参考 #742 ，人家是来解决问题你的，你是来找刺激的。

**Comment by biggercool** [comment]
#742 编译以后也同样是 n is no function的错误

**Comment by galenyuan** [comment]
可参考 #750 看看是否对症你的问题
