### ISSUE TITLE
popup安卓物理返回键的问题

### ISSUE THREAD

**Issue by eaminhu** [ElemeFE/mint-ui#746]
最新版的mint-ui+vue, 用popup弹层的时候，安卓操作物理返回键的时候，不是关闭弹层还是直接回到前一页

**Comment by galenyuan** [comment]
本身功能就不是这么设计的，你可以在 router 的 `beforeRouteLeave` 自行处理

**Comment by dmlzj** [comment]
@galenyuan 大哥我錯了。。。
