### ISSUE TITLE
Action sheet actions数组里的method不起作用

### ISSUE THREAD

**Issue by dmlzj** [ElemeFE/mint-ui#747]
**"mint-ui": "^2.2.0",**

` mobileActions: [
            {
                name: "通过短信认证修改",
                method: "goSms"
            },
            {
                name: "人工申诉",
                method: "goAppeal"
            }
        ]`

` methods: {
  
    goSms: function() {
        this.$router.push({path: 'mobile',params: { type: ''}})
    },
    goAppeal: function() {
        console.log('aaa')
        this.$router.push('/about/appeal')
    }
  }`
log也打不出来

**Comment by galenyuan** [comment]
ref #700 ，你的一切 issue 不做回答，请你不要用，谢谢。
