### ISSUE TITLE
Action sheet method的问题

### ISSUE THREAD

**Issue by dmlzj** [ElemeFE/mint-ui#748]
"mint-ui": "^2.2.0"
文档上写的不行：
`actions 属性绑定一个由对象组成的数组，每个对象有 name 和 method 两个键，name 为菜单项的文本，method 为点击该菜单项的回调函数。将 v-model 绑定到一个本地变量，通过操作这个变量即可控制 actionsheet 的显示与隐藏。`
格式应该是这样的，比如你要点击的时候执行methods里面的getUser，代码应该这样写：
`Actions: [
            {
                name: "获取用户信息",
                method: this.getUser
            }`
留给后面的童鞋参考[747](https://github.com/ElemeFE/mint-ui/issues/747) [738](https://github.com/ElemeFE/mint-ui/issues/738)
[你的智商全世界第一。。](https://github.com/ElemeFE/mint-ui/issues/700)
我只想说你可以不回答，你可以别这么牛逼吗？@galenyuan

**Comment by galenyuan** [comment]
你可以自己好好回想一下这个问题，然后自己总结一下你的智商究竟处于什么样的水平线上，还是那句话，求你别用，ok？

**Comment by dmlzj** [comment]
@galenyuan 你很牛逼？你父母是这样教你的？动不动旧特么的装逼的说求你别用，我爱用关你屁事，什么垃圾玩意，老子不想骂你个傻逼，你还嘚瑟上了，你特么智商高的能赶上比尔盖茨？不用求老子，老子想用就用！文档写的烂还不让人说了？真尼玛服了！写的不行就是不行，别尼玛装的自己多牛逼似的

**Comment by dmlzj** [comment]
求你个傻逼别再这里用自己那所谓的时间来管理这仓库了，你在这里就是垃圾，不用你管理了，求你滚吧！ @galenyuan
