### ISSUE TITLE
用vue-cli执行Build命令后，页面报Uncaught TypeError: n is not a function

### ISSUE THREAD

**Issue by zzhero** [ElemeFE/mint-ui#750]
### Mint UI version
mint-ui: 2.2.1
vue: 2.2.2

### What is actually happening?
使用最新的vue-cli脚手架搭建的项目， 在非npm安装mint-ui而是直接引用下载下来的min-ui.js的时候，

```js
import Mint from '../static/chunk/mint/mint-ui.js'
Vue.use(Mint);
```

执行Build后，页面报mint-ui.js错误
Uncaught TypeError: n is not a function,打开报错地点如下： 
![错误提示](http://of2xzyue0.bkt.clouddn.com/error1.png)
![sorucemap打开](http://of2xzyue0.bkt.clouddn.com/error2.png)

```js
var t = n(91).Promise,
e = "undefined" != typeof window;
return Array.prototype.$remove || (Array.prototype.$remove = function(t) {
    if (this.length) {
        var e = this.indexOf(t);
        return e > -1 ? this.splice(e, 1) : void 0
    }
}
```

但如果用npm安装mint-ui， 然后单独引用mint-ui.common.js,运行ok。

**Comment by biggercool** [comment]
I have the same problem

**Comment by galenyuan** [comment]
我试一下

**Comment by biggercool** [comment]
昨天就是这个问题，周末准备一个页面一个页面进行测试

**Comment by galenyuan** [comment]
重现成功, 因为你`import`的是 Mint 提供给 CDN 的文件, 也就是 `lib/index.js`, 但 Mint 暴露给 npm 的入口是 `lib/mint-ui.common.js`, 也就是说 你从 CDN 上下载下来的文件只能作为 `script` 标签引入, 而从 npm 上拉下来的 pkg 只能以 `import` 的方式引入

**Comment by zzhero** [comment]
谢谢。  
ok   那我自己再混淆common.js文件，单独引入好了。 可原来的项目就是这样引入的也没有build出问题来。感觉是新脚手架vue-cli的配置问题， 那这就与mint-ui本身无关了。

**Comment by galenyuan** [comment]
问题已修复并发布新版本，更新依赖即可
