### ISSUE TITLE
使用的是mint-ui提供的模版 dev正常 build同样出现 n is not a function 报错

### ISSUE THREAD

**Issue by biggercool** [ElemeFE/mint-ui#753]
https://github.com/biggercool/PnPark

目前有这个疑问的有好多，看了团队成员对上一个问题的回复，
貌似和给的模版有一些区别

https://github.com/mint-ui/mint-ui-starter
这个模板

**Comment by biggercool** [comment]
npm run dev   地址需要加   ?banks_id=3

**Comment by galenyuan** [comment]
卧槽... 你憋说了 我现在就去更新这玩意 TOT

**Comment by galenyuan** [comment]
你可以自己先
```bash
npm update --save
npm update --save-dev
```
解决一下

**Comment by biggercool** [comment]
今天测试一天找不到哪个地方错了，但是模版直接编译以后可以用啊，也没有这个错误，我一直以为是自己写的页面有问题！

**Comment by galenyuan** [comment]
参考 #742 先把`babel-plugin-component`删掉

**Comment by galenyuan** [comment]
问题已修复并发布新版本，更新依赖即可
