### ISSUE TITLE
Cell控件，带is-link的，点击后背景无变化

### ISSUE THREAD

**Issue by simon82** [ElemeFE/mint-ui#754]
Cell控件，带is-link的，点击后背景无变化。
但在官方的demo里面是正确显示的，会有一个backgroud-color: #000的区块的opacity被设置为0.1

**Comment by galenyuan** [comment]
查一下这个元素 `.mint-cell-mask:active:after`

**Comment by simon82** [comment]
<script async src="//jsfiddle.net/simon82/2m3cbzzn/2/embed/"></script>

**Comment by simon82** [comment]
重现链接：
https://jsfiddle.net/simon82/2m3cbzzn/

**Comment by galenyuan** [comment]
修复 #470 时引发的问题，解决中
