### ISSUE TITLE
你们的文档写的是有多垃圾！看看知乎上有多少人在吐槽你们的文档

### ISSUE THREAD

**Issue by crastyle** [ElemeFE/mint-ui#761]
首先很感谢你们，开源了你们的业务组件。

但是但是但是，这文档……既然开源了能把文档做好吗？？

中文版和英文版的api竟然不一样！！不一样！！不一样！！

这么多人关注了，请把文档给写好，可以吗？

同样饿了么团队，为什么element做的就那么好呢？！！！

**Comment by QingWei-Li** [comment]
Mint UI 纯粹是我和 @Leopoldthecoder 两人利用业余时间开发和维护的，再则现在我们的业余时间已经花在了维护 element 上，现在的 mint 都是 @galenyuan 有空才管理。

如果你觉得文档有问题，欢迎提 PR，开源项目不是开源出来就是给开发者的，还需要大家一起维护。我们花那么时间和精力，目的就是为了伺候各位大爷？
