### ISSUE TITLE
[Bug Report] Button被点击时（active状态)，背景并非圆角。

### ISSUE THREAD

**Issue by simon82** [ElemeFE/mint-ui#763]
### Mint UI version
2.2.2

### OS/Browsers version
chrome版本 55.0.2883.75 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/simon82/2m3cbzzn/](https://jsfiddle.net/simon82/2m3cbzzn/)

### Steps to reproduce
请看jsfiddle

### What is Expected?
按钮被点击时，背景是圆角的

### What is actually happening?
按钮被点击时，背景不是圆角的

**Comment by galenyuan** [comment]
修复 #470 时引发的问题，解决中

**Comment by galenyuan** [comment]
新版发布之前可以用
```css
.cell-wrapper {
  position: static;
}
```
作为 workaround
