### ISSUE TITLE
Picker组件的onValuesChange事件会默认调用一次

### ISSUE THREAD

**Issue by deepred5** [ElemeFE/mint-ui#765]
我想选中的值发生改变后才调用onValuesChange的处理函数，结果页面一初始化，就立刻触发了onValuesChange事件，怎么处理？

**Comment by galenyuan** [comment]
在组件初始化时会触发一次，你可以通过watch结果来观察选值变化

**Comment by deepred5** [comment]
我现在是这样的业务场景，假如picker有多个选项
```
slots: [{values: ['深圳', '上海', '广州', '南昌', '北京', '天津']}]
```
我想监听数据发生改动时，就获取用户选择了哪个值，但是现在onValuesChange默认会调用一次，当用户第一次点击picker，如果他刚好就想选第一个选项“深圳”，那么他这次点击picker就不会触发onValueChange事件，我也就无法知道他选择了第一个选项。
`mt-picker`好像并不能自动绑定`v-model`，要手动设置值，但是现在这种情况如何解决？

**Comment by galenyuan** [comment]
😂 他刚好就想选第一个的话不就是第一次触发`onValuesChange`的结果么，为什么还要强制再触发一次呢

**Comment by deepred5** [comment]
我现在是一个表单，里面有多个这样的picker。比如有个cell组件，文字是居住地。然后我点一下这个cell，弹出了个picker，让用户选择居住地。又有个cell组件，文字是年龄，点一下，又弹出个picker。现在这种情况，用户进入该页面，什么都不操作，就默认把所有的picker的第一个选项选中了，他甚至可以直接点击提交按钮了，我也没办法提示他说他的picker未选择，因为onValuesChange已经默认帮他选了。

**Comment by galenyuan** [comment]
你可以加个默认的空值，`values`可以变为一个对象数组，设置一个`valueKey`来控制哪个字段用来显示在页面上

**Comment by deepred5** [comment]
```
slots: [{
    values: [
        { '深圳': '0112' },
        { '上海': '0113' }
    ]
}]
```
```
<mt-picker :slots="slots" valueKey=""></mt-picker>
```
文档上好像也没写清怎么写？

**Comment by galenyuan** [comment]
```javascript
values: [
  {
    text: '请选择',
    value: ''
  },
  {
    text: '上海',
    value: 'ShangHai'
  }
],
valueKey: 'text'
```

**Comment by galenyuan** [comment]
https://jsfiddle.net/p11091wm/ 这样

**Comment by deepred5** [comment]
这样写的话，“请选择”也变成了一个可选项。我试着用了其他的方式，阻止第一次onValueChange事件时赋值。
https://jsfiddle.net/ac891jfp/

**Comment by cooper1x** [comment]
@deepred5 也可以用一个变量，就你上面的`ispopup`，点击为true，这样就不需要两个变量了。
```
 onCityChange(picker, values) {
        if (this.ispopup) {
          this.city = values[0].value;
        }
      }
```
