### ISSUE TITLE
[Bug Report] swiper 如果放入图片高度为0

### ISSUE THREAD

**Issue by haishengXie0712** [ElemeFE/mint-ui#774]
### Mint UI version
2.1.0

### OS/Browsers version
Google Chrome版本 56.0.2924.87

### Vue version
2.0.3

### Steps to reproduce
<mt-swipe :auto="4000" :show-indicators="false" class="swiper">
	<mt-swipe-item>
		<img src="...url"/>
	</mt-swipe-item>
	<mt-swipe-item>
		<img src="...url"/>
	</mt-swipe-item>
</mt-swipe>
.swiper{
	img{
		width: 100%;
		height: auto;
	}
}

### What is Expected?
根据我的图片大小自适应

### What is actually happening?
高度全部都是0，可是我的图片是有高度的，高度整体为0，无法根据我的图片大小自适应

**Comment by galenyuan** [comment]
见demo
https://github.com/ElemeFE/mint-ui/blob/master/example/pages/swipe.vue#L48
要给`.mint-swipe`设定高度

**Comment by haishengXie0712** [comment]
@galenyuan 可是如果我的图片变大小那怎么处理？

**Comment by galenyuan** [comment]
动态改元素的高度即可

**Comment by haishengXie0712** [comment]
@galenyuan 好的，非常感谢

**Comment by zhuxianbin** [comment]
@galenyuan 怎么动态高度..
