### ISSUE TITLE
picker组件中picker-solt.vue中once函数中的回调写的有问题

### ISSUE THREAD

**Issue by Measy** [ElemeFE/mint-ui#776]
### Mint UI version
2.2.2

### OS/Browsers version
无关

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue](https://github.com/ElemeFE/mint-ui/blob/master/packages/picker/src/picker-slot.vue)

### Steps to reproduce
```
once(el, translateUtil.transitionEndProperty, () => {
          this.animationFrameId = null;
          cancelAnimationFrame(this.animationFrameId); 
});
```

### What is Expected?
```
once(el, translateUtil.transitionEndProperty, () => {
          cancelAnimationFrame(this.animationFrameId); 
          this.animationFrameId = null;
});
```

### What is actually happening?
先置null再取消，cancelAnimationFrame无效

**Comment by galenyuan** [comment]
😂 为啥不直接提个 PR 啊
