### ISSUE TITLE
[Bug Report] cell-swipe刷新问题

### ISSUE THREAD

**Issue by haishengXie0712** [ElemeFE/mint-ui#785]
### Mint UI version
2.2.2

### OS/Browsers version
google chrome 52.0.2743.116

### Vue version
2.2.2

### Steps to reproduce
在当前路由下刷新，右边滑出来的按钮会漏出一点点。
但是看css中mint-cell-right，已经有    position: absolute，right: 0;的属性。
在其他路由切换过来却不会有这种问题。

### What is Expected?
我希望在当前路由刷新时，也可以把右手边的按钮完全隐藏起来

### What is actually happening?
右手边的按钮漏出来了一点点

**Comment by galenyuan** [comment]
有图或者在线的 demo 么，这表述有点抽象，脑补不出来。。

**Comment by haishengXie0712** [comment]
@galenyuan 问题已经解决，给顶一个宽度就不会显示出来了

**Comment by godo9** [comment]
> @galenyuan问题已经解决，给顶一个宽度就不会显示出来了

请问下设置哪个元素的宽度？
