### ISSUE TITLE
[Bug Report] 手机 sofari浏览器  无法关闭加载提示 。

### ISSUE THREAD

**Issue by zodana** [ElemeFE/mint-ui#803]
### Mint UI version
2.2.3

### OS/Browsers version
ios 9    sofari 

### Vue version
2.2.6

### Reproduction Link
[https://github.com/ElemeFE/mint-ui](https://github.com/ElemeFE/mint-ui)

### Steps to reproduce
if (this.loading) {
console.log('44444');
Indicator.open({
text: '加载中...',
spinnerType: 'fading-circle'
});
} else {
console.log('55555');
Indicator.close();
}

ios 版本是最新的了。 估计不是 sofari 版本过老的问题。
但是通过windows 下载的sofari浏览器 没有重现这个问题。

### What is Expected?
加载提示在加载完成后  能够隐藏 

### What is actually happening?
没有隐藏。

**Comment by galenyuan** [comment]
请提供重现链接或 GitHub 仓库

**Comment by zodana** [comment]
误报了。可能是缓存问题吧，再看 好了。  但是 element-ui 是有问题的。 我是临时把element-ui的loading 切换成mint-ui 来做的。 发现问题没有重现了
