### ISSUE TITLE
部分导入组件时使用Vue.use(Button)无法成功导入组件

### ISSUE THREAD

**Issue by imalexi** [ElemeFE/mint-ui#805]
部分导入组件时使用Vue.use(Button)无法成功导入组件，版本：2.2.3

**Comment by galenyuan** [comment]
部分导入不需要 use，直接`Vue.component()`或`components: { component }`

**Comment by Foreverofh** [comment]
为啥button组件用点击事件会触发三次效果！！！

**Comment by Ttou** [comment]
@galenyuan 
那文档为什么写可以用`Vue.use(Button)`，而且在`element-ui`下就可以这样写

**Comment by chuanxd** [comment]
確實文檔是這樣寫，繞了一個圈發現不能使用 `.use()`
