### ISSUE TITLE
[Feature Request] Datetime Picker 支援 plain JavaScript 物件

### ISSUE THREAD

**Issue by chuanxd** [ElemeFE/mint-ui#806]
### Existing Component
Yes

### Component Name
Datetime Picker

### Description
https://github.com/vuejs/vue/issues/5281

目前 datetime-picker 組件不支持非 Date 物件，但 Vue 不支持非純 JS 物件 reactive

除了更改接口規格之外，還有什麼方式可以讓 datetime-picker `v-model` 支持 reactive ？

使用 date String 可以 reactive 不過 console 會報錯，因為沒有 Date 物件屬性

**Comment by galenyuan** [comment]
重新给`date`赋值，不要单独去改他的`year`，而且这是 vue 层面的问题
