### ISSUE TITLE
在自定义组件xx.vue里面使用“html某些标签+mt-picker”，引用<xx></xx>的时候，其它标签都可以显示出来，但mt-picker无法显示出来？

### ISSUE THREAD

**Issue by wonghoman** [ElemeFE/mint-ui#818]
在自定义组件xx.vue里面使用“html某些标签+mt-picker”，引用<xx></xx>的时候，其它标签都可以显示出来，但mt-picker无法显示出来？
尝试过将mt-picker不放在自定义组件里面，是可以显示的，放到自定义组件就不能显示了。
在自定义组件已经用下面的代码引入mt-picker了，跟没用到自定义组件的那个见面的方式是一样的，那个见面可以显示，自定义组件就不可以了
`<mt-picker :slots="slots" @change="onValuesChange" :visibleItemCount="3"></mt-picker>

import Vue from 'vue';
import { Picker } from 'mint-ui';
Vue.component(Picker.name, Picker);`
请问大神，这个问题是怎么回事？

**Comment by galenyuan** [comment]
看一下`<mt-picker></mt-picker>`被解析成 html 了么

**Comment by wonghoman** [comment]
@galenyuan 解析成html了；
不显示的时候是这样：
<div data-v-0ca52ad8="" class="picker"> <div class="pickera-items"> <div class="picker-center-highlight" style="height: 36px; margin-top: -18px;"></div></div></div>

显示的时候是这样：
<div class="picker" style="clear: both;"> <div class="picker-items"><div class="picker-slot picker-slot-center slot1" style="flex: 1 1 0%; -webkit-box-flex: 1;"><div class="picker-slot-wrapper" style="height: 108px; transform: translate(0px, 36px) translateZ(0px);"><div class="picker-item picker-selected" style="height: 36px; line-height: 36px;">
      今天
    </div><div class="picker-item" style="height: 36px; line-height: 36px;">
      明天
    </div><div class="picker-item" style="height: 36px; line-height: 36px;">
      后天
    </div></div> </div><div class="picker-slot picker-slot-center picker-slot-divider slot2"> <div></div></div><div class="picker-slot picker-slot-left slot3" style="flex: 1 1 0%; -webkit-box-flex: 1;"><div class="picker-slot-wrapper" style="height: 108px; transform: translate(0px, 36px) translateZ(0px);"><div class="picker-item picker-selected" style="height: 36px; line-height: 36px;">
      尽快送达
    </div><div class="picker-item" style="height: 36px; line-height: 36px;">
      11111111
    </div><div class="picker-item" style="height: 36px; line-height: 36px;">
      2222222
    </div></div> </div> <div class="picker-center-highlight" style="height: 36px; margin-top: -18px;"></div></div></div>

感谢感谢！

**Comment by galenyuan** [comment]
引入全局css，不要单独引入picker的css，参考 #682

**Comment by wonghoman** [comment]
@galenyuan 刚刚试过了，你说的引用全局是在main.js加入import 'mint-ui/lib/style.css';吗？我加了然后重启服务，没效果，还是不显示。是不是哪里搞错了？

**Comment by galenyuan** [comment]
你说 ”将mt-picker不放在自定义组件里面，是可以显示的，放到自定义组件就不能显示了“
那应该不是这个问题..感觉是你自己css的问题啊，仔细查一下css？

**Comment by wonghoman** [comment]
@galenyuan 不会是我的css影响到吧，css名字不可能覆盖掉他的，用组件包装了一层就不显示了，代码都是那些，唉，有没我这种情况（自定义组件使用了mt-picker）的demo可以参考下？没有的话有空搞个demo测试一下吗？

**Comment by galenyuan** [comment]
https://github.com/ElemeFE/mint-ui/blob/master/example/pages/picker.vue#L21

**Comment by wonghoman** [comment]
@galenyuan 你上面给的demo是没用到自定义组件的情况，这种情况我这边也是可以显示的，你有没做过我现在这种（自定义组件中使用了mt-picker）情况？要不你有空的话测试一下？非常感谢！

**Comment by galenyuan** [comment]
https://github.com/CodeDreamfy/Rickbread/blob/9754518d77e41d918d8671bc43de944ab28e5178/src/router/index.js#L18
https://github.com/CodeDreamfy/Rickbread/blob/9754518d77e41d918d8671bc43de944ab28e5178/src/main.js#L10
github 上随便搜的，自己去看看吧

**Comment by wonghoman** [comment]
@galenyuan 非常感谢你的耐心回复，问题已经解决，原因是自定义组件中，使用的数据放在props中无法读取到，放在data() {return就可以了，这应该是基础问题，大神见笑了，再次感谢大神的回答，回复速度也好快，点赞！
