### ISSUE TITLE
loadmore 模块 loadBottom 事件首次触发及进入页面3次触发 loadBottom 的问题

### ISSUE THREAD

**Issue by LeisureZjj** [ElemeFE/mint-ui#82]
首次进入列表页面时 loadBottom 事件会在 route -> data 之前执行，可否设置在首次进入页面时不触发 loadBottom ?另外，进入页面时会3次触发 loadBottom 的情况。

**Comment by Leopoldthecoder** [comment]
能否详细说明首次进入列表页面时 loadBottom 事件执行的时机？
关于进入页面时会 3 次触发 loadBottom 的问题：loadmore 组件在初始化时会检测列表能否撑满容器，不能的话就会触发 loadBottom，直到列表撑满容器为止。所以是不是你的列表比较短，以及 loadBottom 每次请求的数据较少？

**Comment by LeisureZjj** [comment]
@Leopoldthecoder 
- 3次触发 loadBottom 的问题，确实正如你所说。
- 首次进入列表页面的问题，我再反复操作了下，需要纠正下我的叙述：

  首次进入列表页面，我在 route -> data 中获取了第一页列表数据，并撑满容器，这时没有 触发 loadBottom，然后上拉加载第二页数据也正常。在 route -> data 中我通过 promise 串行获取基本信息得到ID，再根据ID获取列表数据。

  但是当我通过浏览器刷新列表页，先触发的 loadBottom，然后才执行 route -> data，这两次得到都是第一页数据，并且上拉没有效果，allLoaded 这时还是 false。另外，退出重新进入列表页时，route -> data 中得到第一页列表数据，然后上拉也效果。

**Comment by Leopoldthecoder** [comment]
@LeisureZjj Hi，现在给组件添加了一个 API，可以设置在进入页面时不触发 loadBottom。详见[这里](http://mint-ui.github.io/docs/#!/zh-cn/loadmore)。请尝试指定 autoFill 为 false，看看问题能不能解决。
