### ISSUE TITLE
picker组件初始化后先滚动二级slot会有报错:[Vue warn]: Error in callback for watcher "currentValue":  (found in <PickerSlot>)

### ISSUE THREAD

**Issue by Joeycz** [ElemeFE/mint-ui#829]
完整的报错如下：

```
[Vue warn]: Error in callback for watcher "currentValue": 
(found in <PickerSlot>)
TypeError: Cannot read property 'indexOf' of undefined

[Vue warn]: Error in callback for watcher "mutatingValues": 
(found in <PickerSlot>)
TypeError: Cannot read property 'indexOf' of undefined
```
我怀疑是v-model双向绑定的原因：（mint-ui/packages/picker/src/picker.vue）
```
<picker-slot
    v-for="slot in slots" 
    :valueKey="valueKey" 
    :values="slot.values || []" 
    :text-align="slot.textAlign || 'center'" 
    :visible-item-count="visibleItemCount" 
    :class-name="slot.className" :flex="slot.flex" 
    **v-model="values[slot.valueIndex]"** 
    :rotate-effect="rotateEffect" 
    :divider="slot.divider" 
    :content="slot.content" 
    :itemHeight="itemHeight" 
    :default-index="slot.defaultIndex"></picker-slot>
```

bug复现条件：
1、更改example里的picker（mint-ui/example/pages/picker.vue）
2、更改address为：
```
const address = {
    '广东': ['广州', '深圳', '珠海', '汕头', '韶关', '佛山', '江门', '湛江', '茂名', '肇庆', '惠州', '梅州', '汕尾', '河源', '阳江', '清远', '东莞', '中山', '潮州', '揭阳', '云浮'],
    '北京': ['北京'],
    '上海': ['上海'],
    ...
}
```
3、页面打开以后，省份不动，滚动2级选项，即滚动城市，报错。

**Comment by galenyuan** [comment]
`更改example里的picker`
改啥了啊？

**Comment by ruinL** [comment]
他给2级联动的默认值里面多加了一个，变成可滚动的，然后先拖动2级就会发生报错。我在把2级联动改为3级联动的时候也碰到了这个问题。
`addressSlots: [
          {
            flex: 1,
            values: Object.keys(address),
            className: 'slot1',
            textAlign: 'center'
          }, {
            divider: true,
            content: '-',
            className: 'slot2'
          }, {
            flex: 1,
            values: ['澳门','打算'],
            currentValue: '北京',
            className: 'slot3',
            textAlign: 'center'
          }, {
            divider: true,
            content: '-',
            className: 'slot2'
          }, {
            flex: 1,
            values: [],
            className: 'slot3',
            textAlign: 'center'
          }
        ],`
你们给的example中默认值设置的是['北京']，不能拖动 所以不会发生问题

**Comment by galenyuan** [comment]
@ruinL 的问题成功重现了，但 @Joeycz 的问题依然没重现..我这里城市是错的 但不会报错

**Comment by ruinL** [comment]
请问这个问题可以解决吗(默认值)，还有三级联动的方案，谢谢。

**Comment by Foreverofh** [comment]
楼主我也遇到这个问题，滚动的时候赋值报错，你怎么解决！

**Comment by Foreverofh** [comment]
@galenyuan  picker滚动的时候赋值，打开控制台无限打印数据，导致浏览器崩毁！

**Comment by MiachelPeng** [comment]
@Joeycz 您好，请问您这个问题解决了么，我现在用的版本是2.2.6

**Comment by Joeycz** [comment]
@MiachelPeng 是的我把双向绑定去掉了，凑合能用，但是这个组件使用我觉得不能超过三级，问题还是比较多
我怀疑是v-model双向绑定的原因：（mint-ui/packages/picker/src/picker.vue）
更改是这样的
<picker-slot
        v-for="slot in slots"
        :values="slot.values || []"
        :text-align="slot.textAlign || 'center'"
        :visible-item-count="visibleItemCount"
        :class-name="slot.className"
        :flex="slot.flex"
        :value="values[slot.valueIndex]"
        :rotate-effect="rotateEffect"
        :divider="slot.divider"
        :content="slot.content"
        :key="slot.className"></picker-slot>
貌似其他地方也做了一些修改，我个人觉得是双向绑定报的错

**Comment by RunningV** [comment]
请问这个做三级联动时如何判断当前滚动的是哪一级？
