### ISSUE TITLE
MessageBox.confirm，取消报错

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/mint-ui#83]
`
MessageBox.confirm('确定执行此操作?').then(action => {
  ...
});
`
点击取消按钮报错

**Comment by QingWei-Li** [comment]
http://mint-ui.github.io/docs/#!/zh-cn/message-box

> 在 prompt 中，若用户点击了取消按钮，则 Promise 的状态会变为 rejected

所以应该是 
```javascript
MessageBox.confirm('确定执行此操作?')
  .then(action => {
    console.log(action);
  }).catch(err => {
    console.log(err);
  });
```

**Comment by acmeid** [comment]
当使用者没有写catch的时候，就报错了。我觉得不应该给使用者出现报错的机会。

**Comment by QingWei-Li** [comment]
不捕获 Promise 的异常是不会有任何错误提示，那个是 Chrome 才会这样处理，其实只是个 warning

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/21304637/9abb0270-c601-11e6-8072-ebcbf161b938.png)
文档里也跟进改下吧
