### ISSUE TITLE
[Feature Request] picker组件滑到顶部或底部时留出一半的空白区，希望解决

### ISSUE THREAD

**Issue by RunningV** [ElemeFE/mint-ui#833]
### Existing Component
是

### Component Name
picker、datetime-picker

### Description
我在使用datetime-picker组件时，发现问题：默认一开始打开组件时组件的排列是从设置的div中部开始的，选则某一项picker后滑动到底部其它picker-slot还在中部，不对齐，看了下源码，date-picker是依赖picker的组件，默认组件内部用js动态计算设置了`transform: translate(0px, 72px) translateZ(0px);`这个`translateY`的值导致每个选择项不对齐，是组件里的我又没办法用css去改，也算是个小bug吧，望修复.详图见下面的回复。tks

**Comment by RunningV** [comment]
上面的问题我用图片说明下吧：
![Uploading 1.png…]()
像这样日期选择三列，是居中开始排列的，按道理应该从这个div的顶部开始排列吧。
![Uploading 2.png…]()
当我把某一项如第一项拉到底部时，它应该自动滑到底部对齐，而不是在中部对齐，如上图很不美观。
![Uploading 3.png…]()
当三项都拉到底部时如上图，按道理不应该是据底部对齐吗？
我看了下源码是通过js动态计算设置`translateY`的值来设置滑动位置的，不好改啊，望修复下吧。

**Comment by galenyuan** [comment]
图片没上传完..重传一下 图片出来了再 Comment

**Comment by RunningV** [comment]
想了想这个貌似没法实现，这个组件默认就是中间一行是选中的，不可能做到据顶据底对齐，其实能不能做成在给定的数组范围循环滚动呢？

**Comment by galenyuan** [comment]
想法太定制化了..而且看起来也会很奇怪，关掉了
