### ISSUE TITLE
with browserify cannot find module [...]/style.css

### ISSUE THREAD

**Issue by Nakurai** [ElemeFE/mint-ui#836]
Hello!

I have tried to use mint-ui in my Vue.js project. I am using browserify. 
1. I have installed mint using `npm install mint-ui --save`
2. required the module using `var mint = require('mint-ui`);
2. included mint in Vue: `Vue.use('mint');`

Then when I want to generate the app bundle: 
`
$ browserify -t vueify www/js/main.js -o ./www/js/build/app.js
Error: Cannot find module 'mint-ui/packages/cell/style.css' from 'path\to\project\node_modules\mint-ui\lib'
    at path\to\windows\user\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (path\to\windows\user\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (path\to\windows\user\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (path\to\windows\user\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (path\to\windows\user\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at path\to\windows\user\AppData\Roaming\npm\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
`
Am I missing anything?

**Comment by galenyuan** [comment]
Can you create a repo in GitHub and upload your code or a sample?
It's wired...

**Comment by Nakurai** [comment]
Hello, I have created this repository: https://github.com/Nakurai/error_mint_ui
It's litterally just the `browserify-simple` template from the Vue.js repo and then mint-ui installed. I hope it will help!

**Comment by QingWei-Li** [comment]
You should use webpack.
I am not sure why this code does not work in browserify, but it works in webpack.

```js
if (false) {
  require('mint-ui/packages/font/style.css')
}
```

**Comment by maurop123** [comment]
I'm getting this error, too. I see that there is no `style.css` in `node_modules/mint-ui/packages/(picker|spinner|cell|popup)/` and there is not font folder in packages either. Could that be a problem?

**Comment by maurop123** [comment]
I see that the `build/config.js` file does this...
```
Object.keys(Components).forEach(function(key) {
  externals[`mint-ui/packages/${key}/index.js`] = `mint-ui/lib/${key}`;
  externals[`mint-ui/packages/${key}/style.css`] = `mint-ui/lib/${key}/style.css`;
});
```
Could that be why it works in webpack but not browserify?

**Comment by maurop123** [comment]
@Nakurai I figured out a workaround this that doesn't mean dropping browserify.

Import the component individually instead of the whole thing at once. It should work just fine.

Still, the all-in-one import should work on browserify too :confused:

**Comment by maurop123** [comment]
Here's is how I ended up importing all the Mint-UI components at once.
```
import Vue from 'vue'
import 'mint-ui/lib/style.css'
import * as Mint from 'mint-ui'

const MintUI = Object.keys(Mint).map(key =>  Mint[key])
registerComponents([].concat(MintUI))

function registerComponents(components) {
    Object.keys(components).map(key => components[key])
    .filter(component => typeof(component) === 'object' && component.hasOwnProperty('name'))
    .map(component => Vue.component(component.name, component))
}
}
```
I've forked mint-ui and hope to find a way for it to work better with Browserify. Hope this helps for now.
