### ISSUE TITLE
停止支持旧版本chrome了吗？

### ISSUE THREAD

**Issue by 262060984** [ElemeFE/mint-ui#840]
chrome 版本 45.0.2421.0 m

重现步骤

1、vue-cli生成项目,npm install
2、npm install mint-ui -S
3、main.js中引入mint-ui
`import Vue from 'vue'
import Mint from 'mint-ui'
import App from './App'
import router from './router'

Vue.use(Mint)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})`
4、npm run dev
结果
报错Uncaught TypeError: Object.assign is not a function

firefox正常，chrome更新后正常

**Comment by galenyuan** [comment]
..是你自己没有加 ES6 的 polyfill

**Comment by 262060984** [comment]
我没有写代码，报错的地方是
mint-ui.common.js?1045:860

**Comment by galenyuan** [comment]
囧，buble的锅，把
```javascript
{
  ...obj
}
```
转成
```javascript
Object.assign()
```
了

**Comment by galenyuan** [comment]
已修复，更新最新版本即可
