### ISSUE TITLE
[Bug Report] Swipe组件点击非滑动，触发多次initTimer而未清除Timer造成的Bug

### ISSUE THREAD

**Issue by saiigo** [ElemeFE/mint-ui#844]
### Mint UI version
2.2.5

### OS/Browsers version
chrome 58.0.3029.81

### Vue version
2.2.6

### Reproduction Link
[http://elemefe.github.io/mint-ui/#/swipe](http://elemefe.github.io/mint-ui/#/swipe)

### Steps to reproduce
swipe的第一个范例，连续点击滚动的图片，会导致滑动速度变快的问题

### What is Expected?
应该是仍然按照原先设置的速度进行滚动的

### What is actually happening?
实际由于每次点击事件touchend都触发了initTimer而没有清除clearTimer处理，造成多个定时器的产生，导致滑动异常的bug。
clearTimer只在touchmove中进行了，在点击非滑动时候就会造成bug

**Comment by errormonstor** [comment]
看了一下源码，在touchend里面clearTimer应该可以解决

**Comment by muuyao** [comment]
这个bug有在解决么？没有发pr的么？

**Comment by galenyuan** [comment]
fixed in #871
