### ISSUE TITLE
DatetimePicker呼不出来

### ISSUE THREAD

**Issue by htank-wang** [ElemeFE/mint-ui#853]
使用vue官网的构建命令生成的工程使用DatetimePicker组件时呼不出来

半个月以前构建的工程是可以，是否与vue版本升级有关，麻烦帮忙定位下问题

**Comment by ViYaYaYa** [comment]
今早执行npm update后，遇到同样问题。暂未发现其他组件相关问题。

**Comment by galenyuan** [comment]
应该是Vue升级2.3导致的 我去看一下

**Comment by cixiwcy** [comment]
确实 之前的项目还能用  今天npm i 的就是调不出来 还不报错

**Comment by htank-wang** [comment]
有没什么降级方案 或临时解决方案

**Comment by funnycherry** [comment]
遇到同样问题，之前可以呼出，现在无法呼出且无报错。

**Comment by liaojianGH** [comment]
第一次用这个组件，我也遇到这个问题

**Comment by ZhuRay** [comment]
密切关注,同问:有什么临时方案

**Comment by jindasong** [comment]
vue2.3.0的问题，先降级到 vue@2.1.8    vue-template-compiler@2.1.8

**Comment by chuanxd** [comment]
vue@2.2.6 正常

**Comment by Jialufeng** [comment]
我也遇到这个问题，最后用了之前的node包，才得到解决。应该是版本问题。

**Comment by galenyuan** [comment]
已发布v2.2.6，Vue2.3.0以上更新版本即可
