### ISSUE TITLE
[Bug Report] UC浏览器下Lazyload报错

### ISSUE THREAD

**Issue by zx204721** [ElemeFE/mint-ui#856]
### Mint UI version
2.2.5

### OS/Browsers version
android7.0/UC浏览器11.4.9.941

### Vue version
2.3.2

### Reproduction Link
[http://elemefe.github.io/mint-ui/#/](http://elemefe.github.io/mint-ui/#/)

### Steps to reproduce
用UC浏览器打开网址，展示空页面。
附uc开发者版的log：
Uncaught TypeError: undefined is not a function       index.js:69。
报错代码：
Vue.use(Lazyload, {
    loading: require('./assets/loading-spin.svg'),
    attempt: 3,
    ...config.lazyload
  });

### What is Expected?
展示网页内容

### What is actually happening?
展示空白页面

**Comment by galenyuan** [comment]
已修复，更新最新版本即可
