### ISSUE TITLE
[Bug Report] mint-ui demo 不能在手机浏览器中打开

### ISSUE THREAD

**Issue by leavesgreen** [ElemeFE/mint-ui#865]
### Mint UI version
2.2.6

### OS/Browsers version
android 6.0, ios 7, qq浏览器，uc浏览器，sogou浏览器

### Vue version
2.2.6

### Reproduction Link
[http://elemefe.github.io/mint-ui/#/](http://elemefe.github.io/mint-ui/#/)

### Steps to reproduce
用手机浏览器打开mint-ui demo地址即可； 目前发现在微信内置浏览器中可以打开，pc浏览器可以； 但其余浏览器打开都显示空白；

### What is Expected?
正确加载web组件

### What is actually happening?
浏览器打开空白

**Comment by moudicat** [comment]
我也测试了一下，发现UC确实打不开， 但chrome可以。

**Comment by galenyuan** [comment]
文档的demo没更新到最新的Mint，install到本地的Mint不会有这个问题

**Comment by leavesgreen** [comment]
我就是自己开发的项目打不开,才试验了一下这个官方demo,结果也是打不开

**Comment by galenyuan** [comment]
确定你的Mint是最新版本的？我刚才重新构建了一次demo 在UC里已经没问题了 你试一下？

**Comment by owlfj** [comment]
使用cell-swipe做侧滑，用chrome测试没有问题，但是用api-cloud打包后，在手机上测试侧滑时，一侧滑就抖动，抖动后才能侧滑成功，后来使用git上的例子也是同样的问题
