### ISSUE TITLE
[Bug Report] Height of indexList needs to be altered when the browser window has been resized 

### ISSUE THREAD

**Issue by suyi91** [ElemeFE/mint-ui#880]
### Mint UI version
2.2.6

### OS/Browsers version
MacChrome v58.0.3029.110 (64-bit), Android7.1Chrome(latest), iOS10.3 Safari

### Vue version
2.3.3

### Reproduction Link
[https://elemefe.github.io/mint-ui/#/index-list](https://elemefe.github.io/mint-ui/#/index-list)

### Steps to reproduce
    1) open https://elemefe.github.io/mint-ui/#/index-list in browser(Android, iOS or macChrome in responsive mode )
    2) Android, iOS => rotate screen ;  macChrome => click "rotate" button

### What is Expected?
When IndexList's prop "height" is changed, IndexList should re-calculate self's height.

### What is actually happening?
IndexList's height is decided when mounted.

**Comment by galenyuan** [comment]
fixed in #881
