### ISSUE TITLE
mint-ui结合nuxt服务端渲染框架使用时，Swipe组件首屏空白问题

### ISSUE THREAD

**Issue by fetjq** [ElemeFE/mint-ui#885]
问题描述：我使用nuxt脚手架生成了nuxt项目目录,在nuxt.config.js里配置好mint-ui组件库时，在使用Swipe组件，当第一次访问该组件或者刷新页面时，轮播图组件首屏显示不出任何内容。当轮播图完成一个循环，首屏才能正确显示。
尝试解决方案：
1.在nuxt.config.js里配置 plugins: [{ src: '~plugins/mint', ssr: false }],意思是只在浏览器渲染，不再使用服务端渲染mint-ui，这样做可以解决首屏显示问题，但浏览器会报错
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. 
2.网上有说使用局部注册的方式进行mint-ui注册使用，我尝试着试了一下，依然无法解决首屏显示问题。
3.当我使用vue官方脚手架时，mint-ui轮播图可正常显示。这种情况下，是mint-ui的ssr处理方式有问题，还是nuxt的处理方式有问题呢？

请大神不吝赐教，谢谢。

**Comment by xianweics** [comment]
我也遇到
