### ISSUE TITLE
[Bug Report] swipe组件，点击几次后，轮播的时间间隔 会加快

### ISSUE THREAD

**Issue by megone** [ElemeFE/mint-ui#904]
### Mint UI version
2.2.7

### OS/Browsers version
win10 / chrome 48

### Vue version
"vue": "^2.2.6"

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/249/](https://jsfiddle.net/pj71jkyw/249/)

### Steps to reproduce
1.给第一个轮播图swipe item添加点击事件
2.多点击几次第一个轮播图的文字 “ 1 ”
3.轮播的间隔加快

### What is Expected?
轮播的间隔时间与初始设置一致

### What is actually happening?
轮播的间隔加快

**Comment by yuling** [comment]
请问 有解决方案了吗？

**Comment by Say-Hello** [comment]
更新到最新版本就会没问题啦

**Comment by yuling** [comment]
谢谢，之前一直没上来看看，这个问题解决了，也没发现

**Comment by Say-Hello** [comment]
@yuling 你在手机里用，会闪动吗，设置了auto以后，会闪

**Comment by yuling** [comment]
这个没留意，但是现在用的，没有问题

**Comment by lonfi123** [comment]
真的解决了吗？我用的swiper.2.7.6.min.js还是这样啊，刚开始没问题，一会儿后，不知道怎么时间就缩短，自动轮播加快，还会出现图片一闪就切换的情况

**Comment by lonfi123** [comment]
我的是这样：
  autoplay: 4000,
            speed: 1500,
            slidesPerView: 2,
            slidesPerGroup: 2,
            autoplayDisableOnInteraction: false,
            loop: true,
            grabCursor: true,
            paginationClickable: true,
            observer:true,
            observeParents:true,
