### ISSUE TITLE
请问如何动态绑定 filed内input的值。

### ISSUE THREAD

**Issue by zhuqiuyang** [ElemeFE/mint-ui#93]
因为field中的内容 主要用于提交使用，但因为它是片段组件，无法通过v-model绑定，如何能获取其中input的值， 或者把field中的输入内容绑定到一个特定的变量上呢。
想请教一下。

**Comment by QingWei-Li** [comment]
额 文档漏写了。通过 `value` 属性，我一会补充文档
```html
<mt-field
    label="邮箱"
    :value.sync="value"
    placeholder="成功状态">
</mt-field>
```

**Comment by zhuqiuyang** [comment]
@QingWei-Li 好的，谢谢，我想应该有的， 这样表单就可以使用啦。
