### ISSUE TITLE
picker组件 滑动不流畅

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/mint-ui#94]
picker组件 滑动不流畅
特别是滚动即将完的、确定哪一项是选择项的这一个过程。比如滑动到 a和b的之间，这时候需要计算哪一个才是选择项，这时候不流畅。希望能抽出时间优化一下。

**Comment by hee93** [comment]
记得好像是微信里头是不怎么流畅

**Comment by Leopoldthecoder** [comment]
@acmeid 你说的确定哪一项是选择项的过程会不流畅的问题，我试了几个浏览器，没有重现。请问你的浏览器是？以及这个[示例页](http://elemefe.github.io/mint-ui/#!/picker)也会不流畅吗？

**Comment by acmeid** [comment]
示例比较流畅，可能是我本地的太多数据了导致的。。。
