### ISSUE TITLE
MessageBox 的一些建议

### ISSUE THREAD

**Issue by lishengzxc** [ElemeFE/mint-ui#96]
- prompt 是不是可以弹出后，input 获取焦点
- prompt input 框没有`appearance: none;` 可能导致不同浏览器的 input 样式会不一样

**Comment by furybean** [comment]
第二个需要做一下：@Leopoldthecoder 

第一个获取焦点没卵用，键盘并不会弹出。

**Comment by furybean** [comment]
@Leopoldthecoder 第一个现在的浏览器好像可以了，你确认下，没问题也加上。

**Comment by Leopoldthecoder** [comment]
@furybean 好

**Comment by Leopoldthecoder** [comment]
done
