### ISSUE TITLE
FileId 浏览器控制报指令解析失败

### ISSUE THREAD

**Issue by airzhanglin** [ElemeFE/mint-ui#982]
vue.esm.js?65d7:434 [Vue warn]: Failed to resolve directive: modal

(found in <Anonymous>)。拿文档的提供的代码，出现此问题。请问如何解决

**Comment by Leopoldthecoder** [comment]
应该是把 `v-model` 写成了 `v-modal`

**Comment by airzhanglin** [comment]
改了之后还是有这个警告
