### ISSUE TITLE
[Bug Report] Picker change事件中我用变量保存了values但是在change事件第二次触发时该变量还没赋值就已经是改变后的值了

### ISSUE THREAD

**Issue by confirmTing** [ElemeFE/mint-ui#986]
### Mint UI version
2.2.7

### OS/Browsers version
谷歌59.0.3071.115

### Vue version
2.4.1

### Reproduction Link
[https://jsfiddle.net/smallMing/L754mh9s/1/](https://jsfiddle.net/smallMing/L754mh9s/1/)

### Steps to reproduce
一上来的时候效果是对的，但是当我滑动了以后，立马就可以看到我的变量还未赋值但是值已经是最新的了

### What is Expected?
不要改变我的变量，在我未赋值以前

### What is actually happening?
我的变量莫名其妙的被改变了

**Comment by win5do** [comment]
数组和对象是引用数据类型，基础！！！改成直接复制就行了
https://jsfiddle.net/L754mh9s/3/

**Comment by confirmTing** [comment]
@win5do  感谢大佬， 没注意到这点小细节，惭愧惭愧
