### ISSUE TITLE
文档栗子错误

### ISSUE THREAD

**Issue by zhcsyncer** [ElemeFE/mint-ui#99]
文档中tabbar 组件部分, 栗子 
``import { Tabbar, TabbarItem } from 'mint-ui';``
中导出的变量名TabbarItem有误...应为TabItem

**Comment by QingWei-Li** [comment]
fixed https://github.com/mint-ui/docs/commit/ab543b0d9ffd7f7ccbfba081f0ce6d9dd9d57162
