### ISSUE TITLE
[Bug Report] script引入模式下使用Datetime Picker设置startDate无效

### ISSUE THREAD

**Issue by wandiao** [ElemeFE/mint-ui#994]
### Mint UI version
2.2.7

### OS/Browsers version
chrome

### Vue version
2.3.3

### Reproduction Link
[https://wandiao.github.io/test/](https://wandiao.github.io/test/)

### Steps to reproduce
源码如下 https://github.com/wandiao/test/blob/master/index.html

### What is Expected?
设置日期的最小可选值为当前时间

### What is actually happening?
日期的最小值为10年前

**Comment by wuwenchang** [comment]
在标签里面加:startDate="startDate"  :endDate="endDate"
script中
data(){
    return {
      startDate: new Date('1950-1-1'),
      endDate: new Date()
    }
}
